import type { McqItem } from "@/lib/types";
import { mcq } from "./build";

export const DIAGNOSTIC_ITEMS: McqItem[] = [
  mcq({
    id: "diag-01",
    family: "diag-vector",
    unit: "bridge",
    topic: "B.1",
    objective: "B.1.A",
    sciencePractice: 1,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A force of 5.0 N points 53° above +x (a 3-4-5 orientation). The x-component is",
    choices: [
      { id: "A", text: "5.0 N" },
      { id: "B", text: "3.0 N" },
      { id: "C", text: "4.0 N" },
      { id: "D", text: "−3.0 N", distractorTag: "wrong-quadrant" },
    ],
    correct: "B",
    explanation: "$F_x = 5\\cos 53^\\circ \\approx 3.0\\,\\mathrm{N}$ (adjacent side). $F_y \\approx 4.0\\,\\mathrm{N}$. Quadrant I, so $F_x>0$.",
    distractorRationales: {
      A: "Magnitude, not a component.",
      C: "That is the y-component, $5\\sin 53^\\circ$.",
      D: "The force is in quadrant I; $F_x$ is positive.",
    },
  }),
  mcq({
    id: "diag-02",
    family: "diag-slope",
    unit: "bridge",
    topic: "B.3",
    objective: "B.3.A",
    sciencePractice: 1,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A graph of $x(t)$ is a straight line from $(0,0)$ to $(4.0\\,\\mathrm{s},\\,8.0\\,\\mathrm{m})$. The velocity is",
    choices: [
      { id: "A", text: "8.0 m/s" },
      { id: "B", text: "2.0 m/s" },
      { id: "C", text: "32 m/s" },
      { id: "D", text: "0.50 m/s" },
    ],
    correct: "B",
    explanation: "Slope $\\Delta x/\\Delta t = 8/4 = 2.0\\,\\mathrm{m/s}$. Constant because the graph is linear.",
    distractorRationales: {
      A: "That is the displacement, not the rate.",
      C: "That multiplies instead of dividing.",
      D: "That is $\\Delta t/\\Delta x$.",
    },
  }),
  mcq({
    id: "diag-03",
    family: "diag-derivative",
    unit: "bridge",
    topic: "B.4",
    objective: "B.4.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "If $Q(t)= (6.0\\,\\mu\\mathrm{C})\\, e^{-t/0.020\\mathrm{s}}$, $I=dQ/dt$ at $t=0$ is",
    choices: [
      { id: "A", text: "0" },
      { id: "B", text: "$-3.0\\times 10^{-4}\\,\\mathrm{A}$" },
      { id: "C", text: "$+3.0\\times 10^{-4}\\,\\mathrm{A}$" },
      { id: "D", text: "$-6.0\\,\\mu\\mathrm{A}$" },
    ],
    correct: "B",
    explanation: "$dQ/dt = -Q/\\tau$. At $t=0$, $I= -(6.0\\times 10^{-6})/0.020 = -3.0\\times 10^{-4}\\,\\mathrm{A}$. Charge is leaving the positive plate.",
    distractorRationales: {
      A: "The exponential is smooth but the initial slope is not zero.",
      C: "Missed the minus sign from the chain rule.",
      D: "Forgot to divide by $\\tau$ correctly (used 1 s or mixed μ).",
    },
  }),
  mcq({
    id: "diag-04",
    family: "diag-integral",
    unit: "bridge",
    topic: "B.5",
    objective: "B.5.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "Uniform $\\lambda = 2.0\\,\\mu\\mathrm{C/m}$ on a rod from $x=0$ to $x=0.50\\,\\mathrm{m}$. The total charge is",
    choices: [
      { id: "A", text: "$1.0\\,\\mu\\mathrm{C}$" },
      { id: "B", text: "$4.0\\,\\mu\\mathrm{C}$" },
      { id: "C", text: "$2.0\\,\\mu\\mathrm{C}$" },
      { id: "D", text: "$0.50\\,\\mu\\mathrm{C}$" },
    ],
    correct: "A",
    explanation: "$Q=\\lambda L = (2.0\\,\\mu\\mathrm{C/m})(0.50\\,\\mathrm{m})=1.0\\,\\mu\\mathrm{C}$.",
    distractorRationales: {
      B: "Used $L=2.0\\,\\mathrm{m}$ or $\\lambda L^2$.",
      C: "Quoted $\\lambda$ as if it were already the charge.",
      D: "Multiplied by $L^2$ or used 0.25 m.",
    },
  }),
  mcq({
    id: "diag-05",
    family: "diag-energy",
    unit: "bridge",
    topic: "B.8",
    objective: "B.8.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A 2.0 kg object falls 1.5 m from rest, mechanical energy conserved. Speed at the bottom is closest to",
    choices: [
      { id: "A", text: "1.5 m/s" },
      { id: "B", text: "5.4 m/s" },
      { id: "C", text: "15 m/s" },
      { id: "D", text: "3.0 m/s" },
    ],
    correct: "B",
    explanation: "$v=\\sqrt{2gh}=\\sqrt{2\\times 9.8\\times 1.5}\\approx 5.4\\,\\mathrm{m/s}$. Mass cancels.",
    distractorRationales: {
      A: "Used $v=h$ or $v=\\sqrt{h}$.",
      C: "Forgot the square root, or used $mgh$ as speed.",
      D: "Used $v=gh$ without 2 and without square root, roughly.",
    },
  }),
  mcq({
    id: "diag-06",
    family: "diag-coulomb",
    unit: 8,
    topic: "8.1",
    objective: "8.1.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 70,
    prereqSkill: "bridge-vectors",
    pool: "diagnostic",
    stem: "Two point charges $+q$ and $+q$ are 2.0 m apart. A third charge $+Q$ at the midpoint feels a net force that is",
    choices: [
      { id: "A", text: "zero" },
      { id: "B", text: "to the right, twice one Coulomb force" },
      { id: "C", text: "undefined" },
      { id: "D", text: "attractive toward both, hence zero? no — they repel" },
    ],
    correct: "A",
    explanation: "Both sources are positive, so each repels $+Q$ away: left source pushes right, right source pushes left. Equal distances, equal $|q|$, net zero.",
    distractorRationales: {
      B: "Would be true for $+q$ and $-q$ at the ends, not two like charges.",
      C: "Superposition is defined at the midpoint; the third charge is not on top of a source.",
      D: "Like charges repel; the two forces oppose.",
    },
  }),
  mcq({
    id: "diag-07",
    family: "diag-flux",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A closed surface encloses zero net charge. Which must be true?",
    choices: [
      { id: "A", text: "E = 0 at every point on the surface.", distractorTag: "flux-equals-local-field" },
      { id: "B", text: "Net electric flux through the surface is zero." },
      { id: "C", text: "There are no charges anywhere outside the surface." },
      { id: "D", text: "The surface must be a sphere." },
    ],
    correct: "B",
    misconception: "flux-equals-local-field",
    explanation:
      "Gauss’s law: $\\Phi_{\\mathrm{net}}=Q_{\\mathrm{enc}}/\\varepsilon_0=0$. That does not force the integrand $E$ to vanish. External charges and uniform fields are counterexamples. The surface need not be a sphere.",
    distractorRationales: {
      A: "Confuses a surface integral with a local field. Uniform field through a cube has $E\\neq 0$ and $\\Phi_{\\mathrm{net}}=0$.",
      C: "External charges are allowed; they simply are not enclosed.",
      D: "Gauss’s law holds for any closed surface. Spheres are useful, not required.",
    },
  }),
  mcq({
    id: "diag-08",
    family: "diag-potential",
    unit: 9,
    topic: "9.2",
    objective: "9.2.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "At a point, $V=0$ (with $V(\\infty)=0$). Which is possible?",
    choices: [
      { id: "A", text: "E must be 0 there." },
      { id: "B", text: "E can be nonzero, as at a dipole midpoint." },
      { id: "C", text: "No charge may exist anywhere." },
      { id: "D", text: "The point must lie on a conductor." },
    ],
    correct: "B",
    explanation: "Potential is a scalar sum. Equal distances from $+q$ and $-q$ give $V=0$ with $E$ pointing from $+$ to $-$.",
    distractorRationales: {
      A: "Zero value of $V$ is not zero slope.",
      C: "A dipole is a counterexample.",
      D: "Conductors are equipotentials, not the only $V=0$ locations.",
    },
  }),
  mcq({
    id: "diag-09",
    family: "diag-conductor",
    unit: 10,
    topic: "10.1",
    objective: "10.1.A",
    sciencePractice: 3,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A solid metal sphere carries net charge $+Q$ in electrostatic equilibrium. Inside the metal,",
    choices: [
      { id: "A", text: "E = 0" },
      { id: "B", text: "E is the Coulomb field of Q as a point at the centre" },
      { id: "C", text: "E = 0 only at the exact centre" },
      { id: "D", text: "E = σ/ε0 throughout the volume" },
    ],
    correct: "A",
    explanation: "In equilibrium the field in conducting material is zero. Excess charge is on the outer surface.",
    distractorRationales: {
      B: "That describes the exterior of a spherical conductor, not the interior of the metal.",
      C: "The entire conducting material is field-free, not just a point.",
      D: "σ/ε0 is the field just outside a conductor, not inside.",
    },
  }),
  mcq({
    id: "diag-10",
    family: "diag-cap-energy",
    unit: 10,
    topic: "10.3",
    objective: "10.3.B",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 65,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A capacitor stays connected to a battery while its plate separation increases. Stored energy",
    choices: [
      { id: "A", text: "increases because U = Q²/(2C) and C falls" },
      { id: "B", text: "decreases because V is fixed and C falls" },
      { id: "C", text: "is unchanged" },
      { id: "D", text: "becomes negative" },
    ],
    correct: "B",
    explanation: "Battery connected: $V$ fixed. $U=\\tfrac12 C V^2$ falls with $C$. $Q$ is not fixed, so quoting $Q^2/(2C)$ with the old $Q$ is inconsistent.",
    distractorRationales: {
      A: "That argument would apply if the capacitor were isolated (fixed $Q$).",
      C: "Both $C$ and $Q$ change.",
      D: "Energy stored is positive.",
    },
  }),
  mcq({
    id: "diag-11",
    family: "diag-kirchhoff",
    unit: 11,
    topic: "11.6",
    objective: "11.6.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A loop equation yields $I=-0.25\\,\\mathrm{A}$ relative to your drawn arrow. The actual current is",
    choices: [
      { id: "A", text: "impossible; current cannot be negative" },
      { id: "B", text: "0.25 A opposite the arrow" },
      { id: "C", text: "0.25 A along the arrow, ignoring the sign" },
      { id: "D", text: "zero, because a negative result means no current" },
    ],
    correct: "B",
    explanation: "The sign is relative to the assumed direction. Reverse the arrow and take 0.25 A.",
    distractorRationales: {
      A: "Negative current is a convention, not an error.",
      C: "Dropping the sign keeps the wrong direction.",
      D: "A negative value is a directed 0.25 A, not zero.",
    },
  }),
  mcq({
    id: "diag-12",
    family: "diag-rc",
    unit: 11,
    topic: "11.8",
    objective: "11.8.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "bridge-exponentials",
    pool: "diagnostic",
    stem: "Just after a switch closes to charge an initially uncharged capacitor from a battery through R, the current is",
    choices: [
      { id: "A", text: "0" },
      { id: "B", text: "ε/R" },
      { id: "C", text: "εC" },
      { id: "D", text: "infinite" },
    ],
    correct: "B",
    explanation: "$V_C(0^+)=0$, so $\\mathcal{E}=IR$ at that instant. Later $I\\to 0$.",
    distractorRationales: {
      A: "That is the long-time current, not $t=0^+$.",
      C: "That is $Q_\\infty$, not a current.",
      D: "Finite R keeps I finite.",
    },
  }),
  mcq({
    id: "diag-13",
    family: "diag-lorentz",
    unit: 12,
    topic: "12.1",
    objective: "12.1.A",
    sciencePractice: 1,
    difficulty: 3,
    expectedSeconds: 55,
    prereqSkill: "bridge-vectors",
    pool: "diagnostic",
    stem: "A proton moves right through a magnetic field out of the page. The magnetic force is",
    choices: [
      { id: "A", text: "up the page" },
      { id: "B", text: "down the page" },
      { id: "C", text: "out of the page" },
      { id: "D", text: "in the direction of v" },
    ],
    correct: "B",
    explanation: "Right-hand rule: fingers right, palm facing you (out), thumb down. Proton is positive. (If +x right, +y up, +z out: $\\hat{x}\\times\\hat{z}=-\\hat{y}$.)",
    distractorRationales: {
      A: "That would be an electron, or a reversed B.",
      C: "Magnetic force is perpendicular to B, not along B.",
      D: "Magnetic force is perpendicular to v and does no work.",
    },
  }),
  mcq({
    id: "diag-14",
    family: "diag-lenz",
    unit: 13,
    topic: "13.3",
    objective: "13.3.A",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "A loop faces an increasing magnetic field out of the page. The induced current, viewed from the same side, is",
    choices: [
      { id: "A", text: "clockwise" },
      { id: "B", text: "counterclockwise" },
      { id: "C", text: "zero because the loop is at rest" },
      { id: "D", text: "out of the page" },
    ],
    correct: "A",
    explanation: "Oppose the increase of out-of-page flux: induced B into the page. Thumb into page → fingers clockwise.",
    distractorRationales: {
      B: "That would add to the increase (opposing B rather than dB/dt).",
      C: "The loop need not move; B can change in time.",
      D: "Current is in the wire, around the loop, not a vector out of the page.",
    },
  }),
  mcq({
    id: "diag-15",
    family: "diag-de",
    unit: "bridge",
    topic: "B.7",
    objective: "B.7.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "none",
    pool: "diagnostic",
    stem: "The equation $dQ/dt = -Q/(RC)$ with $Q(0)=Q_0$ has solution",
    choices: [
      { id: "A", text: "$Q_0 e^{-t/(RC)}$" },
      { id: "B", text: "$Q_0 e^{+t/(RC)}$" },
      { id: "C", text: "$Q_0(1-e^{-t/(RC)})$" },
      { id: "D", text: "$Q_0 RC / t$" },
    ],
    correct: "A",
    explanation: "Separable decay. The charging form (C) starts at 0, contradicting $Q(0)=Q_0$ unless $Q_0=0$.",
    distractorRationales: {
      B: "Positive exponent would grow without bound.",
      C: "Charging from zero toward $C\\mathcal{E}$, a different initial condition.",
      D: "Not a solution of the DE; fails a unit check in the exponent sense.",
    },
  }),
];
