import type { McqItem } from "@/lib/types";
import { mcq } from "./build";

function easy(
  id: string,
  family: string,
  unit: McqItem["unit"],
  topic: string,
  objective: string,
  stem: string,
  choices: McqItem["choices"],
  correct: "A" | "B" | "C" | "D",
  explanation: string,
  distractorRationales: NonNullable<McqItem["distractorRationales"]>,
  extra: Partial<McqItem> = {},
): McqItem {
  return mcq({
    id,
    family,
    unit,
    topic,
    objective,
    sciencePractice: extra.sciencePractice ?? 2,
    difficulty: extra.difficulty ?? 2,
    expectedSeconds: extra.expectedSeconds ?? 55,
    prereqSkill: extra.prereqSkill ?? "none",
    pool: extra.pool ?? "practice",
    stem,
    choices,
    correct,
    explanation,
    distractorRationales,
    misconception: extra.misconception,
  });
}

export const REST_ITEMS: McqItem[] = [
  easy("br-vec-1", "br-comp", "bridge", "B.1", "B.1.A",
    "A displacement of 10 m at 30° above +x has y-component",
    [{ id: "A", text: "10 m" }, { id: "B", text: "5.0 m" }, { id: "C", text: "8.7 m" }, { id: "D", text: "−5.0 m" }],
    "B", "$10\\sin 30^\\circ=5.0\\,\\mathrm{m}$. Cosine would be the x-component $\\approx 8.7\\,\\mathrm{m}$.",
    { A: "Magnitude.", C: "That is $10\\cos 30^\\circ$, the x-component.", D: "Quadrant I; y is positive." }),
  easy("br-vec-2", "br-add", "bridge", "B.1", "B.1.A",
    "$\\vec{A}=3\\,\\hat{\\imath}-4\\,\\hat{\\jmath}$ and $\\vec{B}=-3\\,\\hat{\\imath}+4\\,\\hat{\\jmath}$. $\\vec{A}+\\vec{B}$ is",
    [{ id: "A", text: "$\\vec{0}$" }, { id: "B", text: "$6\\,\\hat{\\imath}$" }, { id: "C", text: "$-8\\,\\hat{\\jmath}$" }, { id: "D", text: "magnitude 10" }],
    "A", "Components cancel pairwise. The vectors are equal and opposite.",
    { B: "Added x without y, or doubled A_x incorrectly.", C: "Added y with a sign error.", D: "That is $|A|$ or $|B|$, not the sum." }),
  easy("br-vec-r", "br-neg-comp", "bridge", "B.1", "B.1.A",
    "A force has $F_x=-6.0\\,\\mathrm{N}$ and $F_y=0$. This means the force",
    [{ id: "A", text: "does not exist" }, { id: "B", text: "points opposite the declared +x axis" }, { id: "C", text: "has magnitude −6 N" }, { id: "D", text: "points along +y" }],
    "B", "A negative component is a direction relative to your axis. Magnitude is 6.0 N.",
    { A: "Negative is allowed.", C: "Magnitude is never negative.", D: "F_y=0." }, { pool: "retrieval" }),
  easy("br-alg-1", "br-rearr", "bridge", "B.2", "B.2.A",
    "From $E=kQ/r^2$, $r$ is",
    [{ id: "A", text: "$kQ/E$" }, { id: "B", text: "$\\sqrt{kQ/E}$" }, { id: "C", text: "$kQ/E^2$" }, { id: "D", text: "$E/(kQ)$" }],
    "B", "Multiply by $r^2$, divide by $E$, take the positive root because $r$ is a distance.",
    { A: "Forgot the square.", C: "Squared the wrong quantity.", D: "Inverted the relation." }),
  easy("br-graph-1", "br-area-I", "bridge", "B.3", "B.3.A",
    "The area under an $I(t)$ graph from 0 to 4 s is 8 C. That area is",
    [{ id: "A", text: "average current" }, { id: "B", text: "net charge that passed" }, { id: "C", text: "power" }, { id: "D", text: "resistance" }],
    "B", "$Q=\\int I\\,dt$. Average current would be that charge divided by 4 s.",
    { A: "That would be area divided by time.", C: "Power needs voltage as well.", D: "Not an integral of I." }),
  easy("br-graph-r", "br-V-slope", "bridge", "B.3", "B.3.A",
    "On a $V(x)$ graph, a region of zero slope means",
    [{ id: "A", text: "$V=0$" }, { id: "B", text: "$E_x=0$ on that interval" }, { id: "C", text: "flux is zero" }, { id: "D", text: "charge is zero everywhere" }],
    "B", "$E_x=-dV/dx$. A flat $V$ can sit at 12 V; it need not be the reference zero.",
    { A: "Zero slope is not zero value.", C: "Flux needs a surface and $\\vec{E}\\cdot d\\vec{A}$.", D: "A uniform nonzero field also has constant slope, not zero slope." }, { pool: "retrieval", sciencePractice: 1 }),
  easy("br-der-1", "br-dPhi", "bridge", "B.4", "B.4.A",
    "$\\Phi_B=0.050 t^2$ (SI). $|d\\Phi_B/dt|$ at $t=2.0\\,\\mathrm{s}$ is",
    [{ id: "A", text: "0.050 V" }, { id: "B", text: "0.20 V" }, { id: "C", text: "0.10 V" }, { id: "D", text: "0.20 t V" }],
    "B", "$d\\Phi/dt=0.10 t$, so at 2.0 s the value is 0.20 V. (Emf magnitude for one turn.)",
    { A: "Used Φ itself or forgot the 2 from the power rule.", C: "The coefficient 0.10 without multiplying by t=2.", D: "Did not evaluate at the given t." }),
  easy("br-int-1", "br-lambda-x", "bridge", "B.5", "B.5.A",
    "A rod from 0 to $L$ has $\\lambda=bx$. Total $Q$ is",
    [{ id: "A", text: "$bL$" }, { id: "B", text: "$\\tfrac12 b L^2$" }, { id: "C", text: "$bL^2$" }, { id: "D", text: "$b$" }],
    "B", "$Q=\\int_0^L bx\\,dx=\\tfrac12 b L^2$. Uniform $\\lambda$ would have given $\\lambda L$.",
    { A: "Used $\\lambda(L)\\times 1$ or forgot the integral.", C: "Forgot 1/2.", D: "Quoted the constant $b$." }),
  easy("br-exp-1", "br-tau-def", "bridge", "B.6", "B.6.A",
    "$I=I_0 e^{-t/\\tau}$ equals $I_0/e$ when $t$ equals",
    [{ id: "A", text: "$\\tau$" }, { id: "B", text: "$\\tau\\ln 2$" }, { id: "C", text: "$2\\tau$" }, { id: "D", text: "0" }],
    "A", "$e^{-1}$ at $t=\\tau$. Half remaining is $\\tau\\ln 2$.",
    { B: "That is the half-life marker, not $1/e$.", C: "A rule-of-thumb later time.", D: "At t=0, I=I0." }),
  easy("br-de-1", "br-charge-form", "bridge", "B.7", "B.7.A",
    "Charging from $Q(0)=0$ toward $C\\mathcal{E}$ is described by",
    [{ id: "A", text: "$C\\mathcal{E}\\,e^{-t/RC}$" }, { id: "B", text: "$C\\mathcal{E}(1-e^{-t/RC})$" }, { id: "C", text: "$C\\mathcal{E}\\, t/RC$" }, { id: "D", text: "$\\mathcal{E}/R$" }],
    "B", "Starts at 0 and approaches $C\\mathcal{E}$. Pure exponential decay would start at $C\\mathcal{E}$.",
    { A: "Discharge shape, wrong initial condition.", C: "Linear approximation, not the DE solution.", D: "A current, not a charge." }),
  easy("br-en-1", "br-proton-K", "bridge", "B.8", "B.8.A",
    "A proton released from rest moves to a location where $U$ has decreased by $1.6\\times 10^{-17}\\,\\mathrm{J}$. Its $K$ is then",
    [{ id: "A", text: "0" }, { id: "B", text: "$1.6\\times 10^{-17}\\,\\mathrm{J}$" }, { id: "C", text: "$-1.6\\times 10^{-17}\\,\\mathrm{J}$" }, { id: "D", text: "100 eV exactly, always" }],
    "B", "Conservative electrostatics: $\\Delta K=-\\Delta U$. $1.6\\times 10^{-17}\\,\\mathrm{J}=100\\,\\mathrm{eV}$, but the stem already gave joules.",
    { A: "It speeds up.", C: "Kinetic energy is not negative.", D: "The conversion happens to be 100 eV, but the question asked for K matching ΔU." }),
  easy("br-force-1", "br-equil", "bridge", "B.9", "B.9.A",
    "A charged object hanging at rest in an electric field has net force",
    [{ id: "A", text: "equal to $qE$" }, { id: "B", text: "zero" }, { id: "C", text: "equal to $mg$" }, { id: "D", text: "undefined, because electrostatic forces are not Newtonian" }],
    "B", "At rest, $\\sum F=0$. $qE$, tension, and weight cancel as a set.",
    { A: "That is one force, not the net.", C: "Weight is one force.", D: "Electric force enters Newton’s second law." }),
  easy("br-unit-1", "br-E-units", "bridge", "B.10", "B.10.A",
    "Which pair are identical units of electric field?",
    [{ id: "A", text: "N/C and V/m" }, { id: "B", text: "J/C and N/C" }, { id: "C", text: "T and N/C" }, { id: "D", text: "Wb and V" }],
    "A", "J/(C·m)=N/C because J=N·m. J/C is the volt. T is magnetic field. Wb is flux.",
    { B: "J/C is potential.", C: "Tesla is magnetic.", D: "Different quantities; related by Faraday’s law in time, not as units of E." }),
  easy("br-sign-1", "br-neg-I", "bridge", "B.11", "B.11.A",
    "Power in an ohmic resistor carrying $I=-0.50\\,\\mathrm{A}$ with $R=8.0\\,\\Omega$ is",
    [{ id: "A", text: "−2.0 W (the resistor generates energy)" }, { id: "B", text: "2.0 W dissipated" }, { id: "C", text: "0" }, { id: "D", text: "4.0 W" }],
    "B", "$P=I^2 R=(0.25)(8)=2.0\\,\\mathrm{W}$. The minus sign is directional.",
    { A: "Joule heating is not negative.", C: "Current is not zero.", D: "Used $|I|R$ as power." }),
  easy("br-lim-1", "br-far-ring", "bridge", "B.12", "B.12.A",
    "As $z\\to\\infty$ on the axis of a charged ring of charge $Q$, $E_z$ approaches",
    [{ id: "A", text: "$\\infty$" }, { id: "B", text: "$kQ/z^2$" }, { id: "C", text: "$kQ/R^2$" }, { id: "D", text: "a nonzero constant" }],
    "B", "Far away the ring is a point. At the centre $E=0$, the opposite limit.",
    { A: "Fields of localised charge vanish at infinity.", C: "A near-field scale, not the far limit.", D: "That is an infinite sheet." }),

  easy("u9-u-1", "u9-pair-U", 9, "9.1", "9.1.A",
    "Relative to $U(\\infty)=0$, two protons $0.10\\,\\mathrm{nm}$ apart have $U$ that is",
    [{ id: "A", text: "negative" }, { id: "B", text: "positive" }, { id: "C", text: "zero" }, { id: "D", text: "unbounded negative" }],
    "B", "Like charges: $U=ke^2/r>0$. You do positive work pushing them together from infinity.",
    { A: "Opposite charges have negative U.", C: "Only at infinite separation in this reference.", D: "U is finite at finite r." }),
  easy("u9-u-r", "u9-three-U", 9, "9.1", "9.1.A",
    "When assembling point charges, $U$ of the system is obtained by",
    [{ id: "A", text: "summing $kq_i/r_i$ as if it were V, then multiplying by nothing" }, { id: "B", text: "summing $k q_i q_j/r_{ij}$ over each pair once" }, { id: "C", text: "summing $k q_i q_j/r_{ij}$ over each pair twice" }, { id: "D", text: "using $qEd$ always" }],
    "B", "Each pair counted once. Counting twice double-counts energy. $qEd$ is a uniform-field special case.",
    { A: "That is closer to potential, not system U.", C: "Double-counting.", D: "Only for uniform E and a specified path/reference." }, { pool: "retrieval" }),
  easy("u9-v-1", "u9-dipole-mid-V", 9, "9.2", "9.2.A",
    "Midway between $+4\\,\\mathrm{nC}$ and $-4\\,\\mathrm{nC}$ separated by 20 cm, $V$ (with $V(\\infty)=0$) is",
    [{ id: "A", text: "0" }, { id: "B", text: "$2k(4\\mathrm{nC})/0.10$" }, { id: "C", text: "negative and large" }, { id: "D", text: "equal to $E$ times 0.10 m" }],
    "A", "Equal distances, opposite charges: scalar V cancels. E does not cancel.",
    { B: "Added unsigned potentials.", C: "Signs cancel.", D: "Confuses ΔV=−∫E dl along a path with V at a point." }),
  easy("u9-v-2", "u9-uniform-dV", 9, "9.2", "9.2.A",
    "Uniform $E=150\\,\\mathrm{N/C}$ in $+x$. $V_B-V_A$ for $A$ at $x=0$ and $B$ at $x=0.20\\,\\mathrm{m}$ is",
    [{ id: "A", text: "$+30\\,\\mathrm{V}$" }, { id: "B", text: "$-30\\,\\mathrm{V}$" }, { id: "C", text: "0" }, { id: "D", text: "$150\\,\\mathrm{V}$" }],
    "B", "$\\Delta V=-E_x \\Delta x=-30\\,\\mathrm{V}$. Potential drops along the field.",
    { A: "Missed the minus in $E=-dV/dx$.", C: "Points are not on an equipotential perpendicular to E.", D: "Quoted E as if it were already ΔV." }),
  easy("u9-v-r", "u9-equipot", 9, "9.2", "9.2.A",
    "Moving a test charge along an equipotential",
    [{ id: "A", text: "requires $E=0$" }, { id: "B", text: "gives $\\Delta V=0$; $\\vec{E}$ is perpendicular to the path" }, { id: "C", text: "gives $\\Delta U\\neq 0$ if $q\\neq 0$" }, { id: "D", text: "is impossible if $E\\neq 0$" }],
    "B", "Definition of equipotential. Field lines meet equipotentials at right angles.",
    { A: "E can be nonzero and perpendicular.", C: "ΔU=qΔV=0.", D: "You can move perpendicular to E." }, { pool: "retrieval", sciencePractice: 1 }),
  easy("u9-zero-1", "u9-ring-V", 9, "9.2", "9.2.B",
    "Centre of a charged ring ($V(\\infty)=0$):",
    [{ id: "A", text: "$E=0$, $V=0$" }, { id: "B", text: "$E=0$, $V=kQ/R\\neq 0$" }, { id: "C", text: "$E\\neq 0$, $V=0$" }, { id: "D", text: "both undefined" }],
    "B", "Classic pair: zero field, nonzero potential.",
    { A: "V is kQ/R.", C: "E cancels.", D: "Both are defined." }),
  easy("u9-zero-r", "u9-ref", 9, "9.2", "9.2.B",
    "Adding a constant to $V$ everywhere",
    [{ id: "A", text: "changes $\\vec{E}$" }, { id: "B", text: "changes $\\Delta V$ between two points" }, { id: "C", text: "does not change $\\vec{E}$ or $\\Delta V$" }, { id: "D", text: "is illegal" }],
    "C", "Reference choice. E is a derivative; differences cancel the constant.",
    { A: "Gradient of a constant is zero.", B: "Constants cancel in a difference.", D: "You must state the choice, not forbid it." }, { pool: "retrieval" }),
  easy("u9-ev-1", "u9-poly", 9, "9.3", "9.3.A",
    "$V(x)=6.0x-1.0x^2$ (SI). $E_x$ at $x=1.0\\,\\mathrm{m}$ is",
    [{ id: "A", text: "$-4.0\\,\\mathrm{N/C}$" }, { id: "B", text: "$+4.0\\,\\mathrm{N/C}$" }, { id: "C", text: "$-6.0\\,\\mathrm{N/C}$" }, { id: "D", text: "$5.0\\,\\mathrm{N/C}$ (the value of V)" }],
    "A", "$E_x=-dV/dx=-(6-2x)=-6+2x$. At x=1, $E_x=-4.0\\,\\mathrm{N/C}$.",
    { B: "Dropped the minus.", C: "Evaluated −6 only.", D: "Quoted V." }),
  easy("u9-ev-2", "u9-downhill", 9, "9.3", "9.3.A",
    "If $V$ decreases in the $+x$ direction, a proton released from rest moves",
    [{ id: "A", text: "toward $-x$" }, { id: "B", text: "toward $+x$" }, { id: "C", text: "not at all, because V is a scalar" }, { id: "D", text: "in a circle" }],
    "B", "Protons go to lower V. $E_x=-dV/dx>0$ when V falls with x.",
    { A: "That would be an electron.", C: "The gradient still defines E.", D: "No B field was given." }, { sciencePractice: 1 }),
  easy("u9-ev-r", "u9-graph-E", 9, "9.3", "9.3.A",
    "A $V(x)$ graph falls linearly from 12 V to 0 over 4.0 cm. $E_x$ is",
    [{ id: "A", text: "$300\\,\\mathrm{N/C}$" }, { id: "B", text: "$-300\\,\\mathrm{N/C}$" }, { id: "C", text: "12 N/C" }, { id: "D", text: "0.48 N/C" }],
    "A", "$E_x=-\\Delta V/\\Delta x=-(0-12)/0.040=+300\\,\\mathrm{N/C}$. Field points toward +x, downhill in V.",
    { B: "Missed the minus in $E=-dV/dx$.", C: "Quoted V.", D: "Multiplied V by Δx instead of dividing." }, { pool: "retrieval" }),
  easy("u9-cons-1", "u9-electron-eV", 9, "9.3", "9.3.B",
    "An electron is released from rest at $V=+50\\,\\mathrm{V}$ and reaches $V=0$. Kinetic energy gained is",
    [{ id: "A", text: "50 J" }, { id: "B", text: "50 eV" }, { id: "C", text: "0" }, { id: "D", text: "negative, so it cannot move" }],
    "B", "$\\Delta K=-q\\Delta V$. For an electron $q=-e$, $\\Delta V=-50\\,\\mathrm{V}$, so $\\Delta K=+50\\,\\mathrm{eV}$. Electrons move toward higher $V$ when released from rest.",
    { A: "50 J would be enormous; use electron volts.", C: "$U=qV$ changes.", D: "$U$ decreases because $q$ is negative." }),
  easy("u9-cons-r", "u9-turnaround", 9, "9.3", "9.3.B",
    "A particle with $q=+2e$ and $K=4.0\\,\\mathrm{eV}$ approaches a region 3.0 V higher. It",
    [{ id: "A", text: "passes with $K=10\\,\\mathrm{eV}$" }, { id: "B", text: "passes with $K=-2\\,\\mathrm{eV}$" }, { id: "C", text: "cannot reach that region in this conservative 1-D picture" }, { id: "D", text: "speeds up because $V$ is higher" }],
    "C", "$\\Delta U=+6.0\\,\\mathrm{eV}>K$. It turns around.",
    { A: "Added instead of climbing $U$.", B: "Negative $K$ is not physical here.", D: "Positive charges slow going uphill in $V$." }, { pool: "retrieval" }),
  easy("u10-cond-1", "u10-E-metal", 10, "10.1", "10.1.A",
    "Inside the material of a charged conductor in equilibrium, $E$ is",
    [{ id: "A", text: "0" }, { id: "B", text: "$kQ/r^2$" }, { id: "C", text: "$\\sigma/\\varepsilon_0$" }, { id: "D", text: "maximum at the centre" }],
    "A", "Free charge rearranges until $E$ vanishes in the metal.",
    { B: "Exterior of a sphere.", C: "Just outside the surface.", D: "The whole metal is field-free." }),
  easy("u10-cond-2", "u10-cavity", 10, "10.1", "10.1.A",
    "Empty cavity inside a conductor, no charge in the cavity. Charge on the inner surface is",
    [{ id: "A", text: "the conductor’s net charge" }, { id: "B", text: "0" }, { id: "C", text: "infinite" }, { id: "D", text: "always $+Q$" }],
    "B", "Gaussian surface in the metal: $E=0\\Rightarrow Q_{\\mathrm{enc}}=0$.",
    { A: "Net charge sits on the outer surface if the cavity is empty.", C: "Charge is finite.", D: "Not required." }),
  easy("u10-cond-r", "u10-equipot-vol", 10, "10.1", "10.1.A",
    "A conductor in equilibrium is",
    [{ id: "A", text: "at $V=0$ necessarily" }, { id: "B", text: "an equipotential volume; $V$ need not be zero" }, { id: "C", text: "a region of maximum $E$" }, { id: "D", text: "unable to carry net charge" }],
    "B", "$E=0$ implies $V$ constant. The constant can be 12 V relative to ground.",
    { A: "Reference choice.", C: "$E=0$ inside.", D: "Charged conductors are common." }, { pool: "retrieval" }),
  easy("u10-conn-1", "u10-spheres-share", 10, "10.2", "10.2.A",
    "Spheres of radii $R$ and $2R$, far apart, connected, total charge $Q$. Charge on the smaller is",
    [{ id: "A", text: "$Q/2$" }, { id: "B", text: "$Q/3$" }, { id: "C", text: "$2Q/3$" }, { id: "D", text: "0" }],
    "B", "Common $V\\approx kQ/R$ so $Q\\propto R$. Smaller gets $Q/3$.",
    { A: "Equal-charge myth.", C: "That is the larger sphere.", D: "Charge does not all leave." }),
  easy("u10-conn-r", "u10-not-equal-Q", 10, "10.2", "10.2.A",
    "Two connected conductors of different size have, in equilibrium,",
    [{ id: "A", text: "equal charge" }, { id: "B", text: "equal potential" }, { id: "C", text: "equal surface $E$" }, { id: "D", text: "equal $\\sigma$ always" }],
    "B", "The wire makes one equipotential. Charge splits according to capacitance.",
    { A: "Only if $C$ is equal.", C: "Often larger $E$ on sharper objects.", D: "$\\sigma$ follows curvature." }, { pool: "retrieval", sciencePractice: 3 }),
  easy("u10-cap-1", "u10-C-d", 10, "10.3", "10.3.A",
    "Doubling $d$ for an ideal parallel-plate vacuum capacitor multiplies $C$ by",
    [{ id: "A", text: "2" }, { id: "B", text: "1/2" }, { id: "C", text: "4" }, { id: "D", text: "1" }],
    "B", "$C=\\varepsilon_0 A/d$.",
    { A: "Inverted.", C: "Confused with a stretched wire.", D: "$C$ depends on geometry here." }),
  easy("u10-cap-r", "u10-C-def", 10, "10.3", "10.3.A",
    "For a linear capacitor, $C=Q/V$ is",
    [{ id: "A", text: "independent of $Q$ and $V$ (geometry and dielectric)" }, { id: "B", text: "proportional to $V$" }, { id: "C", text: "defined only at 1 volt" }, { id: "D", text: "equal to $\\varepsilon_0$ always" }],
    "A", "$C$ characterises the device. $Q$ and $V$ scale together.",
    { B: "That would make $Q\\propto V^2$.", C: "Any $V$ in the linear range.", D: "Missing $A/d$ and $\\kappa$." }, { pool: "retrieval" }),
  easy("u10-en-1", "u10-U-isolated", 10, "10.3", "10.3.B",
    "An isolated charged capacitor has $d$ doubled. Stored energy",
    [{ id: "A", text: "halves" }, { id: "B", text: "doubles" }, { id: "C", text: "unchanged" }, { id: "D", text: "becomes zero" }],
    "B", "$Q$ fixed, $C$ halves, $U=Q^2/(2C)$ doubles.",
    { A: "Battery-connected result.", C: "Misses mechanical work.", D: "Charge is still there." }),
  easy("u10-en-2", "u10-U-battery", 10, "10.3", "10.3.B",
    "Battery remains connected while $d$ doubles. Stored energy",
    [{ id: "A", text: "doubles" }, { id: "B", text: "halves" }, { id: "C", text: "quadruples" }, { id: "D", text: "uses original $Q$ in $Q^2/(2C)$" }],
    "B", "$V$ fixed, $C$ halves, $U=\\tfrac12 CV^2$ halves.",
    { A: "Isolated intuition.", C: "Wrong power of 2.", D: "$Q=CV$ also falls." }),
  easy("u10-en-r", "u10-which-formula", 10, "10.3", "10.3.B",
    "Before computing a change in $U$, first identify",
    [{ id: "A", text: "whether $Q$ or $V$ is constrained" }, { id: "B", text: "the colour of the dielectric" }, { id: "C", text: "whether Gauss’s law is optional" }, { id: "D", text: "an official 1–5 score conversion" }],
    "A", "The unit’s central habit. Anannt does not convert uncalibrated percentages into AP scores.",
    { B: "Irrelevant.", C: "Not the point here.", D: "Not offered by this product." }, { pool: "retrieval", sciencePractice: 3 }),
  easy("u10-di-1", "u10-kappa-isolated", 10, "10.4", "10.4.A",
    "Insert $\\kappa=3$ into an isolated capacitor (fixed $Q$). $E$ in the dielectric is multiplied by",
    [{ id: "A", text: "3" }, { id: "B", text: "1/3" }, { id: "C", text: "1" }, { id: "D", text: "0" }],
    "B", "$C\\to\\kappa C$, $V=Q/C$ falls by $\\kappa$, $E=V/d$ falls by $\\kappa$.",
    { A: "Wrong constraint.", C: "Vacuum.", D: "Not perfect screening." }),
  easy("u10-di-r", "u10-kappa-C", 10, "10.4", "10.4.A",
    "Inserting a linear dielectric that fills the gap always",
    [{ id: "A", text: "increases $C$" }, { id: "B", text: "decreases $C$" }, { id: "C", text: "increases $U$ regardless of constraints" }, { id: "D", text: "leaves $C$ unchanged" }],
    "A", "$C=\\kappa C_0$. $U$ rises or falls depending on battery vs isolated.",
    { B: "Opposite.", C: "Isolated $U$ falls.", D: "$\\kappa\\neq 1$ changes $C$." }, { pool: "retrieval" }),
  easy("u11-i-1", "u11-conv-I", 11, "11.1", "11.1.A",
    "Conventional current to the right in a metal means electrons drifting",
    [{ id: "A", text: "to the right" }, { id: "B", text: "to the left" }, { id: "C", text: "not at all" }, { id: "D", text: "at speed $c$" }],
    "B", "Conventional current is the direction positive charge would flow.",
    { A: "Electron charge is negative.", C: "Drift is slow but nonzero.", D: "Drift speeds are typically mm/s." }),
  easy("u11-i-r", "u11-series-I", 11, "11.1", "11.1.A",
    "In a series circuit in the steady state, current is",
    [{ id: "A", text: "used up in each resistor" }, { id: "B", text: "the same at every cross-section" }, { id: "C", text: "largest just after the battery" }, { id: "D", text: "zero in the wires" }],
    "B", "Charge is not consumed. Energy is transferred.",
    { A: "The current-used-up myth.", C: "Same $I$ throughout series.", D: "Ideal wires have $R=0$, not $I=0$." }, { pool: "retrieval" }),
  easy("u11-rho-1", "u11-stretch", 11, "11.2", "11.2.A",
    "A wire is stretched to twice the length at constant volume. $R$ is multiplied by",
    [{ id: "A", text: "2" }, { id: "B", text: "4" }, { id: "C", text: "1/2" }, { id: "D", text: "1" }],
    "B", "$L\\to 2L$, $A\\to A/2$, $R=\\rho L/A\\to 4R$.",
    { A: "Forgot $A$.", C: "Inverted.", D: "$\\rho$ is unchanged, $R$ is not." }),
  easy("u11-rho-r", "u11-rho-vs-R", 11, "11.2", "11.2.A",
    "Resistivity $\\rho$ is primarily a property of",
    [{ id: "A", text: "the material (and temperature)" }, { id: "B", text: "the length only" }, { id: "C", text: "the battery" }, { id: "D", text: "insulation colour" }],
    "A", "$R$ then follows from geometry.",
    { B: "$L$ enters $R$.", C: "Emf is separate.", D: "Irrelevant." }, { pool: "retrieval" }),
  easy("u11-p-1", "u11-series-P", 11, "11.3", "11.3.A",
    "2 Ω and 4 Ω in series on 12 V. Power in the 4 Ω is",
    [{ id: "A", text: "36 W" }, { id: "B", text: "16 W" }, { id: "C", text: "8 W" }, { id: "D", text: "24 W" }],
    "B", "$I=2.0\\,\\mathrm{A}$. $P=I^2 R=16\\,\\mathrm{W}$.",
    { A: "$V^2/R$ with the full 12 V on the 4 Ω.", C: "Power in the 2 Ω.", D: "Total battery power." }),
  easy("u11-p-r", "u11-parallel-P", 11, "11.3", "11.3.A",
    "In parallel at the same $V$, the smaller resistor dissipates",
    [{ id: "A", text: "less power" }, { id: "B", text: "more power" }, { id: "C", text: "equal power" }, { id: "D", text: "zero power" }],
    "B", "$P=V^2/R$.",
    { A: "Series intuition with shared $I$.", C: "Only if $R$ equal.", D: "Nonsense." }, { pool: "retrieval" }),
  easy("u11-mod-1", "u11-terminal-V", 11, "11.4", "11.4.A",
    "A battery $\\mathcal{E}$ with internal $r$ supplying $I$ has terminal voltage",
    [{ id: "A", text: "$\\mathcal{E}$ always" }, { id: "B", text: "$\\mathcal{E}-Ir$" }, { id: "C", text: "$\\mathcal{E}+Ir$" }, { id: "D", text: "$Ir$" }],
    "B", "When discharging. When being charged, $V=\\mathcal{E}+Ir$.",
    { A: "Open-circuit value.", C: "Charging convention.", D: "Internal drop only." }),
  easy("u11-mod-r", "u11-ammeter", 11, "11.4", "11.4.A",
    "An ideal ammeter is modelled as",
    [{ id: "A", text: "infinite resistance in parallel" }, { id: "B", text: "zero resistance in series with the branch" }, { id: "C", text: "a capacitor" }, { id: "D", text: "an open circuit" }],
    "B", "Ideal voltmeter: infinite $R$, in parallel.",
    { A: "Voltmeter.", C: "Wrong element.", D: "Would always read zero." }, { pool: "retrieval" }),
  easy("u11-j-1", "u11-node", 11, "11.5", "11.5.A",
    "3.0 A and 1.0 A enter a junction; 2.5 A leaves on one branch. The other outgoing current is",
    [{ id: "A", text: "1.5 A" }, { id: "B", text: "6.5 A" }, { id: "C", text: "0.5 A" }, { id: "D", text: "undetermined" }],
    "A", "4.0 A in, 2.5 A out already, 1.5 A out the other branch.",
    { B: "Added everything.", C: "Wrong subtraction.", D: "Junction accounting is enough here." }),
  easy("u11-j-r", "u11-neg-branch", 11, "11.5", "11.5.A",
    "If a solved branch current is negative, you should",
    [{ id: "A", text: "discard the solution" }, { id: "B", text: "reverse the assumed arrow and keep the magnitude" }, { id: "C", text: "set that current to zero" }, { id: "D", text: "reverse the physical battery immediately" }],
    "B", "The sign is relative to the assumed direction.",
    { A: "Negative is allowed.", C: "Unjustified.", D: "Not automatically a hardware fault." }, { pool: "retrieval" }),
  easy("u11-l-1", "u11-two-emf", 11, "11.6", "11.6.A",
    "12 V and 4 V batteries oppose through 8 Ω (ideal). $|I|$ is",
    [{ id: "A", text: "2.0 A" }, { id: "B", text: "1.0 A" }, { id: "C", text: "1.5 A" }, { id: "D", text: "0" }],
    "B", "Net emf 8 V / 8 Ω = 1 A.",
    { A: "Added emfs as if they aided.", C: "Used 12/8.", D: "They do not cancel unless equal." }),
  easy("u11-l-2", "u11-walk-R", 11, "11.6", "11.6.A",
    "Walking around a loop in the assumed current direction, a resistor contributes",
    [{ id: "A", text: "$+IR$" }, { id: "B", text: "$-IR$" }, { id: "C", text: "$+I/R$" }, { id: "D", text: "0 always" }],
    "B", "Potential drop in the direction of assumed current.",
    { A: "Opposite convention.", C: "Not Ohm’s law.", D: "Only if $I=0$." }),
  easy("u11-l-r", "u11-C-dc", 11, "11.6", "11.6.A",
    "In DC steady state, a capacitor in a branch behaves as",
    [{ id: "A", text: "a short" }, { id: "B", text: "an open" }, { id: "C", text: "$R=1\\,\\Omega$" }, { id: "D", text: "an inductor" }],
    "B", "$I=0$ through the capacitor. Dual: inductor is a short in DC steady state.",
    { A: "$t=0^+$ uncharged capacitor.", C: "Fabricated.", D: "Wrong element." }, { pool: "retrieval" }),
  easy("u11-n-1", "u11-network-I", 11, "11.7", "11.7.A",
    "4 Ω || 4 Ω, then in series with 2 Ω, on 12 V. Current through the 2 Ω is",
    [{ id: "A", text: "2.0 A" }, { id: "B", text: "3.0 A" }, { id: "C", text: "1.5 A" }, { id: "D", text: "6.0 A" }],
    "B", "Parallel pair is 2 Ω; $R_{\\mathrm{eq}}=4\\,\\Omega$; $I=3.0\\,\\mathrm{A}$.",
    { A: "Treated 4 Ω as series with 2 Ω only.", C: "Current in each 4 Ω.", D: "Ignored the pair." }),
  easy("u11-n-2", "u11-V-split", 11, "11.7", "11.7.A",
    "In that same network, voltage across the parallel pair is",
    [{ id: "A", text: "12 V" }, { id: "B", text: "6.0 V" }, { id: "C", text: "3.0 V" }, { id: "D", text: "8.0 V" }],
    "B", "$I=3.0\\,\\mathrm{A}$ through the 2 Ω equivalent pair: $V=6.0\\,\\mathrm{V}$. The series 2 Ω also has 6.0 V.",
    { A: "Whole battery.", C: "Maybe used 1 Ω.", D: "Unrelated split." }),
  easy("u11-n-r", "u11-cannot-reduce", 11, "11.7", "11.7.A",
    "A Wheatstone bridge that is not balanced",
    [{ id: "A", text: "always reduces by series–parallel alone" }, { id: "B", text: "generally needs loop/junction equations (or a Δ–Y step)" }, { id: "C", text: "has zero current in every branch" }, { id: "D", text: "violates Kirchhoff’s rules" }],
    "B", "If a resistor is not purely series or parallel, do not force a reduction.",
    { A: "Only if balanced (bridge current 0) or special values.", C: "False.", D: "The rules still hold." }, { pool: "retrieval" }),
  easy("u11-rc-1", "u11-t0", 11, "11.8", "11.8.A",
    "Just after charging begins on an uncharged $C$, the capacitor behaves as",
    [{ id: "A", text: "an open, $I=0$" }, { id: "B", text: "a short, $I=\\mathcal{E}/R$" }, { id: "C", text: "a battery $\\mathcal{E}$" }, { id: "D", text: "infinite $R$" }],
    "B", "$V_C(0^+)=0$. Long after, it is an open.",
    { A: "Long-time behaviour.", C: "Final $V_C$, not $t=0^+$.", D: "Finite $R$ is the series resistor." }),
  easy("u11-rc-2", "u11-Q-tau", 11, "11.8", "11.8.A",
    "Charging from zero, $Q(\\tau)$ is about",
    [{ id: "A", text: "$0.37 Q_\\infty$" }, { id: "B", text: "$0.63 Q_\\infty$" }, { id: "C", text: "$0.50 Q_\\infty$" }, { id: "D", text: "$Q_\\infty$" }],
    "B", "$1-e^{-1}\\approx 0.63$. Half is $\\tau\\ln 2$, a different marker. Current at $\\tau$ is $0.37 I(0)$.",
    { A: "That is $I(\\tau)/I(0)$ or remaining charge on discharge.", C: "Half-life confusion.", D: "Only as $t\\to\\infty$." }),
  easy("u11-rc-r", "u11-tau-RC", 11, "11.8", "11.8.A",
    "$R=4.0\\,\\mathrm{k}\\Omega$, $C=2.5\\,\\mu\\mathrm{F}$. $\\tau$ is",
    [{ id: "A", text: "$10\\,\\mathrm{ms}$" }, { id: "B", text: "$1.0\\,\\mathrm{ms}$" }, { id: "C", text: "$10\\,\\mathrm{s}$" }, { id: "D", text: "$6.3\\,\\mathrm{ms}$" }],
    "A", "$RC=(4000)(2.5\\times 10^{-6})=0.010\\,\\mathrm{s}$.",
    { B: "Off by 10.", C: "Forgot micro.", D: "Mixed in $\\ln 2$ or $2\\pi$." }, { pool: "retrieval" }),
  easy("u12-fq-1", "u12-radius", 12, "12.1", "12.1.A",
    "A proton with $v\\perp B$ moves in a circle of radius",
    [{ id: "A", text: "$mv/(qB)$" }, { id: "B", text: "$qB/(mv)$" }, { id: "C", text: "$mvB/q$" }, { id: "D", text: "$qE$" }],
    "A", "From $qvB=mv^2/r$. Magnetic force does not change speed.",
    { B: "Inverted.", C: "Missing a division by $B$ structure.", D: "Electric force." }),
  easy("u12-fq-2", "u12-electron-F", 12, "12.1", "12.1.A",
    "Electron with $\\vec{v}$ to the right, $\\vec{B}$ out of the page. $\\vec{F}$ is",
    [{ id: "A", text: "up the page" }, { id: "B", text: "down the page" }, { id: "C", text: "out of the page" }, { id: "D", text: "along $\\vec{v}$" }],
    "A", "$\\vec{v}\\times\\vec{B}$ is down for a positive charge; the electron reverses it to up.",
    { B: "Proton / $\\vec{v}\\times\\vec{B}$ without the sign of $q$.", C: "F is perpendicular to B.", D: "F is perpendicular to v." }, { sciencePractice: 1 }),
  easy("u12-fq-r", "u12-work", 12, "12.1", "12.1.A",
    "A purely magnetic force on a charge",
    [{ id: "A", text: "can change speed" }, { id: "B", text: "does no work and cannot change speed" }, { id: "C", text: "is always zero" }, { id: "D", text: "points along $\\vec{v}$" }],
    "B", "$\\vec{F}\\perp\\vec{v}$. It can change direction.",
    { A: "That would require a component along v.", C: "Only if v is parallel to B or v=0.", D: "Perpendicular." }, { pool: "retrieval" }),
  easy("u12-fi-1", "u12-ILB", 12, "12.2", "12.2.A",
    "$I=4.0\\,\\mathrm{A}$, $L=0.15\\,\\mathrm{m}$, $B=0.50\\,\\mathrm{T}$ perpendicular. $F$ is",
    [{ id: "A", text: "0.30 N" }, { id: "B", text: "0.075 N" }, { id: "C", text: "8.0 N" }, { id: "D", text: "0" }],
    "A", "$F=ILB=0.30\\,\\mathrm{N}$.",
    { B: "Forgot $I$ or $L$.", C: "Multiplied wrongly.", D: "Perpendicular, so $\\sin 90^\\circ=1$." }),
  easy("u12-fi-r", "u12-parallel-wires", 12, "12.2", "12.2.A",
    "Two long parallel wires with current in the same direction",
    [{ id: "A", text: "attract" }, { id: "B", text: "repel" }, { id: "C", text: "feel no force" }, { id: "D", text: "produce $E$ only" }],
    "A", "Each sits in the other’s $B$; $I\\,d\\ell\\times B$ is inward.",
    { B: "Opposite currents repel.", C: "There is a force.", D: "This is magnetostatics." }, { pool: "retrieval" }),
  easy("u12-bs-1", "u12-wire-B", 12, "12.3", "12.3.A",
    "Long wire, $I=5.0\\,\\mathrm{A}$, $r=2.5\\,\\mathrm{cm}$. $B$ is closest to",
    [{ id: "A", text: "$4.0\\times 10^{-5}\\,\\mathrm{T}$" }, { id: "B", text: "$1.0\\times 10^{-4}\\,\\mathrm{T}$" }, { id: "C", text: "$\\mu_0 I /(2R)$ with $R=2.5\\,\\mathrm{cm}$" }, { id: "D", text: "0" }],
    "A", "$B=\\mu_0 I/(2\\pi r)=4.0\\times 10^{-5}\\,\\mathrm{T}$.",
    { B: "Forgot $2\\pi$ versus 2, roughly.", C: "Loop-centre formula.", D: "Current produces B." }),
  easy("u12-bs-r", "u12-loop-centre", 12, "12.3", "12.3.A",
    "At the centre of a single circular loop, $B=$",
    [{ id: "A", text: "$\\mu_0 I/(2R)$" }, { id: "B", text: "$\\mu_0 I/(2\\pi R)$" }, { id: "C", text: "0" }, { id: "D", text: "$\\mu_0 n I$" }],
    "A", "All $dB$ add along the axis. Straight-wire uses $2\\pi$. Solenoid uses $n$.",
    { B: "Straight wire.", C: "Cancellation would require a different geometry.", D: "Solenoid interior." }, { pool: "retrieval" }),
  easy("u12-amp-1", "u12-solenoid", 12, "12.4", "12.4.A",
    "Long solenoid, $n=1000\\,\\mathrm{m}^{-1}$, $I=2.0\\,\\mathrm{A}$. Interior $B$ is",
    [{ id: "A", text: "$2.5\\times 10^{-3}\\,\\mathrm{T}$" }, { id: "B", text: "$\\mu_0 I/(2\\pi r)$" }, { id: "C", text: "0" }, { id: "D", text: "$4\\pi\\times 10^{-7}\\,\\mathrm{T}$" }],
    "A", "$B=\\mu_0 n I = 2.5\\times 10^{-3}\\,\\mathrm{T}$.",
    { B: "Wire formula.", C: "Ideal exterior, not interior.", D: "Just $\\mu_0$, missing $nI$." }),
  easy("u12-amp-2", "u12-coax", 12, "12.4", "12.4.A",
    "Outside a coaxial cable with equal-and-opposite return current on the sheath, $B$ is",
    [{ id: "A", text: "$\\mu_0 I/(2\\pi r)$" }, { id: "B", text: "0" }, { id: "C", text: "$\\mu_0 n I$" }, { id: "D", text: "infinite" }],
    "B", "Net $I_{\\mathrm{enc}}=0$ for a circle outside.",
    { A: "That is between core and sheath.", C: "Solenoid.", D: "Finite current, finite $B$ where nonzero." }),
  easy("u12-amp-r", "u12-useful-path", 12, "12.4", "12.4.A",
    "Ampère’s law is useful for finding $B$ when",
    [{ id: "A", text: "you can choose a path where $B$ is constant and tangent (or zero) by symmetry" }, { id: "B", text: "always, for any loop, $B$ factors out" }, { id: "C", text: "never; only Biot–Savart works" }, { id: "D", text: "the current is zero" }],
    "A", "The law is always true; usefulness needs symmetry, as with Gauss’s law.",
    { B: "The integral equals $\\mu_0 I_{\\mathrm{enc}}$, not $|B|$ times length without justification.", C: "Both tools exist.", D: "Then $B$ might still exist from other currents." }, { pool: "retrieval", sciencePractice: 3 }),
  easy("u13-flux-1", "u13-BA-cos", 13, "13.1", "13.1.A",
    "$B=0.20\\,\\mathrm{T}$, $A=0.050\\,\\mathrm{m}^2$, $\\theta=60^\\circ$ to the normal. $\\Phi_B$ is",
    [{ id: "A", text: "$0.010\\,\\mathrm{Wb}$" }, { id: "B", text: "$0.0050\\,\\mathrm{Wb}$" }, { id: "C", text: "$0.0087\\,\\mathrm{Wb}$" }, { id: "D", text: "0" }],
    "B", "$BA\\cos 60^\\circ=0.010\\times 0.50=0.0050\\,\\mathrm{Wb}$.",
    { A: "Forgot cosine.", C: "Used $\\sin 60^\\circ$ or $\\cos 30^\\circ$.", D: "Not perpendicular to B in the $\\theta=90^\\circ$ sense." }),
  easy("u13-flux-r", "u13-translate", 13, "13.1", "13.1.A",
    "Translating a loop in a truly uniform $B$ without rotating",
    [{ id: "A", text: "changes $\\Phi$ and induces emf" }, { id: "B", text: "does not change $\\Phi$" }, { id: "C", text: "always produces motional $B\\ell v$ around the whole loop net" }, { id: "D", text: "makes $\\Phi$ infinite" }],
    "B", "$B$, $A$, and $\\theta$ are unchanged. Emf needs $d\\Phi/dt$.",
    { A: "Uniform field, fixed orientation.", C: "Net emf around a closed loop in uniform B with pure translation is zero.", D: "Nonsense." }, { pool: "retrieval" }),
  easy("u13-far-1", "u13-N-dPhi", 13, "13.2", "13.2.A",
    "$\\Phi_B=0.012 t$ (SI) through each of 5 turns. $|\\mathcal{E}|$ is",
    [{ id: "A", text: "0.012 V" }, { id: "B", text: "0.060 V" }, { id: "C", text: "0" }, { id: "D", text: "0.012 t V" }],
    "B", "$N|d\\Phi/dt|=5\\times 0.012=0.060\\,\\mathrm{V}$. Linear flux is constant emf, not zero.",
    { A: "Forgot $N$.", C: "“Steady flux” confusion — slope is not zero.", D: "Did not differentiate." }),
  easy("u13-far-2", "u13-Blv", 13, "13.2", "13.2.A",
    "Sliding bar: $B=0.40\\,\\mathrm{T}$, $\\ell=0.25\\,\\mathrm{m}$, $v=2.0\\,\\mathrm{m/s}$ perpendicular. $\\mathcal{E}$ is",
    [{ id: "A", text: "0.20 V" }, { id: "B", text: "0.080 V" }, { id: "C", text: "2.0 V" }, { id: "D", text: "0" }],
    "A", "$B\\ell v=0.20\\,\\mathrm{V}$.",
    { B: "Forgot $v$ or $\\ell$.", C: "Quoted $v$.", D: "Area is changing: $dA/dt=\\ell v$." }),
  easy("u13-far-r", "u13-const-Phi", 13, "13.2", "13.2.A",
    "If $\\Phi_B$ through a coil is constant but nonzero,",
    [{ id: "A", text: "emf is $N\\Phi$" }, { id: "B", text: "emf is 0" }, { id: "C", text: "current must be infinite" }, { id: "D", text: "Faraday’s law fails" }],
    "B", "Emf is the derivative, not the value, of flux.",
    { A: "Confuses flux with emf.", C: "No.", D: "The law gives zero emf, correctly." }, { pool: "retrieval" }),
  easy("u13-lenz-1", "u13-increasing-out", 13, "13.3", "13.3.A",
    "A loop faces increasing $B$ out of the page. Induced current (same view) is",
    [{ id: "A", text: "clockwise" }, { id: "B", text: "counterclockwise" }, { id: "C", text: "zero because the loop is at rest" }, { id: "D", text: "out of the page" }],
    "A", "Oppose the increase: induced $B$ into the page → clockwise.",
    { B: "Would add to the increase.", C: "$B$ can change in time.", D: "Current is around the loop." }),
  easy("u13-lenz-2", "u13-power-bar", 13, "13.3", "13.3.A",
    "A sliding bar at constant $v$ on rails dissipates $I^2 R$. The agent pulling the bar does work at a rate",
    [{ id: "A", text: "0, because magnetic forces do no work" }, { id: "B", text: "$Fv=I^2 R$" }, { id: "C", text: "$I^2 R/2$" }, { id: "D", text: "negative of $I^2 R$" }],
    "B", "Magnetic force on the bar opposes $v$; the agent balances it. Energy accounting closes with joule heat.",
    { A: "The magnetic force on the bar is opposite $v$; the agent does the work. (Charges in the bar have $F_B$ perpendicular to their drift along the bar.)", C: "No factor of 1/2.", D: "Wrong sign for the agent." }),
  easy("u13-lenz-r", "u13-decreasing-B", 13, "13.3", "13.3.A",
    "If $B$ out of the page through a loop is decreasing, the induced current tries to",
    [{ id: "A", text: "make $B$ into the page" }, { id: "B", text: "maintain out-of-page $B$" }, { id: "C", text: "stop time" }, { id: "D", text: "set $B=0$ instantly" }],
    "B", "Oppose the change, not the field. Decreasing out-of-page → induced $B$ out of the page (counterclockwise if out is toward you).",
    { A: "That would oppose $B$ rather than $dB/dt$.", C: "Poetic, not physics.", D: "The induced current fights the change, not the existence of B." }, { pool: "retrieval", sciencePractice: 3 }),
  easy("u13-ind-1", "u13-L-emf", 13, "13.4", "13.4.A",
    "An inductor with constant current has induced emf",
    [{ id: "A", text: "$LI$" }, { id: "B", text: "0" }, { id: "C", text: "$\\tfrac12 LI^2$ volts" }, { id: "D", text: "infinite" }],
    "B", "$\\mathcal{E}=-L dI/dt$. Energy $\\tfrac12 LI^2$ can still be stored.",
    { A: "Not the emf formula.", C: "That is energy, not emf.", D: "Only if you try to jump $I$ in zero time." }),
  easy("u13-ind-r", "u13-U-L", 13, "13.4", "13.4.A",
    "Magnetic energy stored in an inductor is",
    [{ id: "A", text: "$\\tfrac12 CV^2$" }, { id: "B", text: "$\\tfrac12 LI^2$" }, { id: "C", text: "$LI$" }, { id: "D", text: "$Q^2/(2C)$" }],
    "B", "Capacitor analogues are the other pair.",
    { A: "Capacitor.", C: "Wrong dimensions for energy.", D: "Capacitor." }, { pool: "retrieval" }),
  easy("u13-rl-1", "u13-L-open", 13, "13.5", "13.5.A",
    "Just after connecting a battery to series RL with $I(0)=0$, the inductor behaves as",
    [{ id: "A", text: "a short, $I=\\mathcal{E}/R$" }, { id: "B", text: "an open, $I=0^+$" }, { id: "C", text: "a capacitor" }, { id: "D", text: "a resistor of value $L$" }],
    "B", "Current cannot jump. Dual of the uncharged capacitor (which is a short at $t=0^+$).",
    { A: "Long-time inductor.", C: "Wrong element.", D: "$L$ is not a resistance." }),
  easy("u13-rl-2", "u13-tau-L", 13, "13.5", "13.5.A",
    "$L=0.40\\,\\mathrm{H}$, $R=20\\,\\Omega$. $\\tau$ is",
    [{ id: "A", text: "8.0 s" }, { id: "B", text: "0.020 s" }, { id: "C", text: "0.40 s" }, { id: "D", text: "$RC$" }],
    "B", "$\\tau=L/R=0.020\\,\\mathrm{s}$.",
    { A: "Used $R/L$ inverted with a slip, or $LR$.", C: "Quoted $L$ as if seconds.", D: "Wrong circuit." }),
  easy("u13-rl-r", "u13-I-inf", 13, "13.5", "13.5.A",
    "Long after an RL circuit is connected to $\\mathcal{E}$, $I\\to$",
    [{ id: "A", text: "0" }, { id: "B", text: "$\\mathcal{E}/R$" }, { id: "C", text: "$\\mathcal{E}/L$" }, { id: "D", text: "infinity" }],
    "B", "$dI/dt=0$, inductor is a wire. Capacitor long-time current is 0 — do not mix.",
    { A: "RC long-time current.", C: "Wrong units.", D: "Finite $R$." }, { pool: "retrieval" }),
  easy("u13-lc-1", "u13-quarter", 13, "13.6", "13.6.A",
    "Ideal LC starting at $Q=Q_m$, $I=0$. First maximum $|I|$ is at",
    [{ id: "A", text: "$t=0$" }, { id: "B", text: "$t=T/4$" }, { id: "C", text: "$t=T/2$" }, { id: "D", text: "never" }],
    "B", "All magnetic energy a quarter period later. $T/2$ is $Q=-Q_m$, $I=0$ again.",
    { A: "All electric then.", C: "Charge reversed, current zero.", D: "Oscillation begins." }),
  easy("u13-lc-r", "u13-omega", 13, "13.6", "13.6.A",
    "$C=4.0\\,\\mu\\mathrm{F}$, $L=0.25\\,\\mathrm{H}$. $\\omega$ is",
    [{ id: "A", text: "$1000\\,\\mathrm{rad/s}$" }, { id: "B", text: "$1.0\\,\\mathrm{rad/s}$" }, { id: "C", text: "$\\sqrt{LC}$" }, { id: "D", text: "$1/(RC)$" }],
    "A", "$\\omega=1/\\sqrt{LC}=1/\\sqrt{1.0\\times 10^{-6}}=10^3\\,\\mathrm{rad/s}$.",
    { B: "Forgot the microfarad.", C: "Missing the reciprocal.", D: "RC circuit." }, { pool: "retrieval" }),
];
