import type { McqItem } from "@/lib/types";
import { mcq } from "./build";

export const UNIT8_ITEMS: McqItem[] = [
  mcq({
    id: "u8-flux-1",
    family: "u8-flux-cube",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "none",
    pool: "practice",
    stem: "A closed rectangular box sits in a uniform field $\\vec{E}=E\\hat{z}$. No charge is inside. The net electric flux through the box is",
    choices: [
      { id: "A", text: "$0$, and therefore $E=0$ on every face.", distractorTag: "flux-equals-local-field" },
      { id: "B", text: "$0$. The field on the faces need not be zero." },
      { id: "C", text: "$EA$ through the top face only, so net flux is $EA$." },
      { id: "D", text: "undefined unless the box is a sphere." },
    ],
    correct: "B",
    misconception: "flux-equals-local-field",
    explanation:
      "Gauss: $\\Phi_{\\mathrm{net}}=Q_{\\mathrm{enc}}/\\varepsilon_0=0$. Top face $EA$, bottom face $-EA$ (outward normal down, $\\vec{E}$ up). Walls contribute $0$. The field on the top is still $E$, not zero.",
    distractorRationales: {
      A: "Confuses a vanishing surface integral with a vanishing integrand.",
      C: "Forgets the opposite face, whose outward flux has the opposite sign.",
      D: "Gauss’s law holds for any closed surface. Spheres are convenient, not required.",
    },
  }),
  mcq({
    id: "u8-flux-2",
    family: "u8-flux-outside",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 75,
    prereqSkill: "none",
    pool: "practice",
    stem: "A point charge $+q$ lies outside a closed Gaussian surface $S$. Which statement must be true?",
    choices: [
      { id: "A", text: "$\\vec{E}=0$ at every point of $S$ because $Q_{\\mathrm{enc}}=0$." },
      { id: "B", text: "Net flux through $S$ is zero. $|\\vec{E}|$ on $S$ is generally not uniform." },
      { id: "C", text: "Net flux through $S$ equals $q/\\varepsilon_0$ because the charge is “near” $S$." },
      { id: "D", text: "Flux is zero only if $S$ is far from $q$." },
    ],
    correct: "B",
    misconception: "flux-equals-local-field",
    explanation:
      "Only enclosed charge appears in Gauss’s law. $q$ is outside, so $\\Phi_{\\mathrm{net}}=0$. The field on $S$ is the Coulomb field of $q$, stronger on the near side. Distance does not restore a fake enclosed charge.",
    distractorRationales: {
      A: "Again treats net flux as a local $E=0$ verdict.",
      C: "Proximity is not enclosure.",
      D: "The law does not have a “far enough” clause for net flux when $Q_{\\mathrm{enc}}=0$.",
    },
  }),
  mcq({
    id: "u8-flux-r",
    family: "u8-flux-retrieve",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 1,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "none",
    pool: "retrieval",
    stem: "When may you replace $\\oint\\vec{E}\\cdot d\\vec{A}$ with $E A$ on a Gaussian surface?",
    choices: [
      { id: "A", text: "Whenever the surface is closed." },
      {
        id: "B",
        text: "When symmetry makes $|E|$ constant on the surface and $\\vec{E}$ perpendicular to it.",
      },
      { id: "C", text: "Whenever $Q_{\\mathrm{enc}}=0$." },
      { id: "D", text: "Only for cubes, never for cylinders." },
    ],
    correct: "B",
    explanation:
      "Pulling $E$ out is a symmetry claim about the integrand, not a prize for drawing a closed shape. Zero enclosed charge makes net flux zero; it does not by itself make $E$ constant.",
    distractorRationales: {
      A: "Closed is required for Gauss’s law, not for $EA$.",
      C: "Zero flux is not constant $E$.",
      D: "Cylinders and planes are the usual friends of $EA$, when the distribution has that symmetry.",
    },
  }),
  mcq({
    id: "u8-line-1",
    family: "u8-line-bisector",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 80,
    prereqSkill: "none",
    pool: "practice",
    stem: "A finite rod, length $L$, uniform $\\lambda$, is centred on the origin. Point $P$ is on the perpendicular bisector at distance $a$. Which expression is $|\\vec{E}|$ at $P$?",
    choices: [
      { id: "A", text: "$k(\\lambda L)/a^2$" },
      { id: "B", text: "$k\\lambda L /\\bigl(a\\sqrt{(L/2)^2+a^2}\\bigr)$" },
      { id: "C", text: "$2k\\lambda/a$" },
      { id: "D", text: "$k\\lambda L / a^2\\sqrt{(L/2)^2+a^2}$" },
    ],
    correct: "B",
    explanation:
      "Integrate $dE_\\perp=k\\lambda a(x^2+a^2)^{-3/2}\\,dx$ from $-L/2$ to $L/2$. The antiderivative yields $k\\lambda L /\\bigl(a\\sqrt{(L/2)^2+a^2}\\bigr)$. A is the lumped-point overestimate. C is the infinite-line limit. D drops a factor of $a$ in the algebra.",
    distractorRationales: {
      A: "Point-charge lump at the centre. Ends are farther than $a$.",
      C: "Infinite-line formula. This rod ends.",
      D: "Algebra slip in the denominator.",
    },
  }),
  mcq({
    id: "u8-line-2",
    family: "u8-line-limit",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "none",
    pool: "practice",
    stem: "For a finite rod on its perpendicular bisector, as $L\\to\\infty$ with $\\lambda$ and $a$ fixed, $|\\vec{E}|$ approaches",
    choices: [
      { id: "A", text: "$0$, because the ends recede." },
      { id: "B", text: "$k(\\lambda L)/a^2$, which diverges." },
      { id: "C", text: "$2k\\lambda/a$" },
      { id: "D", text: "$k\\lambda/a^2$" },
    ],
    correct: "C",
    explanation:
      "$E=k\\lambda L /\\bigl(a\\sqrt{(L/2)^2+a^2}\\bigr)\\to k\\lambda L /(a\\cdot L/2)=2k\\lambda/a$. The infinite-line result is a limit of the finite-rod integral, not a separate religion. $L$ in the point-charge estimate is not a free “make it infinite” knob without changing $r$.",
    distractorRationales: {
      A: "More charge arrives from far away at a shallow angle; the limit is finite and nonzero.",
      B: "You cannot send $L\\to\\infty$ inside $kQ/a^2$ while keeping $a$ as the only distance.",
      D: "Missing the factor of $2$ and the wrong power of $a$.",
    },
  }),
  mcq({
    id: "u8-line-r",
    family: "u8-line-retrieve",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 1,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "none",
    pool: "retrieval",
    stem: "On the perpendicular bisector of a uniformly charged finite rod, the components of $d\\vec{E}$ parallel to the rod",
    choices: [
      { id: "A", text: "add, doubling the field along the rod." },
      { id: "B", text: "cancel in pairs; only the perpendicular pieces survive." },
      { id: "C", text: "are the only pieces that survive." },
      { id: "D", text: "cannot be defined because $dQ$ is not a point." },
    ],
    correct: "B",
    explanation:
      "Symmetry on the bisector: an element at $+x$ and its partner at $-x$ have opposite parallel components and equal perpendicular components. $dQ=\\lambda\\,dx$ is treated as a Coulomb point element — that is the continuous-source model.",
    distractorRationales: {
      A: "Wrong direction of the pairing.",
      C: "Those are the pieces that cancel.",
      D: "The whole method is superposition of pointlike $dQ$.",
    },
  }),
];
