import type { McqItem } from "@/lib/types";
import { mcq } from "./build";

export const UNIT8_ITEMS: McqItem[] = [
  mcq({
    id: "u8-coul-1",
    family: "u8-three-line",
    unit: 8,
    topic: "8.1",
    objective: "8.1.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 90,
    prereqSkill: "bridge-vectors",
    pool: "practice",
    stem: "Charges $+4.0\\,\\mathrm{nC}$, $-2.0\\,\\mathrm{nC}$, and $+4.0\\,\\mathrm{nC}$ sit at $x=0$, $0.10\\,\\mathrm{m}$, and $0.30\\,\\mathrm{m}$. The net force on the middle charge is",
    choices: [
      { id: "A", text: "zero, because the outer charges are equal" },
      { id: "B", text: "to the left (toward $x=0$)" },
      { id: "C", text: "to the right (toward $x=0.30\\,\\mathrm{m}$)" },
      { id: "D", text: "undefined; Coulomb’s law is only for two charges" },
    ],
    correct: "B",
    explanation:
      "The middle charge is negative. It is attracted to both positives. Distance to the left charge is 0.10 m; to the right, 0.20 m. The left attraction is four times the right one ($1/r^2$ and equal $|q_{\\mathrm{outer}}|$), so the net force is toward $x=0$. Superposition applies to three charges.",
    distractorRationales: {
      A: "Equal outer charges do not cancel when distances differ.",
      C: "The nearer +4 nC wins; attraction is toward the left.",
      D: "Forces add as vectors; the law is pairwise.",
    },
  }),
  mcq({
    id: "u8-coul-2",
    family: "u8-coulomb-mag",
    unit: 8,
    topic: "8.1",
    objective: "8.1.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 75,
    prereqSkill: "bridge-units",
    pool: "practice",
    stem: "The magnitude of the force between $+3.0\\,\\mu\\mathrm{C}$ and $-3.0\\,\\mu\\mathrm{C}$ separated by 0.30 m in vacuum is closest to",
    choices: [
      { id: "A", text: "$9.0\\times 10^{-3}\\,\\mathrm{N}$" },
      { id: "B", text: "$0.90\\,\\mathrm{N}$" },
      { id: "C", text: "$9.0\\,\\mathrm{N}$" },
      { id: "D", text: "$90\\,\\mathrm{N}$" },
    ],
    correct: "B",
    explanation: "$F=k|q_1 q_2|/r^2=(8.99\\times 10^9)(3\\times 10^{-6})^2/(0.30)^2 \\approx 0.90\\,\\mathrm{N}$. Attraction, but the question asked magnitude.",
    distractorRationales: {
      A: "Dropped a factor of $10^2$ from $(10^{-6})^2$ versus $r^2$.",
      C: "Forgot to square 0.30, or used $r=0.10\\,\\mathrm{m}$.",
      D: "Used $k=9\\times 10^{10}$ or $r=0.10\\,\\mathrm{m}$ without squaring correctly.",
    },
  }),
  mcq({
    id: "u8-coul-r",
    family: "u8-midpoint-signs",
    unit: 8,
    topic: "8.1",
    objective: "8.1.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "u8-coulomb-vectors",
    pool: "retrieval",
    stem: "Charges $+2q$ at $x=0$ and $-q$ at $x=a$. A charge $+Q$ at $x=a/2$ feels a net force",
    choices: [
      { id: "A", text: "zero" },
      { id: "B", text: "to the left" },
      { id: "C", text: "to the right" },
      { id: "D", text: "that cannot be found without $Q$’s mass" },
    ],
    correct: "C",
    explanation:
      "$+2q$ repels $+Q$ to the right. $-q$ attracts $+Q$ to the right. Both contributions are to the right. Force does not require mass.",
    distractorRationales: {
      A: "Cancellation would need opposing directions.",
      B: "Both pairwise forces on $+Q$ point right.",
      D: "Newton’s second law needs mass for acceleration, not for force.",
    },
  }),
  mcq({
    id: "u8-neut-1",
    family: "u8-induction-ground",
    unit: 8,
    topic: "8.1",
    objective: "8.1.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "u8-neutral-vs-uncharged",
    pool: "practice",
    stem: "A negative rod is held near an isolated neutral conducting sphere. After a momentary ground on the far side, the ground is removed and then the rod is removed. The sphere is",
    choices: [
      { id: "A", text: "net negative" },
      { id: "B", text: "net positive" },
      { id: "C", text: "neutral, because the rod never touched it" },
      { id: "D", text: "neutral, because grounding always removes all charge" },
    ],
    correct: "B",
    explanation: "The rod repels electrons to the far side; grounding lets those electrons leave. After isolation and rod removal, the sphere is net positive.",
    distractorRationales: {
      A: "That would match charging by contact with the negative rod, or a reversed grounding story.",
      C: "Touch is not required; charge flowed through the ground lead.",
      D: "Grounding equalises potential with Earth; it does not magically empty every conductor in every geometry.",
    },
  }),
  mcq({
    id: "u8-neut-2",
    family: "u8-paper-attraction",
    unit: 8,
    topic: "8.1",
    objective: "8.1.B",
    sciencePractice: 3,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-neutral-vs-uncharged",
    pool: "practice",
    stem: "A charged comb attracts bits of uncharged paper. The best explanation is",
    choices: [
      { id: "A", text: "the paper must have been net charged already" },
      { id: "B", text: "polarisation in a nonuniform field produces a net attraction" },
      { id: "C", text: "gravity is reduced near charge" },
      { id: "D", text: "uncharged objects cannot feel electric forces" },
    ],
    correct: "B",
    explanation: "Neutral matter still contains charge. Induced dipoles in a nonuniform field are attracted toward stronger $|E|$.",
    distractorRationales: {
      A: "Not necessary; the paper can start neutral.",
      C: "Gravity is not how this demonstration works.",
      D: "That is the misconception this item targets.",
    },
  }),
  mcq({
    id: "u8-neut-r",
    family: "u8-isolated-sphere-rod",
    unit: 8,
    topic: "8.1",
    objective: "8.1.B",
    sciencePractice: 3,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-neutral-vs-uncharged",
    pool: "retrieval",
    stem: "A charged rod is held near an ungrounded neutral metal sphere and then taken away, never touching. The sphere’s final net charge is",
    choices: [
      { id: "A", text: "the same sign as the rod" },
      { id: "B", text: "opposite the rod" },
      { id: "C", text: "zero" },
      { id: "D", text: "infinite" },
    ],
    correct: "C",
    explanation: "Without a path to Earth, charge is rearranged while the rod is near and returns to uniform (net zero) after the rod leaves.",
    distractorRationales: {
      A: "Contact charging, not this process.",
      B: "That is the grounded-induction result.",
      D: "Charge is finite and conserved.",
    },
  }),
  mcq({
    id: "u8-xfer-1",
    family: "u8-share-spheres",
    unit: 8,
    topic: "8.2",
    objective: "8.2.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "u8-charge-transfer",
    pool: "practice",
    stem: "Identical isolated conducting spheres carry $+9.0\\,\\mu\\mathrm{C}$ and $-3.0\\,\\mu\\mathrm{C}$. They touch and separate. Each then has",
    choices: [
      { id: "A", text: "$+9.0$ and $-3.0\\,\\mu\\mathrm{C}$ still" },
      { id: "B", text: "$+3.0\\,\\mu\\mathrm{C}$ each" },
      { id: "C", text: "$+6.0\\,\\mu\\mathrm{C}$ each" },
      { id: "D", text: "$0$ and $+6.0\\,\\mu\\mathrm{C}$" },
    ],
    correct: "B",
    explanation: "Total $+6.0\\,\\mu\\mathrm{C}$ is conserved and shared equally: $+3.0\\,\\mu\\mathrm{C}$ each.",
    distractorRationales: {
      A: "Charge is conserved for the pair, not for each sphere during contact.",
      C: "Used the first charge only, or averaged magnitudes without the signed sum.",
      D: "Treats cancellation as happening on one sphere only.",
    },
  }),
  mcq({
    id: "u8-xfer-r",
    family: "u8-share-caps",
    unit: 8,
    topic: "8.2",
    objective: "8.2.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "u8-charge-transfer",
    pool: "retrieval",
    stem: "Isolated capacitors $C$ and $3C$ carry $+8.0\\,\\mu\\mathrm{C}$ and $0$. After they are connected in parallel, the charge on $C$ is",
    choices: [
      { id: "A", text: "$4.0\\,\\mu\\mathrm{C}$" },
      { id: "B", text: "$2.0\\,\\mu\\mathrm{C}$" },
      { id: "C", text: "$8.0\\,\\mu\\mathrm{C}$" },
      { id: "D", text: "$6.0\\,\\mu\\mathrm{C}$" },
    ],
    correct: "B",
    explanation: "Common $V$, $Q\\propto C$. $C$ takes $1/4$ of 8.0 μC = 2.0 μC; $3C$ takes 6.0 μC.",
    distractorRationales: {
      A: "Equal sharing, as if the capacitors were identical.",
      C: "No charge moved.",
      D: "That is the charge on $3C$, not on $C$.",
    },
  }),
  mcq({
    id: "u8-field-1",
    family: "u8-F-from-E",
    unit: 8,
    topic: "8.3",
    objective: "8.3.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-field-model",
    pool: "practice",
    stem: "$\\vec{E}= (400\\,\\mathrm{N/C})\\,\\hat{\\imath}$. The force on $q=-2.5\\,\\mathrm{nC}$ is",
    choices: [
      { id: "A", text: "$1.0\\times 10^{-6}\\,\\mathrm{N}$ in $+x$" },
      { id: "B", text: "$1.0\\times 10^{-6}\\,\\mathrm{N}$ in $-x$" },
      { id: "C", text: "$400\\,\\mathrm{N}$ in $-x$" },
      { id: "D", text: "zero because field lines are not real" },
    ],
    correct: "B",
    explanation: "$F=|q|E=(2.5\\times 10^{-9})(400)=1.0\\times 10^{-6}\\,\\mathrm{N}$, opposite $\\vec{E}$ because $q\u003c0$.",
    distractorRationales: {
      A: "Forgot to reverse for negative charge.",
      C: "Used $E$ as if it were already the force.",
      D: "Field lines are a drawing; $\\vec{E}$ still determines $\\vec{F}=q\\vec{E}$.",
    },
  }),
  mcq({
    id: "u8-field-r",
    family: "u8-test-charge-sign",
    unit: 8,
    topic: "8.3",
    objective: "8.3.A",
    sciencePractice: 1,
    difficulty: 2,
    expectedSeconds: 45,
    prereqSkill: "u8-field-model",
    pool: "retrieval",
    stem: "Replacing a test charge $+q_0$ by $-q_0$ at the same point",
    choices: [
      { id: "A", text: "reverses $\\vec{E}$" },
      { id: "B", text: "reverses $\\vec{F}$ but not $\\vec{E}$" },
      { id: "C", text: "leaves both $\\vec{F}$ and $\\vec{E}$ unchanged" },
      { id: "D", text: "makes $\\vec{E}$ undefined" },
    ],
    correct: "B",
    explanation: "$\\vec{E}$ is a property of the sources. $\\vec{F}=q\\vec{E}$ flips with $q$.",
    distractorRationales: {
      A: "Confuses force with field.",
      C: "Force must flip.",
      D: "The small-test-charge definition still applies.",
    },
  }),
  mcq({
    id: "u8-sup-1",
    family: "u8-equal-charges-mid",
    unit: 8,
    topic: "8.3",
    objective: "8.3.B",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-superposition",
    pool: "practice",
    stem: "Equal charges $+q$ at $x=\\pm a$. The electric field at the origin is",
    choices: [
      { id: "A", text: "zero" },
      { id: "B", text: "to $+x$, twice one contribution" },
      { id: "C", text: "to $-x$" },
      { id: "D", text: "$kq/a^2$ in an indeterminate direction" },
    ],
    correct: "A",
    explanation: "Each field at the origin points away from its source: opposite directions, equal magnitude.",
    distractorRationales: {
      B: "True for a dipole’s field on the + charge side, not the midpoint of two positives.",
      C: "No preferred left.",
      D: "The vector sum is determined and is zero.",
    },
  }),
  mcq({
    id: "u8-sup-2",
    family: "u8-dipole-perp",
    unit: 8,
    topic: "8.3",
    objective: "8.3.B",
    sciencePractice: 1,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "u8-superposition",
    pool: "practice",
    stem: "A dipole $\\pm q$ lies on the x-axis. At a point on the perpendicular bisector, the net $\\vec{E}$ is",
    choices: [
      { id: "A", text: "zero" },
      { id: "B", text: "parallel to the dipole moment $\\vec{p}$" },
      { id: "C", text: "antiparallel to $\\vec{p}$" },
      { id: "D", text: "along $+y$ regardless of which charge is on the right" },
    ],
    correct: "C",
    explanation: "The two fields have equal magnitude. Components along the bisector add in the direction from $+$ toward the side of $-$, i.e. opposite $\\vec{p}$ (which points from $-$ to $+$).",
    distractorRationales: {
      A: "$V$ may be zero there; $E$ is not.",
      B: "That is the on-axis result, not the bisector.",
      D: "The direction tracks which side is negative.",
    },
  }),
  mcq({
    id: "u8-sup-r",
    family: "u8-zero-field-location",
    unit: 8,
    topic: "8.3",
    objective: "8.3.B",
    sciencePractice: 2,
    difficulty: 4,
    expectedSeconds: 80,
    prereqSkill: "u8-superposition",
    pool: "retrieval",
    stem: "Charges $+4q$ at $x=0$ and $-q$ at $x=d$. A point of $E=0$ on the x-axis (not on a charge) lies",
    choices: [
      { id: "A", text: "between them" },
      { id: "B", text: "to the left of $+4q$" },
      { id: "C", text: "to the right of $-q$" },
      { id: "D", text: "nowhere; opposite signs never cancel" },
    ],
    correct: "C",
    explanation:
      "Between them the two fields point the same way (right). Left of $+4q$, the nearer larger charge wins. Right of $-q$, you can sit closer to the smaller charge so the fields oppose and can cancel.",
    distractorRationales: {
      A: "Both fields point toward $-q$ / away from $+4q$ — same direction between.",
      B: "The $+4q$ is closer and larger; they do not cancel there.",
      D: "Opposite signs can cancel off to the side of the smaller charge.",
    },
  }),
  mcq({
    id: "u8-line-1",
    family: "u8-infinite-line",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "u8-continuous-line",
    pool: "practice",
    stem: "An infinite line has $\\lambda = 2.0\\,\\mu\\mathrm{C/m}$. $E$ at $r=0.10\\,\\mathrm{m}$ is closest to",
    choices: [
      { id: "A", text: "$3.6\\times 10^5\\,\\mathrm{N/C}$" },
      { id: "B", text: "$1.8\\times 10^5\\,\\mathrm{N/C}$" },
      { id: "C", text: "$1.8\\times 10^4\\,\\mathrm{N/C}$" },
      { id: "D", text: "$k\\lambda / r^2$" },
    ],
    correct: "A",
    explanation: "$E=\\lambda/(2\\pi\\varepsilon_0 r)=2k\\lambda/r=(2\\times 8.99\\times 10^9)(2.0\\times 10^{-6})/0.10 \\approx 3.6\\times 10^5\\,\\mathrm{N/C}$.",
    distractorRationales: {
      B: "Used $k\\lambda/r$ without the 2, or doubled $r$.",
      C: "Off by $10$ from $r$ in centimetres mixed with metres.",
      D: "Point-charge formula; wrong radial dependence.",
    },
  }),
  mcq({
    id: "u8-line-2",
    family: "u8-line-scaling",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 45,
    prereqSkill: "u8-continuous-line",
    pool: "practice",
    stem: "If the perpendicular distance from an infinite line charge doubles, $E$ is multiplied by",
    choices: [
      { id: "A", text: "1/4" },
      { id: "B", text: "1/2" },
      { id: "C", text: "2" },
      { id: "D", text: "unchanged, like a sheet" },
    ],
    correct: "B",
    explanation: "Infinite line: $E\\propto 1/r$. Doubling $r$ halves $E$. Sheets are $r$-independent; points are $1/r^2$.",
    distractorRationales: {
      A: "Point-charge scaling.",
      C: "Inverted the proportion.",
      D: "Infinite nonconducting sheet, not a line.",
    },
  }),
  mcq({
    id: "u8-line-r",
    family: "u8-finite-vs-point",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "u8-continuous-line",
    pool: "retrieval",
    stem: "A finite rod of length $L$ and charge $Q$ produces, on its perpendicular bisector at distance $d\\ll L$, a field that is closest to",
    choices: [
      { id: "A", text: "the infinite-line result using $\\lambda=Q/L$" },
      { id: "B", text: "$kQ/d^2$" },
      { id: "C", text: "zero by symmetry" },
      { id: "D", text: "the infinite-sheet result" },
    ],
    correct: "A",
    explanation: "Near a long rod ($d\\ll L$) the ends are a small correction; the infinite-line model is the useful limit. Far away ($d\\gg L$) the point-charge form wins.",
    distractorRationales: {
      B: "Valid when $d\\gg L$, the opposite limit.",
      C: "Symmetry cancels the parallel component, not the perpendicular field.",
      D: "A rod is not a plane.",
    },
  }),
  mcq({
    id: "u8-ring-1",
    family: "u8-ring-centre",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 3,
    difficulty: 2,
    expectedSeconds: 45,
    prereqSkill: "u8-ring-and-disk",
    pool: "practice",
    stem: "At the centre of a uniformly charged ring of charge $Q\\neq 0$",
    choices: [
      { id: "A", text: "$E=0$ and $V=0$" },
      { id: "B", text: "$E=0$ and $V=kQ/R$ (if $V(\\infty)=0$)" },
      { id: "C", text: "$E=kQ/R^2$" },
      { id: "D", text: "$E$ is maximum" },
    ],
    correct: "B",
    explanation: "Pairwise cancellation of $\\vec{E}$. Every $dq$ is at distance $R$, so $V=kQ/R$.",
    distractorRationales: {
      A: "$V$ is not zero relative to infinity.",
      C: "That ignores cancellation; it is not a point charge at the centre.",
      D: "$E=0$ at the centre; the on-axis maximum is at $|z|=R/\\sqrt{2}$.",
    },
  }),
  mcq({
    id: "u8-ring-r",
    family: "u8-disk-sheet-limit",
    unit: 8,
    topic: "8.4",
    objective: "8.4.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 55,
    prereqSkill: "u8-ring-and-disk",
    pool: "retrieval",
    stem: "The on-axis field of a uniformly charged disk approaches, as radius $\\to\\infty$,",
    choices: [
      { id: "A", text: "$\\sigma/(2\\varepsilon_0)$" },
      { id: "B", text: "$\\sigma/\\varepsilon_0$" },
      { id: "C", text: "$kQ/z^2$" },
      { id: "D", text: "0" },
    ],
    correct: "A",
    explanation: "Infinite nonconducting sheet. The conducting-plane value is twice as large. Far from a finite disk you recover a point charge, the opposite limit.",
    distractorRationales: {
      B: "Conducting plane (or the region between opposite sheets).",
      C: "Large-$z$ finite-disk limit, not large-radius.",
      D: "The sheet field is finite and nonzero.",
    },
  }),
  mcq({
    id: "u8-flux-1",
    family: "u8-cube-uniform",
    unit: 8,
    topic: "8.5",
    objective: "8.5.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-flux-definition",
    pool: "practice",
    stem: "A cube of side $a$ sits in uniform $\\vec{E}=E\\hat{\\imath}$. Net flux through the closed cube is",
    choices: [
      { id: "A", text: "$6Ea^2$" },
      { id: "B", text: "$Ea^2$" },
      { id: "C", text: "0" },
      { id: "D", text: "$Ea^3$" },
    ],
    correct: "C",
    explanation: "Inward flux on one face cancels outward flux on the opposite face. $Q_{\\mathrm{enc}}=0$ agrees.",
    distractorRationales: {
      A: "Added unsigned face fluxes.",
      B: "That is the flux through one perpendicular face, not the closed surface.",
      D: "Volume has the wrong meaning here; flux is not $E$ times volume.",
    },
  }),
  mcq({
    id: "u8-flux-2",
    family: "u8-tilted-area",
    unit: 8,
    topic: "8.5",
    objective: "8.5.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 55,
    prereqSkill: "u8-flux-definition",
    pool: "practice",
    stem: "Uniform $E=250\\,\\mathrm{N/C}$ along $+z$. A $0.080\\,\\mathrm{m}^2$ flat surface has its normal at $60^\\circ$ to $+z$. Flux through the open surface is",
    choices: [
      { id: "A", text: "$20\\,\\mathrm{N\\cdot m}^2/\\mathrm{C}$" },
      { id: "B", text: "$10\\,\\mathrm{N\\cdot m}^2/\\mathrm{C}$" },
      { id: "C", text: "$17\\,\\mathrm{N\\cdot m}^2/\\mathrm{C}$" },
      { id: "D", text: "0, because the surface is not closed" },
    ],
    correct: "B",
    explanation: "$\\Phi=EA\\cos 60^\\circ=(250)(0.080)(0.50)=10$. Open surfaces can have flux; Gauss’s law uses closed surfaces.",
    distractorRationales: {
      A: "Forgot $\\cos 60^\\circ=1/2$.",
      C: "Used $\\sin 60^\\circ$ or $\\cos 30^\\circ$.",
      D: "Flux is defined for open surfaces; net flux in Gauss’s law needs a closed surface.",
    },
  }),
  mcq({
    id: "u8-flux-r",
    family: "u8-parallel-surface",
    unit: 8,
    topic: "8.5",
    objective: "8.5.A",
    sciencePractice: 3,
    difficulty: 2,
    expectedSeconds: 40,
    prereqSkill: "u8-flux-definition",
    pool: "retrieval",
    stem: "A flat surface is parallel to a uniform $\\vec{E}$. The flux through it is",
    choices: [
      { id: "A", text: "EA" },
      { id: "B", text: "0" },
      { id: "C", text: "E/A" },
      { id: "D", text: "impossible to define" },
    ],
    correct: "B",
    explanation: "$\\theta=90^\\circ$ between $\\vec{E}$ and the normal, so $\\cos\\theta=0$. $E$ itself is not zero.",
    distractorRationales: {
      A: "That requires $\\vec{E}$ perpendicular to the surface.",
      C: "Wrong dimensions.",
      D: "The integral is defined and happens to be zero.",
    },
  }),
  mcq({
    id: "u8-mis-1",
    family: "u8-external-charge-flux",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "u8-flux-misconception",
    pool: "practice",
    stem: "A point charge $+Q$ lies outside a closed Gaussian surface $S$. Which is correct?",
    choices: [
      { id: "A", text: "Net flux through $S$ is $Q/\\varepsilon_0$" },
      { id: "B", text: "Net flux is 0, but $E$ on $S$ is generally not 0" },
      { id: "C", text: "$E=0$ everywhere on $S$" },
      { id: "D", text: "Gauss’s law does not apply unless $Q$ is at the centre" },
    ],
    correct: "B",
    misconception: "flux-equals-local-field",
    explanation: "$Q_{\\mathrm{enc}}=0$ so net flux is 0. Field lines still pierce $S$; they enter and leave. Gauss’s law always applies; usefulness is a separate question.",
    distractorRationales: {
      A: "That would require $Q$ inside.",
      C: "The local field of an external charge is not zero on $S$.",
      D: "The law is general; centering is for pulling $|E|$ out of the integral.",
    },
  }),
  mcq({
    id: "u8-mis-2",
    family: "u8-uniform-field-sphere",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 55,
    prereqSkill: "u8-flux-misconception",
    pool: "practice",
    stem: "A spherical Gaussian surface is placed in a uniform electric field in empty space. Net flux is zero. A student concludes $E=0$ on the sphere. The error is",
    choices: [
      { id: "A", text: "Gauss’s law is false in uniform fields" },
      { id: "B", text: "treating $\\oint \\vec{E}\\cdot d\\vec{A}=0$ as if $\\vec{E}=0$" },
      { id: "C", text: "the sphere has the wrong radius" },
      { id: "D", text: "uniform fields have no Gaussian surfaces" },
    ],
    correct: "B",
    misconception: "flux-equals-local-field",
    explanation: "The integral vanishes by cancellation (or $Q_{\\mathrm{enc}}=0$). $E$ is the given uniform field, not zero. The sphere is legal but not useful for finding $E$.",
    distractorRationales: {
      A: "The law holds; this configuration is a standard illustration of it.",
      C: "Radius does not create a field that wasn’t there.",
      D: "Any closed surface is allowed in the statement of the law.",
    },
  }),
  mcq({
    id: "u8-mis-3",
    family: "u8-pillbox-external",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 55,
    prereqSkill: "u8-flux-misconception",
    pool: "practice",
    stem: "A Gaussian cylinder is drawn around empty space next to an infinite line charge (the line is outside the cylinder). Net flux through the cylinder is",
    choices: [
      { id: "A", text: "$\\lambda L/\\varepsilon_0$" },
      { id: "B", text: "0" },
      { id: "C", text: "equal to $E$ times the curved area" },
      { id: "D", text: "undefined because the line is infinite" },
    ],
    correct: "B",
    explanation: "The line is not enclosed, so $Q_{\\mathrm{enc}}=0$ and net flux is 0 even though $E$ is nonzero on the cylinder.",
    distractorRationales: {
      A: "That is the flux if the line were the axis of the cylinder.",
      C: "You cannot factor $E$ out; it varies, and the net integral is still 0.",
      D: "The infinite-line model is an idealisation, but flux through a finite cylinder is defined.",
    },
  }),
  mcq({
    id: "u8-mis-r",
    family: "u8-off-centre-charge",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    sciencePractice: 3,
    difficulty: 4,
    expectedSeconds: 70,
    prereqSkill: "u8-flux-misconception",
    pool: "retrieval",
    stem: "A charge $+Q$ is inside a spherical Gaussian surface but not at the centre. Which is true?",
    choices: [
      { id: "A", text: "Net flux is $Q/\\varepsilon_0$, but $|E|$ is not constant on the sphere" },
      { id: "B", text: "$E=kQ/R^2$ at every point on the sphere" },
      { id: "C", text: "Net flux is less than $Q/\\varepsilon_0$ because the charge is off-centre" },
      { id: "D", text: "Gauss’s law requires the charge to be centred" },
    ],
    correct: "A",
    explanation: "Flux depends only on enclosed charge. $|E|$ is larger on the near side. You cannot solve for a single $E$.",
    distractorRationales: {
      B: "That requires spherical symmetry of the charge about the centre.",
      C: "Flux is independent of position inside, as long as the charge is enclosed.",
      D: "The law is true; the useful-symmetry condition is extra.",
    },
  }),
  mcq({
    id: "u8-gsph-1",
    family: "u8-insulator-inside",
    unit: 8,
    topic: "8.6",
    objective: "8.6.A",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 70,
    prereqSkill: "u8-gauss-sphere",
    pool: "practice",
    stem: "A uniform insulating sphere has total $Q$ and radius $R$. At $r=R/2$, $E$ is",
    choices: [
      { id: "A", text: "$kQ/r^2$ using the full $Q$ at this $r$" },
      { id: "B", text: "$kQ/(2R^2)$" },
      { id: "C", text: "$kQ/R^2$ (the surface value)" },
      { id: "D", text: "0" },
    ],
    correct: "B",
    explanation:
      "$Q_{\\mathrm{enc}}=(r^3/R^3)Q=Q/8$. Then $E=k Q_{\\mathrm{enc}}/r^2 = k(Q/8)/(R/2)^2 = kQ/(2R^2)$. Equivalently $E=kQr/R^3$ at $r=R/2$.",
    distractorRationales: {
      A: "Uses all of $Q$ as if you were outside, or as if the interior were empty of charge beyond $r$.",
      C: "That is $E(R)$, not $E(R/2)$. Inside, $E$ is smaller than the surface value for a uniform ball.",
      D: "Zero field inside is the conducting-sphere result, not a uniform insulator.",
    },
  }),
  mcq({
    id: "u8-gsph-2",
    family: "u8-shell-inside",
    unit: 8,
    topic: "8.6",
    objective: "8.6.A",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 45,
    prereqSkill: "u8-gauss-sphere",
    pool: "practice",
    stem: "A thin spherical shell of radius $R$ carries $Q$. For $r\u003cR$, $E$ is",
    choices: [
      { id: "A", text: "$kQ/r^2$" },
      { id: "B", text: "$kQ/R^2$" },
      { id: "C", text: "0" },
      { id: "D", text: "$kQr/R^3$" },
    ],
    correct: "C",
    explanation: "Spherical symmetry and $Q_{\\mathrm{enc}}=0$ for $r\u003cR$ imply $E=0$ inside an empty shell (or a conductor’s cavity with no charge in it).",
    distractorRationales: {
      A: "Exterior formula used inside.",
      B: "Surface value used inside.",
      D: "Uniform-ball interior formula; the shell’s charge is not distributed through the volume $r\u003cR$.",
    },
  }),
  mcq({
    id: "u8-gsph-r",
    family: "u8-cavity-charge",
    unit: 8,
    topic: "8.6",
    objective: "8.6.A",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 65,
    prereqSkill: "u8-gauss-sphere",
    pool: "retrieval",
    stem: "A conducting spherical shell has net charge $+Q$. A point charge $+q$ sits in the empty cavity. The charge on the outer surface is",
    choices: [
      { id: "A", text: "$+Q$" },
      { id: "B", text: "$+Q+q$" },
      { id: "C", text: "$+Q-q$" },
      { id: "D", text: "0" },
    ],
    correct: "B",
    explanation: "A Gaussian surface in the metal has $E=0$, so $Q_{\\mathrm{enc}}=0=q+Q_{\\mathrm{inner}}$, hence $Q_{\\mathrm{inner}}=-q$. Net on the shell is $Q$, so outer = $Q-(-q)=Q+q$.",
    distractorRationales: {
      A: "Ignores the induced inner-surface charge.",
      C: "Wrong sign on the induced charge.",
      D: "The shell’s net charge was given as $+Q$, not zero.",
    },
  }),
  mcq({
    id: "u8-gcyl-1",
    family: "u8-sheet-noncond",
    unit: 8,
    topic: "8.6",
    objective: "8.6.B",
    sciencePractice: 2,
    difficulty: 2,
    expectedSeconds: 50,
    prereqSkill: "u8-gauss-cylinder-plane",
    pool: "practice",
    stem: "An infinite nonconducting sheet has uniform $\\sigma$. $E$ a distance $x$ away is",
    choices: [
      { id: "A", text: "$\\sigma/(2\\varepsilon_0)$, independent of $x$" },
      { id: "B", text: "$\\sigma/\\varepsilon_0$" },
      { id: "C", text: "$\\sigma/(2\\varepsilon_0 x)$" },
      { id: "D", text: "$k\\sigma/x^2$" },
    ],
    correct: "A",
    explanation: "Gaussian pillbox, flux from two faces: $2EA=\\sigma A/\\varepsilon_0$. Independent of $x$ in the infinite idealisation.",
    distractorRationales: {
      B: "Conducting plane (or the field between opposite sheets of $\\pm\\sigma$).",
      C: "Invented a $1/x$ that belongs to a line.",
      D: "Point-charge thinking.",
    },
  }),
  mcq({
    id: "u8-gcyl-2",
    family: "u8-two-sheets",
    unit: 8,
    topic: "8.6",
    objective: "8.6.B",
    sciencePractice: 2,
    difficulty: 3,
    expectedSeconds: 60,
    prereqSkill: "u8-gauss-cylinder-plane",
    pool: "practice",
    stem: "Two infinite nonconducting sheets carry $\\sigma$ and $-\\sigma$. The field between them has magnitude",
    choices: [
      { id: "A", text: "0" },
      { id: "B", text: "$\\sigma/(2\\varepsilon_0)$" },
      { id: "C", text: "$\\sigma/\\varepsilon_0$" },
      { id: "D", text: "$2\\sigma/\\varepsilon_0$" },
    ],
    correct: "C",
    explanation: "Each sheet contributes $\\sigma/(2\\varepsilon_0)$. Between, they add; outside, they cancel. This matches the ideal parallel-plate capacitor.",
    distractorRationales: {
      A: "That is the exterior.",
      B: "Forgot superposition of the second sheet.",
      D: "Treated each sheet as a conductor ($\\sigma/\\varepsilon_0$) and added.",
    },
  }),
  mcq({
    id: "u8-gcyl-r",
    family: "u8-wrong-surface",
    unit: 8,
    topic: "8.6",
    objective: "8.6.B",
    sciencePractice: 3,
    difficulty: 3,
    expectedSeconds: 55,
    prereqSkill: "u8-gauss-cylinder-plane",
    pool: "retrieval",
    stem: "To find $E$ of an infinite line, a spherical Gaussian surface centred on a point of the line is",
    choices: [
      { id: "A", text: "useful, because Gauss’s law always yields a unique $E$" },
      { id: "B", text: "legal but not useful: $|E|$ is not constant on the sphere" },
      { id: "C", text: "required; cylinders are only for finite rods" },
      { id: "D", text: "invalid because Gauss’s law fails for infinite objects" },
    ],
    correct: "B",
    explanation: "The law holds. Symmetry of the line is cylindrical, not spherical, so you cannot factor $E$ out of the sphere integral.",
    distractorRationales: {
      A: "Usefulness requires matching symmetry.",
      C: "A coaxial cylinder is the useful choice for the infinite line.",
      D: "The infinite line is an idealisation for which the law still holds.",
    },
  }),
];
