import type { Objective, Topic, UnitId } from "@/lib/types";

export interface UnitMeta {
  id: UnitId;
  official: string;
  title: string;
  mcqWeight: string;
  summary: string;
}

export const UNITS: UnitMeta[] = [
  {
    id: "bridge",
    official: "Bridge",
    title: "Prerequisite repair",
    mcqWeight: "not examined as a unit",
    summary:
      "Vectors, graphs, derivatives, integrals, separable DEs, and mechanics ideas that E&M will use. Weak calculus opens these alongside physics, not instead of it.",
  },
  {
    id: 8,
    official: "Unit 8",
    title: "Electric charges, fields, and Gauss’s law",
    mcqWeight: "15–25%",
    summary:
      "Charge as a conserved source; the field as a vector model; superposition and integration; flux and symmetry-based Gauss’s law.",
  },
  {
    id: 9,
    official: "Unit 9",
    title: "Electric potential",
    mcqWeight: "10–20%",
    summary:
      "Potential energy of charge systems, potential difference, and the field–potential relationship, including reference choice.",
  },
  {
    id: 10,
    official: "Unit 10",
    title: "Conductors and capacitors",
    mcqWeight: "10–15%",
    summary:
      "Equilibrium in conductors, capacitance from geometry, stored energy, and dielectrics with the battery connected or not.",
  },
  {
    id: 11,
    official: "Unit 11",
    title: "Electric circuits",
    mcqWeight: "15–25%",
    summary:
      "Current, resistance, energy transfer, networks with Kirchhoff’s rules, and RC transients.",
  },
  {
    id: 12,
    official: "Unit 12",
    title: "Magnetic fields and electromagnetism",
    mcqWeight: "10–20%",
    summary:
      "Magnetic force on charges and currents; fields from currents via Biot–Savart and Ampère’s law.",
  },
  {
    id: 13,
    official: "Unit 13",
    title: "Electromagnetic induction",
    mcqWeight: "10–20%",
    summary:
      "Changing flux, induced emf and current, inductance, RL transients, and LC energy exchange.",
  },
];

export const TOPICS: Topic[] = [
  {
    id: "B.1",
    unit: "bridge",
    title: "Vectors and coordinates",
    emphasis: "Choose axes, resolve components, add vectors, and state a sign convention.",
    evidenceOfUnderstanding: "Student chooses coordinates, sets a positive direction, and explains a sign.",
    lessonIds: ["bridge-vectors"],
    objectiveIds: ["B.1.A"],
  },
  {
    id: "B.2",
    unit: "bridge",
    title: "Algebra for physics",
    emphasis: "Rearrange literal equations and keep symbols until substitution.",
    evidenceOfUnderstanding: "Student isolates a requested quantity and checks dimensions.",
    lessonIds: ["bridge-algebra"],
    objectiveIds: ["B.2.A"],
  },
  {
    id: "B.3",
    unit: "bridge",
    title: "Graph slopes and areas",
    emphasis: "Slope as a derivative; area as an accumulation.",
    evidenceOfUnderstanding: "Student reads a slope and an area with units.",
    lessonIds: ["bridge-graphs"],
    objectiveIds: ["B.3.A"],
  },
  {
    id: "B.4",
    unit: "bridge",
    title: "Derivatives in physics",
    emphasis: "Rate of change of a physical quantity.",
    evidenceOfUnderstanding: "Student writes dQ/dt and interprets the sign.",
    lessonIds: ["bridge-derivatives"],
    objectiveIds: ["B.4.A"],
  },
  {
    id: "B.5",
    unit: "bridge",
    title: "Definite integrals",
    emphasis: "Set bounds from a physical story; integrate a source element.",
    evidenceOfUnderstanding: "Student sets bounds, checks dimensions, and explains a sign.",
    lessonIds: ["bridge-integrals"],
    objectiveIds: ["B.5.A"],
  },
  {
    id: "B.6",
    unit: "bridge",
    title: "Exponential functions",
    emphasis: "e^{−t/τ} as a solution, not a memorised shape.",
    evidenceOfUnderstanding: "Student identifies τ from a governing equation.",
    lessonIds: ["bridge-exponentials"],
    objectiveIds: ["B.6.A"],
  },
  {
    id: "B.7",
    unit: "bridge",
    title: "Separable differential equations",
    emphasis: "Separate, integrate, apply an initial condition.",
    evidenceOfUnderstanding: "Student produces Q(t) from dQ/dt = −Q/τ.",
    lessonIds: ["bridge-de"],
    objectiveIds: ["B.7.A"],
  },
  {
    id: "B.8",
    unit: "bridge",
    title: "Mechanics energy",
    emphasis: "Work and potential energy as a template for electrostatics.",
    evidenceOfUnderstanding: "Student accounts for energy transfers with a stated reference.",
    lessonIds: ["bridge-energy"],
    objectiveIds: ["B.8.A"],
  },
  {
    id: "B.9",
    unit: "bridge",
    title: "Force and Newton’s laws",
    emphasis: "Net force, free-body diagrams, and when a charge is in equilibrium.",
    evidenceOfUnderstanding: "Student draws forces and writes ∑F = 0 or ma.",
    lessonIds: ["bridge-force"],
    objectiveIds: ["B.9.A"],
  },
  {
    id: "B.10",
    unit: "bridge",
    title: "Dimensions and units",
    emphasis: "SI base and derived units used in E&M.",
    evidenceOfUnderstanding: "Student rejects an equation that fails a unit check.",
    lessonIds: ["bridge-units"],
    objectiveIds: ["B.10.A"],
  },
  {
    id: "B.11",
    unit: "bridge",
    title: "Sign conventions",
    emphasis: "Current direction, loop direction, flux orientation.",
    evidenceOfUnderstanding: "Student interprets a negative solved quantity.",
    lessonIds: ["bridge-signs"],
    objectiveIds: ["B.11.A"],
  },
  {
    id: "B.12",
    unit: "bridge",
    title: "Limiting cases",
    emphasis: "Check r → ∞, t → 0, t → ∞, κ → 1.",
    evidenceOfUnderstanding: "Student names a limit and what physical quantity it constrains.",
    lessonIds: ["bridge-limits"],
    objectiveIds: ["B.12.A"],
  },
  {
    id: "8.1",
    unit: 8,
    title: "Electric charge and electric force",
    emphasis: "Interactions of charges; Coulomb’s law as a vector equation.",
    evidenceOfUnderstanding: "Distinguishes a neutral object from an object with no constituent charges.",
    lessonIds: ["u8-coulomb-vectors", "u8-neutral-vs-uncharged"],
    objectiveIds: ["8.1.A", "8.1.B"],
  },
  {
    id: "8.2",
    unit: 8,
    title: "Charge accounting and transfer",
    emphasis: "Conservation during conduction, induction, and polarisation.",
    evidenceOfUnderstanding: "Tracks charge so the algebraic sum is invariant.",
    lessonIds: ["u8-charge-transfer"],
    objectiveIds: ["8.2.A"],
  },
  {
    id: "8.3",
    unit: 8,
    title: "Electric field models",
    emphasis: "Field as force per unit charge; superposition of discrete sources.",
    evidenceOfUnderstanding: "Constructs E at a point from more than one source and states the test-charge idealisation.",
    lessonIds: ["u8-field-model", "u8-superposition"],
    objectiveIds: ["8.3.A", "8.3.B"],
  },
  {
    id: "8.4",
    unit: 8,
    title: "Continuous sources and integration",
    emphasis: "Source element dQ; integrate the required vector component.",
    evidenceOfUnderstanding: "Constructs a source element and integrates the required vector component.",
    lessonIds: ["u8-continuous-line", "u8-ring-and-disk"],
    objectiveIds: ["8.4.A"],
  },
  {
    id: "8.5",
    unit: 8,
    title: "Electric flux",
    emphasis: "Φ_E = ∫ E · dA; net flux versus local field.",
    evidenceOfUnderstanding: "Explains why zero net flux does not establish a zero field everywhere.",
    lessonIds: ["u8-flux-definition", "u8-flux-misconception"],
    objectiveIds: ["8.5.A", "8.5.B"],
  },
  {
    id: "8.6",
    unit: 8,
    title: "Gauss’s law and symmetry",
    emphasis: "Useful Gaussian surfaces; enclosed charge; symmetry limits.",
    evidenceOfUnderstanding: "Selects a valid surface and states when |E| can leave the integral.",
    lessonIds: ["u8-gauss-sphere", "u8-gauss-cylinder-plane"],
    objectiveIds: ["8.6.A", "8.6.B"],
  },
  {
    id: "9.1",
    unit: 9,
    title: "Electric potential energy",
    emphasis: "Energy of charge systems; path independence for electrostatics.",
    evidenceOfUnderstanding: "Writes ΔU = q ΔV and states the zero of energy.",
    lessonIds: ["u9-potential-energy"],
    objectiveIds: ["9.1.A"],
  },
  {
    id: "9.2",
    unit: 9,
    title: "Electric potential",
    emphasis: "Potential difference; reference choice; superposition of V.",
    evidenceOfUnderstanding: "Distinguishes zero potential from zero field and states the reference.",
    lessonIds: ["u9-potential", "u9-zero-v-vs-zero-e"],
    objectiveIds: ["9.2.A", "9.2.B"],
  },
  {
    id: "9.3",
    unit: 9,
    title: "Field–potential relationships",
    emphasis: "E = −∇V; energy conservation for a test charge.",
    evidenceOfUnderstanding: "Obtains E from a V(x) graph and checks the sign.",
    lessonIds: ["u9-e-from-v", "u9-energy-conservation"],
    objectiveIds: ["9.3.A", "9.3.B"],
  },
  {
    id: "10.1",
    unit: 10,
    title: "Equilibrium in conducting material",
    emphasis: "E = 0 in electrostatic equilibrium; excess charge on surfaces.",
    evidenceOfUnderstanding: "Uses E = 0 inside without claiming Q = 0 on the conductor.",
    lessonIds: ["u10-conductor-equilibrium"],
    objectiveIds: ["10.1.A"],
  },
  {
    id: "10.2",
    unit: 10,
    title: "Connected conductors",
    emphasis: "Charge movement until potentials equalise.",
    evidenceOfUnderstanding: "Uses equipotential conditions without assuming equal charge.",
    lessonIds: ["u10-connected-conductors"],
    objectiveIds: ["10.2.A"],
  },
  {
    id: "10.3",
    unit: 10,
    title: "Capacitance and stored energy",
    emphasis: "C from geometry; U = ½ CV² = Q²/(2C); what stays fixed.",
    evidenceOfUnderstanding: "Identifies what stays fixed before choosing an energy expression.",
    lessonIds: ["u10-capacitance", "u10-stored-energy"],
    objectiveIds: ["10.3.A", "10.3.B"],
  },
  {
    id: "10.4",
    unit: 10,
    title: "Dielectrics",
    emphasis: "κ, bound charge, battery connected versus disconnected.",
    evidenceOfUnderstanding: "Tracks the fixed variable and the energy change.",
    lessonIds: ["u10-dielectrics"],
    objectiveIds: ["10.4.A"],
  },
  {
    id: "11.1",
    unit: 11,
    title: "Electric current",
    emphasis: "Charge flow; I = dQ/dt; current density.",
    evidenceOfUnderstanding: "Interprets current direction, including a negative solved current.",
    lessonIds: ["u11-current"],
    objectiveIds: ["11.1.A"],
  },
  {
    id: "11.2",
    unit: 11,
    title: "Resistance and resistivity",
    emphasis: "Material resistance; R = ρL/A; microscopic model.",
    evidenceOfUnderstanding: "Separates geometry from material and temperature.",
    lessonIds: ["u11-resistivity"],
    objectiveIds: ["11.2.A"],
  },
  {
    id: "11.3",
    unit: 11,
    title: "Electrical energy and power",
    emphasis: "Energy transfer rate; P = IV = I²R = V²/R with hypotheses.",
    evidenceOfUnderstanding: "Explains where energy is transferred in a circuit.",
    lessonIds: ["u11-power"],
    objectiveIds: ["11.3.A"],
  },
  {
    id: "11.4",
    unit: 11,
    title: "Circuit models",
    emphasis: "Ideal batteries, resistors, and connecting wires.",
    evidenceOfUnderstanding: "States which idealisations are in play.",
    lessonIds: ["u11-circuit-models"],
    objectiveIds: ["11.4.A"],
  },
  {
    id: "11.5",
    unit: 11,
    title: "Junction equations",
    emphasis: "Charge conservation at a node.",
    evidenceOfUnderstanding: "Writes ∑I_in = ∑I_out with a consistent current map.",
    lessonIds: ["u11-junctions"],
    objectiveIds: ["11.5.A"],
  },
  {
    id: "11.6",
    unit: 11,
    title: "Loop equations",
    emphasis: "Energy accounting around a closed path.",
    evidenceOfUnderstanding: "Writes a consistent sign convention and interprets a negative current.",
    lessonIds: ["u11-loops"],
    objectiveIds: ["11.6.A"],
  },
  {
    id: "11.7",
    unit: 11,
    title: "Multi-loop networks",
    emphasis: "Simultaneous loop and junction equations.",
    evidenceOfUnderstanding: "Reduces a network or solves the system without mixing conventions.",
    lessonIds: ["u11-networks"],
    objectiveIds: ["11.7.A"],
  },
  {
    id: "11.8",
    unit: 11,
    title: "Capacitor transients",
    emphasis: "Governing equation; initial and final behaviour.",
    evidenceOfUnderstanding: "Derives and interprets charging or discharging functions.",
    lessonIds: ["u11-rc-transients"],
    objectiveIds: ["11.8.A"],
  },
  {
    id: "12.1",
    unit: 12,
    title: "Magnetic force on moving charges",
    emphasis: "Direction; negative charges; F = q v × B.",
    evidenceOfUnderstanding: "Handles negative charges and explains force relative to velocity.",
    lessonIds: ["u12-force-on-charges"],
    objectiveIds: ["12.1.A"],
  },
  {
    id: "12.2",
    unit: 12,
    title: "Magnetic force on currents",
    emphasis: "F = I ∫ dℓ × B; torque on a loop.",
    evidenceOfUnderstanding: "Finds direction and magnitude for a straight segment in uniform B.",
    lessonIds: ["u12-force-on-currents"],
    objectiveIds: ["12.2.A"],
  },
  {
    id: "12.3",
    unit: 12,
    title: "Fields from currents",
    emphasis: "Biot–Savart source element; superposition.",
    evidenceOfUnderstanding: "Constructs a dB element and integrates a required component.",
    lessonIds: ["u12-biot-savart"],
    objectiveIds: ["12.3.A"],
  },
  {
    id: "12.4",
    unit: 12,
    title: "Ampère’s law and symmetry",
    emphasis: "Circulation; when |B| leaves the integral.",
    evidenceOfUnderstanding: "Selects a valid Amperian path and justifies simplifications.",
    lessonIds: ["u12-ampere"],
    objectiveIds: ["12.4.A"],
  },
  {
    id: "13.1",
    unit: 13,
    title: "Magnetic flux",
    emphasis: "Φ_B = ∫ B · dA; orientation.",
    evidenceOfUnderstanding: "Separates flux magnitude from flux change.",
    lessonIds: ["u13-magnetic-flux"],
    objectiveIds: ["13.1.A"],
  },
  {
    id: "13.2",
    unit: 13,
    title: "Faraday’s law",
    emphasis: "ε = −dΦ_B/dt; motional emf as a special case.",
    evidenceOfUnderstanding: "Computes emf from a stated flux function.",
    lessonIds: ["u13-faraday"],
    objectiveIds: ["13.2.A"],
  },
  {
    id: "13.3",
    unit: 13,
    title: "Lenz’s law and energy",
    emphasis: "Direction; motion and energy accounting.",
    evidenceOfUnderstanding: "Separates flux, flux change, emf, and induced current, and accounts for energy.",
    lessonIds: ["u13-lenz"],
    objectiveIds: ["13.3.A"],
  },
  {
    id: "13.4",
    unit: 13,
    title: "Inductance and energy storage",
    emphasis: "Self-inductance; U = ½ LI².",
    evidenceOfUnderstanding: "Connects induced emf to dI/dt and stored magnetic energy.",
    lessonIds: ["u13-inductance"],
    objectiveIds: ["13.4.A"],
  },
  {
    id: "13.5",
    unit: 13,
    title: "RL transients",
    emphasis: "Governing equation; initial and final inductor behaviour.",
    evidenceOfUnderstanding: "Writes I(t) with a stated time constant and initial condition.",
    lessonIds: ["u13-rl"],
    objectiveIds: ["13.5.A"],
  },
  {
    id: "13.6",
    unit: 13,
    title: "LC oscillations",
    emphasis: "Energy exchange between C and L; ω = 1/√(LC).",
    evidenceOfUnderstanding: "Connects initial conditions, time dependence, and energy exchange.",
    lessonIds: ["u13-lc"],
    objectiveIds: ["13.6.A"],
  },
];

export const OBJECTIVES: Objective[] = TOPICS.map((t) => ({
  id: t.objectiveIds[0],
  topicId: t.id,
  statement: t.evidenceOfUnderstanding,
  essentialKnowledge: [t.emphasis],
  lessonId: t.lessonIds[0],
  workedExampleId: `${t.lessonIds[0]}-we`,
  independentItemIds: [],
  retrievalItemIds: [],
  representation: t.emphasis,
  reviewOwner: "Anannt physics review",
}));

export function topicsForUnit(unit: UnitId) {
  return TOPICS.filter((t) => t.unit === unit);
}

export function topicById(id: string) {
  return TOPICS.find((t) => t.id === id);
}

export const FRAMEWORK = {
  name: "Model → Represent → Derive → Check → Explain",
  steps: [
    {
      id: "model",
      title: "Model",
      detail: "Name the physical situation, the idealisations, and the quantities that matter.",
    },
    {
      id: "represent",
      title: "Represent",
      detail: "Draw the diagram, choose coordinates, and write the symbols you will use.",
    },
    {
      id: "derive",
      title: "Derive",
      detail: "Select a principle and produce a result from it, keeping the chain of reasoning visible.",
    },
    {
      id: "check",
      title: "Check",
      detail: "Units, signs, limiting cases, and whether the result could be true of the situation.",
    },
    {
      id: "explain",
      title: "Explain",
      detail: "Say what the result means, what it assumed, and why a tempting alternative fails.",
    },
  ],
} as const;

export const SKILL_TRACKS = [
  { id: "physical_modelling", label: "Physical modelling" },
  { id: "mathematical_execution", label: "Mathematical execution" },
  { id: "representations", label: "Representations" },
  { id: "experimental_reasoning", label: "Experimental reasoning" },
  { id: "argumentation", label: "Argumentation" },
  { id: "timed_execution", label: "Timed execution" },
] as const;

export const SCIENCE_PRACTICES = [
  {
    id: 1 as const,
    name: "Creating representations",
    note: "Official AP Physics science practice 1.",
  },
  {
    id: 2 as const,
    name: "Mathematical routines",
    note: "Official AP Physics science practice 2. Distinct from the FRQ category of the same everyday name.",
  },
  {
    id: 3 as const,
    name: "Scientific questioning and argumentation",
    note: "Official AP Physics science practice 3.",
  },
];

export const FRQ_CATEGORY_LABELS: Record<string, string> = {
  mathematical_routines: "Mathematical routines",
  translation_between_representations: "Translation between representations",
  experimental_design: "Experimental design and analysis",
  qualitative_quantitative_translation: "Qualitative/quantitative translation",
};
