import type { FrqTask } from "@/lib/types";

const provenance = {
  author: "Anannt physics author",
  reviewer: "Independent physics reviewer",
  reviewed: "2026-09-10",
  version: "1.0",
};

export const FRQ_TASKS: FrqTask[] = [
  {
    id: "diag-w1",
    family: "diag-written-vector",
    version: "1.0",
    unit: "bridge",
    topic: "B.1",
    objective: "B.1.A",
    category: "mathematical_routines",
    sciencePractice: 2,
    totalPoints: 4,
    expectedMinutes: 8,
    pool: "diagnostic",
    parts: [
      { id: "a", prompt: "A force of 8.0 N acts at 120° from +x. Compute $F_x$ and $F_y$.", points: 2 },
      { id: "b", prompt: "State in one sentence what the sign of $F_x$ means.", points: 2 },
    ],
    modelSolution:
      "(a) $F_x=8\\cos 120^\\circ=-4.0\\,\\mathrm{N}$, $F_y=8\\sin 120^\\circ=4\\sqrt{3}\\,\\mathrm{N}$. (b) The x-contribution points opposite the declared +x axis. Magnitude is still 4.0 N.",
    rubric: [
      { id: "a1", points: 1, earns: "Correct cosine/sine with 120°.", alternate: "Using adjacent/opposite on a sketch with a 60° complement." },
      { id: "a2", points: 1, earns: "Both components with signs.", afterError: "If the angle is taken as 60° from +x, subsequent magnitude may still earn the sign sentence if consistent." },
      { id: "b1", points: 2, earns: "Interprets negative as opposite +x, not as an unphysical force." },
    ],
    selfChecks: [
      "Did I report units?",
      "Did I treat magnitude as positive?",
      "Did I mention the axis I defined?",
    ],
    provenance,
    status: "published",
  },
  {
    id: "diag-w2",
    family: "diag-written-flux",
    version: "1.0",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    category: "qualitative_quantitative_translation",
    sciencePractice: 3,
    totalPoints: 5,
    expectedMinutes: 10,
    pool: "diagnostic",
    stimulus: "A student says: “This Gaussian sphere has no charge inside, so the electric field on it must be zero.”",
    parts: [
      { id: "a", prompt: "Identify the physical error in one sentence.", points: 2 },
      { id: "b", prompt: "Give a counterexample (uniform field or external charge) and state what is actually zero.", points: 3 },
    ],
    modelSolution:
      "(a) The student treats a surface integral as a local field. (b) A cube in a uniform field has $\\Phi_{\\mathrm{net}}=0$ while $|E|$ is the uniform value. What is zero is net flux, $Q_{\\mathrm{enc}}/\\varepsilon_0$, not $E$ on the surface.",
    rubric: [
      { id: "a1", points: 2, earns: "Names integral vs local field, or flux vs E." },
      { id: "b1", points: 2, earns: "A valid counterexample with E not zero." },
      { id: "b2", points: 1, earns: "States that net flux (or Q_enc) is zero." },
    ],
    selfChecks: [
      "Did I avoid saying Gauss’s law is false?",
      "Did I distinguish useful symmetry from the law itself?",
    ],
    provenance,
    status: "published",
  },
  {
    id: "frq-flux-mr",
    family: "frq-gauss-sphere",
    version: "1.0",
    unit: 8,
    topic: "8.6",
    objective: "8.6.A",
    category: "mathematical_routines",
    sciencePractice: 2,
    totalPoints: 10,
    expectedMinutes: 18,
    pool: "practice",
    stimulus:
      "A uniformly charged insulating sphere of radius $R=0.050\\,\\mathrm{m}$ has total charge $Q=4.0\\,\\mathrm{nC}$. Point P is at $r=0.020\\,\\mathrm{m}$ from the centre; point S is at $r=0.080\\,\\mathrm{m}$.",
    parts: [
      { id: "a", prompt: "Using Gauss’s law, derive $E(r)$ for $r<R$. State the Gaussian surface and the symmetry that lets $|E|$ leave the integral.", points: 4 },
      { id: "b", prompt: "Calculate $E$ at P and at S.", points: 3 },
      { id: "c", prompt: "A student uses $E=kQ/r^2$ at P. Explain why that is incorrect, then check that your two formulae agree at $r=R$.", points: 3 },
    ],
    modelSolution:
      "(a) Concentric sphere of radius r. Spherical symmetry: E radial and constant magnitude on the surface. $Q_{\\mathrm{enc}}=(r^3/R^3)Q$, $E 4\\pi r^2 = Q_{\\mathrm{enc}}/\\varepsilon_0$, so $E=kQr/R^3$. (b) $E_P=kQr/R^3=(8.99e9)(4e-9)(0.020)/(0.050)^3=5.8\\times 10^3\\,\\mathrm{N/C}$. $E_S=kQ/r^2=(8.99e9)(4e-9)/(0.080)^2=5.6\\times 10^3\\,\\mathrm{N/C}$. (c) Inside, not all Q is enclosed. At r=R both give $kQ/R^2$.",
    rubric: [
      { id: "a1", points: 1, earns: "Concentric spherical Gaussian surface." },
      { id: "a2", points: 1, earns: "States E constant in magnitude and radial." },
      { id: "a3", points: 1, earns: "Q_enc proportional to r^3." },
      { id: "a4", points: 1, earns: "E = kQr/R^3 or equivalent." },
      { id: "b1", points: 2, earns: "Numeric E at P with units, using interior formula." },
      { id: "b2", points: 1, earns: "Numeric E at S with exterior formula." },
      { id: "c1", points: 2, earns: "Explains full Q is not enclosed." },
      { id: "c2", points: 1, earns: "Matching at r=R." },
    ],
    selfChecks: ["Gaussian surface named", "Only enclosed charge used", "Units N/C", "Limit at R checked"],
    provenance,
    status: "published",
  },
  {
    id: "frq-flux-rep",
    family: "frq-zero-flux",
    version: "1.0",
    unit: 8,
    topic: "8.5",
    objective: "8.5.B",
    category: "translation_between_representations",
    sciencePractice: 1,
    totalPoints: 8,
    expectedMinutes: 15,
    pool: "practice",
    parts: [
      { id: "a", prompt: "Sketch a cube in a uniform field E to the right. Mark flux in and out on the faces with signs using outward normals.", points: 3 },
      { id: "b", prompt: "On the same sketch, indicate that |E| is not zero on the left and right faces.", points: 2 },
      { id: "c", prompt: "Write Gauss’s law for this cube and explain in words why the law does not imply E=0.", points: 3 },
    ],
    modelSolution:
      "(a) Left face Φ=−EA, right +EA, others 0. (b) Equal-length E arrows on left and right. (c) ∮E·dA=0=Q_enc/ε0. The integral vanishes by cancellation, not because the integrand is zero.",
    rubric: [
      { id: "a1", points: 3, earns: "Correct signed fluxes on opposite faces." },
      { id: "b1", points: 2, earns: "Nonzero E indicated on those faces." },
      { id: "c1", points: 3, earns: "Gauss’s law stated and integral vs integrand distinguished." },
    ],
    selfChecks: ["Outward normals", "Opposite signs", "Did not claim Gauss’s law fails"],
    provenance,
    status: "published",
  },
  {
    id: "frq-cap-exp",
    family: "frq-capacitor-lab",
    version: "1.0",
    unit: 10,
    topic: "10.3",
    objective: "10.3.B",
    category: "experimental_design",
    sciencePractice: 3,
    totalPoints: 10,
    expectedMinutes: 18,
    pool: "practice",
    stimulus: "Students may connect a parallel-plate capacitor either to a battery or isolate it after charging. They can vary d and insert a dielectric.",
    parts: [
      { id: "a", prompt: "Describe a procedure to determine whether U increases or decreases when d is increased, stating what must be held fixed and which meters you need.", points: 4 },
      { id: "b", prompt: "Predict the outcome for battery connected and for isolated. Identify the energy source or sink.", points: 4 },
      { id: "c", prompt: "Name one idealisation that would make a real experiment differ from $C=\\varepsilon_0 A/d$.", points: 2 },
    ],
    modelSolution:
      "(a) Two runs: (1) remain connected to a voltmeter/battery, increase d; compute U=½CV² with C from geometry or from Q=CV if a coulombmeter is available. (2) Charge, disconnect, then increase d, using Q fixed. (b) Connected: U decreases, energy returns to the battery. Isolated: U increases, agent does work. (c) Fringing, finite plate size, leakage, imperfect dielectric fill.",
    rubric: [
      { id: "a1", points: 2, earns: "States the Q vs V constraint explicitly." },
      { id: "a2", points: 2, earns: "Mentions measurable quantities (V, Q, or C)." },
      { id: "b1", points: 2, earns: "Correct connected prediction + battery as sink." },
      { id: "b2", points: 2, earns: "Correct isolated prediction + mechanical work." },
      { id: "c1", points: 2, earns: "A real-world idealisation named." },
    ],
    selfChecks: ["Did I freeze the right variable?", "Did I not claim an official AP score from this lab?"],
    provenance,
    status: "published",
  },
  {
    id: "frq-rc-qqt",
    family: "frq-rc-switch",
    version: "1.0",
    unit: 11,
    topic: "11.8",
    objective: "11.8.A",
    category: "qualitative_quantitative_translation",
    sciencePractice: 3,
    totalPoints: 9,
    expectedMinutes: 16,
    pool: "practice",
    stimulus: "$\\mathcal{E}=12\\,\\mathrm{V}$, $R=4.0\\,\\mathrm{k}\\Omega$, $C=2.0\\,\\mu\\mathrm{F}$, initially uncharged. Switch closes at t=0.",
    parts: [
      { id: "a", prompt: "Find I(0⁺), Q(∞), and τ.", points: 3 },
      { id: "b", prompt: "Sketch I(t) and V_C(t) on labelled axes.", points: 3 },
      { id: "c", prompt: "A student says current is ε/R at all times because the battery is constant. Correct the student using the governing equation.", points: 3 },
    ],
    modelSolution:
      "(a) I(0⁺)=3.0 mA, Q∞=24 μC, τ=8.0 ms. (b) I exponential decay; V_C exponential rise to 12 V. (c) ε = IR + Q/C. As Q grows, IR must fall. Current is ε/R only while Q=0.",
    rubric: [
      { id: "a1", points: 1, earns: "I(0⁺)=ε/R with value." },
      { id: "a2", points: 1, earns: "Q∞=Cε." },
      { id: "a3", points: 1, earns: "τ=RC with seconds." },
      { id: "b1", points: 3, earns: "Both sketches with asymptotes and qualitative curvature." },
      { id: "c1", points: 3, earns: "Uses loop equation; does not merely say “exponential.”" },
    ],
    selfChecks: ["t=0 vs t=∞ not swapped", "Units ms not μs by accident"],
    provenance,
    status: "published",
  },
  {
    id: "frq-lenz-mr",
    family: "frq-sliding-bar",
    version: "1.0",
    unit: 13,
    topic: "13.3",
    objective: "13.3.A",
    category: "mathematical_routines",
    sciencePractice: 2,
    totalPoints: 10,
    expectedMinutes: 18,
    pool: "practice",
    stimulus: "A bar of length ℓ=0.20 m slides at v=3.0 m/s on two rails in B=0.50 T into the page. The circuit resistance is R=0.40 Ω. Area in the field is increasing.",
    parts: [
      { id: "a", prompt: "Find emf and current. State the current direction.", points: 4 },
      { id: "b", prompt: "Find the magnetic force on the bar and its direction.", points: 3 },
      { id: "c", prompt: "Show that Fv = I²R. Who supplies that power?", points: 3 },
    ],
    modelSolution:
      "(a) ε=Bℓv=0.30 V, I=0.75 A. Increasing into-page flux → induced B out of page → counterclockwise if the bar is on the right. (b) F=IℓB=0.075 N opposing v (to the left if v is right). (c) Fv=0.225 W; I²R=0.225 W. An external agent pulling at constant speed supplies it.",
    rubric: [
      { id: "a1", points: 2, earns: "ε=Bℓv numeric." },
      { id: "a2", points: 1, earns: "I=ε/R." },
      { id: "a3", points: 1, earns: "Lenz direction consistent with increasing flux." },
      { id: "b1", points: 3, earns: "F=IℓB opposite v." },
      { id: "c1", points: 2, earns: "Numeric equality." },
      { id: "c2", points: 1, earns: "Agent identified." },
    ],
    selfChecks: ["Lenz on the change not the field", "Power signs"],
    provenance,
    status: "published",
  },
];

export function frqById(id: string) {
  return FRQ_TASKS.find((f) => f.id === id);
}

export const PRACTICE_FRQS = FRQ_TASKS.filter((f) => f.pool === "practice");
export const DIAGNOSTIC_FRQS = FRQ_TASKS.filter((f) => f.pool === "diagnostic");
