import type { Lesson } from "@/lib/types";

const review = {
  reviewDate: "2026-09-10",
  authors: [
    { name: "Anannt physics author", role: "author" as const },
    { name: "Independent physics reviewer", role: "reviewer" as const },
  ],
  version: "1.0",
  status: "published" as const,
};

export const BRIDGE_LESSONS: Lesson[] = [
  {
    id: "bridge-vectors",
    slug: "vectors-and-coordinates",
    title: "Vectors, components, and a usable sign convention",
    unit: "bridge",
    topics: ["B.1"],
    objectives: ["B.1.A"],
    capability:
      "Choose a coordinate system, resolve a vector, add two vectors, and explain what a negative component means.",
    prereqs: [],
    minutes: [20, 30],
    ...review,
    prediction: {
      prompt:
        "A displacement is 3.0 m at 30° above the +x-axis. Which statement about the y-component is correct if +y is upward?",
      choices: [
        { id: "A", text: "It is 3.0 m, because the magnitude is 3.0 m." },
        { id: "B", text: "It is 3.0 cos 30° m." },
        { id: "C", text: "It is 3.0 sin 30° m.", correct: true },
        {
          id: "D",
          text: "It is negative, because 30° is measured from +x.",
          misconception: "sign-from-quadrant-guess",
        },
      ],
      explanation:
        "The y-component is the projection onto +y: $3.0\\sin 30^\\circ$ m. The cosine belongs to the adjacent side (x). Nothing about a first-quadrant angle makes y negative.",
    },
    explanation: {
      model:
        "A vector has magnitude and direction. In a plane we represent it by two scalar components along chosen axes. The physics is the arrow; the numbers depend on the axes you declared.",
      represent:
        "Draw the arrow, mark the angle from a stated axis, and write $\\vec{a} = a_x\\,\\hat{\\imath} + a_y\\,\\hat{\\jmath}$. If you later need a different origin or a rotated axis, redraw rather than recycling the old components.",
      derive:
        "If $\\theta$ is measured from +x toward +y, $a_x = a\\cos\\theta$ and $a_y = a\\sin\\theta$. Adding vectors means adding components: $(\\vec{a}+\\vec{b})_x = a_x + b_x$.",
      check:
        "Units of each component match the original quantity. A vector in the second quadrant has $a_x \u003c 0$ and $a_y \u003e 0$. The magnitude $\\sqrt{a_x^2+a_y^2}$ is never negative.",
      explain:
        "A negative component is not \u201ca negative vector.\u201d It means that piece points opposite the axis you defined as positive. Coulomb\u2019s law, $\\vec{E}$, and $\\vec{B}$ will all inherit this convention.",
    },
    workedExample: {
      title: "Two forces on a charge",
      situation:
        "A charge sits at the origin. One force is $4.0\\,\\mathrm{N}$ along $+x$; another is $3.0\\,\\mathrm{N}$ at $90^\\circ$. Find the magnitude and direction of the net force.",
      assumptions: [
        "The two forces are simultaneous and coplanar.",
        "+x and +y are the stated axes; no other forces.",
      ],
      derivation:
        "$F_x = 4.0\\,\\mathrm{N}$, $F_y = 3.0\\,\\mathrm{N}$. $|\\vec{F}| = 5.0\\,\\mathrm{N}$. $\\theta = \\tan^{-1}(3/4)$ above +x.",
      units: "Newtons for force; the angle is dimensionless.",
      interpretation:
        "The net force is not 7 N. Vector addition is not arithmetic addition of magnitudes unless the vectors are parallel.",
      whyAlternativesFail:
        "Adding 4 and 3 as scalars ignores direction. Subtracting them as if they were opposite also invents an alignment that was not given.",
    },
    fadedExample: {
      situation:
        "A 6.0 N electric force points 120° from +x (standard position). Find $F_x$ and $F_y$.",
      steps: [
        {
          prompt: "What is $F_x$?",
          hint: "120° is in the second quadrant; cosine is negative.",
          expected: "$F_x = 6\\cos 120^\\circ = -3.0\\,\\mathrm{N}$.",
        },
        {
          prompt: "What is $F_y$?",
          hint: "Sine of 120° is positive.",
          expected: "$F_y = 6\\sin 120^\\circ = 3\\sqrt{3}\\,\\mathrm{N}$.",
        },
        {
          prompt: "What does the negative $F_x$ mean?",
          hint: "Compare to the +x axis you defined, not to \u201cleft on the page\u201d as a primitive.",
          expected: "The x-contribution points opposite +x.",
        },
      ],
    },
    independentItemIds: ["br-vec-1", "br-vec-2"],
    representationTask: {
      kind: "diagram",
      prompt:
        "Sketch $\\vec{A} = 2\\,\\hat{\\imath} - 3\\,\\hat{\\jmath}$ and $\\vec{B} = -\\hat{\\imath} + 2\\,\\hat{\\jmath}$, then sketch $\\vec{A}+\\vec{B}$. Label components.",
      expected:
        "Resultant is $\\hat{\\imath} - \\hat{\\jmath}$. The sketch should show head-to-tail or parallelogram addition, not two disconnected arrows.",
    },
    retrievalItemId: "br-vec-r",
    videoAlt:
      "A coordinate grid is drawn. An arrow of length 3.0 m at 30° is projected onto x and y. The y-projection is half the magnitude. A second arrow in quadrant II is shown with a negative x-component and a spoken reminder that the sign is relative to the declared +x direction.",
  },
  {
    id: "bridge-algebra",
    slug: "algebra-for-physics",
    title: "Literal algebra before substitution",
    unit: "bridge",
    topics: ["B.2"],
    objectives: ["B.2.A"],
    capability: "Rearrange a physics equation symbolically and substitute only at the end.",
    prereqs: ["bridge-vectors"],
    minutes: [18, 25],
    ...review,
    prediction: {
      prompt:
        "Coulomb\u2019s law is $F = k |q_1 q_2| / r^2$. Solving for $r$ gives",
      choices: [
        { id: "A", text: "$r = k |q_1 q_2| / F$" },
        { id: "B", text: "$r = \\sqrt{k |q_1 q_2| / F}$", correct: true },
        { id: "C", text: "$r = k |q_1 q_2| / F^2$" },
        { id: "D", text: "$r = F / (k |q_1 q_2|)$" },
      ],
      explanation:
        "Multiply both sides by $r^2$, divide by $F$, then take the positive square root because $r$ is a distance.",
    },
    explanation: {
      model: "Most E&M results are relationships among symbols. Numbers come last so that dependence on each quantity stays visible.",
      represent: "List knowns, unknown, and the equation that actually applies. Box the target symbol.",
      derive: "Use inverse operations, keeping both sides equal. Roots and signs are physical decisions, not automatic algebra.",
      check: "Dimensions must match on both sides after rearranging. If $r$ is a length, the right-hand side must be a length.",
      explain: "Substituting too early hides how the answer scales. Exam solutions that keep symbols also survive rounding until the last line.",
    },
    workedExample: {
      title: "Isolate $E$ from $V = Ed$ for uniform field",
      situation: "A uniform field exists between plates separated by $d$. The potential difference is $V$. Find $E$.",
      assumptions: ["Uniform field; path along a field line; $V$ is the magnitude of the potential difference."],
      derivation: "$|\\Delta V| = E d$ so $E = |\\Delta V|/d$.",
      units: "V/m, which is also N/C.",
      interpretation: "Closer plates at fixed $V$ mean a stronger field.",
      whyAlternativesFail: "$E = V d$ fails a unit check. $E = V/d^2$ invents an extra length.",
    },
    fadedExample: {
      situation: "From $U = k q_1 q_2 / r$, isolate $r$.",
      steps: [
        { prompt: "Multiply both sides by $r$.", hint: "Clear the denominator first.", expected: "$U r = k q_1 q_2$." },
        { prompt: "Solve for $r$.", hint: "Divide by $U$, watching the sign of $U$.", expected: "$r = k q_1 q_2 / U$. If $U$ is negative (opposite charges), $r$ is still positive because $q_1 q_2$ is also negative." },
      ],
    },
    independentItemIds: ["br-alg-1"],
    videoAlt: "An equation is rearranged on a board without inserting numbers until the final substitution. A unit check catches $E = Vd$.",
  },
  {
    id: "bridge-graphs",
    slug: "graph-slopes-and-areas",
    title: "Slope and area as physical operations",
    unit: "bridge",
    topics: ["B.3"],
    objectives: ["B.3.A"],
    capability: "Read a slope and an area from a physics graph and assign units.",
    prereqs: ["bridge-algebra"],
    minutes: [20, 28],
    ...review,
    prediction: {
      prompt: "On a graph of $V(x)$ versus $x$, the slope at a point is",
      choices: [
        { id: "A", text: "the potential energy." },
        { id: "B", text: "$-E_x$ at that point, for a 1-D electrostatic field.", correct: true },
        { id: "C", text: "the flux through a surface at $x$." },
        { id: "D", text: "always positive because potential is a scalar." },
      ],
      explanation:
        "In one dimension $E_x = -dV/dx$. The slope can be negative. Flux is an integral of $\\vec{E}\\cdot d\\vec{A}$, not a derivative of $V$.",
    },
    explanation: {
      model: "A graph encodes a function. Slope is a local rate; area is an accumulation between bounds you must state.",
      represent: "Name both axes with symbols and units. Mark the interval of interest.",
      derive: "Average slope $\\Delta y/\\Delta x$. Area $\\int y\\,dx$ has units of (y-unit)×(x-unit).",
      check: "A horizontal $V(x)$ means $E_x = 0$ on that interval, not that $V = 0$.",
      explain: "You cannot read flux from a $V$ graph without reconstructing $\\vec{E}$ and specifying a surface.",
    },
    workedExample: {
      title: "Area under $E_x(x)$",
      situation: "$E_x$ is $20\\,\\mathrm{N/C}$ from $x=0$ to $x=0.10\\,\\mathrm{m}$ and zero elsewhere. Find $\\Delta V$ along $x$.",
      assumptions: ["1-D; path along +x; electrostatics so $\\Delta V = -\\int E_x dx$."],
      derivation: "$\\Delta V = - (20)(0.10) = -2.0\\,\\mathrm{V}$ from 0 to 0.10 m.",
      units: "(N/C)·m = V.",
      interpretation: "Potential drops in the direction of $E_x$.",
      whyAlternativesFail: "Using $+\\int E\\,dx$ flips the sign convention $E = -dV/dx$.",
    },
    fadedExample: {
      situation: "A current graph $I(t)$ is a triangle from (0,0) to (2 s, 4 A) to (4 s, 0).",
      steps: [
        { prompt: "What physical quantity is the area?", hint: "$I = dQ/dt$.", expected: "Net charge that passed in 4 s." },
        { prompt: "Compute it.", hint: "Triangle area $\\tfrac12$ base height.", expected: "$\\tfrac12 (4\\,\\mathrm{s})(4\\,\\mathrm{A}) = 8\\,\\mathrm{C}$." },
      ],
    },
    independentItemIds: ["br-graph-1"],
    retrievalItemId: "br-graph-r",
    videoAlt: "A V-versus-x graph with a negative slope is annotated as a positive E_x. An area under E_x is shaded and converted to a potential difference with a minus sign.",
  },
  {
    id: "bridge-derivatives",
    slug: "derivatives-in-physics",
    title: "Derivatives as rates with signs",
    unit: "bridge",
    topics: ["B.4"],
    objectives: ["B.4.A"],
    capability: "Write a derivative for a physical rate and interpret its sign.",
    prereqs: ["bridge-graphs"],
    minutes: [18, 25],
    ...review,
    prediction: {
      prompt: "If $Q(t) = Q_0 e^{-t/\\tau}$ with $Q_0\u003e0$, then $dQ/dt$ at $t=0$ is",
      choices: [
        { id: "A", text: "zero, because the function is smooth." },
        { id: "B", text: "$-Q_0/\\tau$", correct: true },
        { id: "C", text: "$+Q_0/\\tau$" },
        { id: "D", text: "undefined; exponentials have no derivative at the origin." },
      ],
      explanation: "$dQ/dt = - (Q_0/\\tau) e^{-t/\\tau}$, which equals $-Q_0/\\tau$ at $t=0$. Charge is leaving the capacitor.",
    },
    explanation: {
      model: "A derivative is the instantaneous rate of change of a modelled quantity.",
      represent: "Write the function, the independent variable, and the interval of validity.",
      derive: "Power rule, chain rule, and $d(e^{u})/dt = e^{u} du/dt$ cover nearly all course rates.",
      check: "Units of $dQ/dt$ are coulombs per second (amperes). A decreasing positive $Q$ has negative derivative.",
      explain: "\u201cThe current is $Q/t$\u201d is an average, not the instantaneous current unless $Q$ is linear.",
    },
    workedExample: {
      title: "Induced emf from a flux function",
      situation: "$\\Phi_B(t) = 0.012\\,t^2$ (SI) for $0\\le t\\le 2\\,\\mathrm{s}$. Find $\\mathcal{E}(1.0\\,\\mathrm{s})$.",
      assumptions: ["Single-turn loop; Faraday $\\mathcal{E}=-d\\Phi_B/dt$."],
      derivation: "$d\\Phi_B/dt = 0.024 t$, so $\\mathcal{E}(1) = -0.024\\,\\mathrm{V}$.",
      units: "Weber per second is volt.",
      interpretation: "The minus sign is Lenz\u2019s law in derivative clothing; magnitude 24 mV.",
      whyAlternativesFail: "Evaluating $\\Phi/t$ at 1 s gives 0.012 V and misses both the factor 2 and the meaning of a derivative.",
    },
    fadedExample: {
      situation: "$V(x) = 4x - x^3$ (SI) on the x-axis.",
      steps: [
        { prompt: "Find $E_x$.", hint: "$E_x = -dV/dx$.", expected: "$E_x = -4 + 3x^2$." },
        { prompt: "Where is $E_x=0$?", hint: "Solve $-4 + 3x^2 = 0$.", expected: "$x = \\pm\\sqrt{4/3}\\,\\mathrm{m}$ (within the model\u2019s domain)." },
      ],
    },
    independentItemIds: ["br-der-1"],
    videoAlt: "A discharging exponential is sketched. Tangents at t=0 and at t=τ are drawn; the first is steeper and negative.",
  },
  {
    id: "bridge-integrals",
    slug: "definite-integrals",
    title: "Definite integrals with physical bounds",
    unit: "bridge",
    topics: ["B.5"],
    objectives: ["B.5.A"],
    capability: "Build a source element, choose bounds, and integrate a required component.",
    prereqs: ["bridge-derivatives"],
    minutes: [22, 32],
    ...review,
    prediction: {
      prompt: "For a uniform line charge $\\lambda$ from $x=-L$ to $x=L$, the field on the perpendicular bisector uses which symmetry?",
      choices: [
        { id: "A", text: "Every $dE_x$ cancels; $dE_y$ adds.", correct: true },
        { id: "B", text: "Every $dE_y$ cancels; $dE_x$ adds." },
        { id: "C", text: "No components cancel; you must integrate a vector without simplifying." },
        { id: "D", text: "Gauss\u2019s law with a sphere centred on one end." },
      ],
      explanation:
        "Pair elements at $\\pm x$. Their components along the rod cancel; components along the bisector add. A sphere at one end has no useful symmetry.",
    },
    explanation: {
      model: "A continuous source is a pile of $dq$. The field (or potential) is the integral of the contribution of each $dq$.",
      represent: "Draw $dq$, the vector to the field point, and the component you will keep. Write $dq = \\lambda dx$ or $\\sigma dA$.",
      derive: "Only scalars integrate easily. Resolve $\\vec{dE}$ first, then $\\int dE_\\parallel$.",
      check: "Bounds must match the object you drew. Dimensions: $\\lambda dx$ is charge.",
      explain: "Skipping the component step and integrating $|dE|$ as if it were a scalar invents a field that points nowhere in particular.",
    },
    workedExample: {
      title: "Charge on a rod",
      situation: "A rod of length $L$ has $\\lambda = bx$ with $x$ from 0 to $L$. Find $Q$.",
      assumptions: ["$\\lambda$ is charge per length along the rod; $b$ has units C/m²."],
      derivation: "$Q = \\int_0^L bx\\,dx = \\tfrac12 b L^2$.",
      units: "(C/m²)·m² = C.",
      interpretation: "More charge sits toward $x=L$. The average $\\lambda$ is not $\\lambda(0)$.",
      whyAlternativesFail: "$Q = \\lambda L$ with a single $\\lambda$ is only for uniform rods.",
    },
    fadedExample: {
      situation: "Uniform ring, radius $R$, charge $Q$. Field on axis at distance $z$.",
      steps: [
        { prompt: "Why do transverse components cancel?", hint: "Pair opposite $dq$.", expected: "Each pair\u2019s components perpendicular to the axis cancel by symmetry." },
        { prompt: "Write $dE_z$.", hint: "$dE \\cos\\theta$ with $\\cos\\theta = z/\\sqrt{R^2+z^2}$.", expected: "$dE_z = (k dq /(R^2+z^2)) (z/\\sqrt{R^2+z^2})$." },
      ],
    },
    independentItemIds: ["br-int-1"],
    investigationId: "charge-field",
    videoAlt: "A rod is sliced into dq elements. Pairwise cancellation of components along the rod is shown before the remaining integral is written.",
  },
  {
    id: "bridge-exponentials",
    slug: "exponential-functions",
    title: "Exponentials and time constants",
    unit: "bridge",
    topics: ["B.6"],
    objectives: ["B.6.A"],
    capability: "Identify $\\tau$ in $e^{\\pm t/\\tau}$ and evaluate characteristic times.",
    prereqs: ["bridge-integrals"],
    minutes: [18, 25],
    ...review,
    prediction: {
      prompt: "A quantity $I(t) = I_0 e^{-t/\\tau}$ falls to $I_0/e$ when",
      choices: [
        { id: "A", text: "$t = \\tau$", correct: true },
        { id: "B", text: "$t = \\tau \\ln 2$" },
        { id: "C", text: "$t = 2\\tau$" },
        { id: "D", text: "$t = 0$" },
      ],
      explanation: "$e^{-1} = 1/e$ at $t=\\tau$. Half-life is $\\tau\\ln 2$, a different marker.",
    },
    explanation: {
      model: "Linear first-order rate equations produce exponentials. $\\tau$ is the time scale in the exponent, not a lifetime in the biological sense.",
      represent: "Write $Q(t)$ or $I(t)$ with $Q_0$ or $I_0$ and $\\tau$ defined from circuit parameters.",
      derive: "If $dQ/dt = -Q/\\tau$, the solution is $Q = Q_0 e^{-t/\\tau}$.",
      check: "At $t=0$ the exponential is 1. As $t\\to\\infty$ a decaying exponential goes to 0.",
      explain: "Calling every exponential \u201chalf-life\u201d mixes $\\ln 2$ into problems that asked for $\\tau$.",
    },
    workedExample: {
      title: "RC time constant",
      situation: "$R=4.0\\,\\mathrm{k}\\Omega$, $C=2.5\\,\\mu\\mathrm{F}$. Find $\\tau$ and the time to reach 1% of $Q_0$ on discharge.",
      assumptions: ["Series RC; no leakage; $t=0$ at the start of discharge."],
      derivation: "$\\tau=RC=1.0\\times 10^{-2}\\,\\mathrm{s}$. $e^{-t/\\tau}=0.01 \\Rightarrow t=\\tau\\ln 100 \\approx 46\\,\\mathrm{ms}$.",
      units: "Ohms times farads is seconds.",
      interpretation: "About five time constants leave a few percent; $\\ln 100 \\approx 4.6\\tau$ for 1%.",
      whyAlternativesFail: "Using $t=5\\tau$ as exact 1% is a rule of thumb, not this calculation.",
    },
    fadedExample: {
      situation: "$I(t)= (V/R)(1-e^{-t/\\tau})$ in an RL circuit.",
      steps: [
        { prompt: "What is $I(0)$?", hint: "The exponential is 1.", expected: "0." },
        { prompt: "What is $I(\\infty)$?", hint: "The exponential dies.", expected: "$V/R$." },
      ],
    },
    independentItemIds: ["br-exp-1"],
    videoAlt: "A decaying exponential is marked at t=0, τ, and 5τ. A separate tick marks τ ln 2 for half remaining.",
  },
  {
    id: "bridge-de",
    slug: "separable-differential-equations",
    title: "Separable differential equations",
    unit: "bridge",
    topics: ["B.7"],
    objectives: ["B.7.A"],
    capability: "Separate variables, integrate, and apply an initial condition to a first-order DE.",
    prereqs: ["bridge-exponentials"],
    minutes: [22, 32],
    ...review,
    prediction: {
      prompt: "From $C\\,dV/dt = -V/R$ with $V(0)=V_0$, $V(t)$ is",
      choices: [
        { id: "A", text: "$V_0 e^{-t/(RC)}$", correct: true },
        { id: "B", text: "$V_0 e^{+t/(RC)}$" },
        { id: "C", text: "$V_0 (1-e^{-t/(RC)})$" },
        { id: "D", text: "$V_0 RC / t$" },
      ],
      explanation: "This is discharge, not charge. The charging form $1-e^{-t/\\tau}$ would start at 0, contradicting $V(0)=V_0$.",
    },
    explanation: {
      model: "A governing equation relates a rate to the present value. Separable means you can move all $V$ to one side and $t$ to the other.",
      represent: "Write $dV/V = -dt/\\tau$ with $\\tau=RC$, and state $V(0)$.",
      derive: "$\\ln|V/V_0| = -t/\\tau$, so $V=V_0 e^{-t/\\tau}$.",
      check: "Differentiate the answer and substitute back into the DE. Check the initial condition.",
      explain: "The form with $(1-e^{-\\cdots})$ solves a different DE: charging toward a nonzero asymptote from zero.",
    },
    workedExample: {
      title: "Discharge of C through R",
      situation: "Derive $Q(t)$ from $I=-V/R$, $I=dQ/dt$, $V=Q/C$, $Q(0)=Q_0$.",
      assumptions: ["Series loop; sign: current decreases $Q$ on the capacitor plate we call positive."],
      derivation: "$dQ/dt = -Q/(RC)$. Separate, integrate, apply $Q_0$. $Q=Q_0 e^{-t/RC}$.",
      units: "Each term in the DE is current (amperes).",
      interpretation: "The capacitor\u2019s own voltage drives the current that reduces its charge.",
      whyAlternativesFail: "Using $I=+V/R$ without a sign convention yields runaway growth, which the circuit cannot do.",
    },
    fadedExample: {
      situation: "Charging: $\\mathcal{E} = IR + Q/C$, $I=dQ/dt$, $Q(0)=0$.",
      steps: [
        { prompt: "Write the DE for $Q$.", hint: "Replace $I$.", expected: "$\\mathcal{E} = R\\,dQ/dt + Q/C$." },
        { prompt: "What is $Q(\\infty)$?", hint: "Derivatives vanish in the steady state.", expected: "$Q_\\infty = C\\mathcal{E}$." },
      ],
    },
    independentItemIds: ["br-de-1"],
    videoAlt: "Variables are separated on the board, both sides integrated, and the constant fixed by Q(0). The result is differentiated to recover the DE.",
  },
  {
    id: "bridge-energy",
    slug: "mechanics-energy",
    title: "Energy accounting as a template",
    unit: "bridge",
    topics: ["B.8"],
    objectives: ["B.8.A"],
    capability: "State a reference, write ΔK + ΔU = W_nonconservative, and track signs.",
    prereqs: ["bridge-algebra"],
    minutes: [20, 28],
    ...review,
    prediction: {
      prompt: "A charge is released from rest in a conservative electrostatic field. Its kinetic energy",
      choices: [
        { id: "A", text: "can increase only if a nonconservative agent does work." },
        { id: "B", text: "increases if the charge moves to lower potential energy.", correct: true },
        { id: "C", text: "is always zero because electrostatic forces do no work." },
        { id: "D", text: "depends on the path because potential is path-dependent." },
      ],
      explanation: "Electrostatics is conservative. $K+U$ is constant if no nonconservative work. Loss of $U$ appears as $K$.",
    },
    explanation: {
      model: "Energy is an accounting system. Potential energy belongs to a system and requires a reference.",
      represent: "Name the system, the initial and final states, and $U=0$.",
      derive: "For conservative forces $\\Delta K = -\\Delta U$. With a battery or friction, include $W_{nc}$.",
      check: "A negative $\\Delta U$ with $\\Delta K\u003e0$ is consistent. Units are joules.",
      explain: "\u201cThe charge has potential\u201d is shorthand. Potential $V$ is energy per charge; $U=qV$.",
    },
    workedExample: {
      title: "Proton between plates",
      situation: "A proton is released from rest at the positive plate. Plate gap $d$, potential difference $V$. Find speed just before the negative plate.",
      assumptions: ["Vacuum; gravity neglected; $U=0$ at the negative plate."],
      derivation: "$\\tfrac12 mv^2 = qV$, so $v=\\sqrt{2qV/m}$.",
      units: "Joules on both sides.",
      interpretation: "The result is independent of $d$ at fixed $V$, though the field and the time of flight are not.",
      whyAlternativesFail: "Using $qEd$ and $V$ together without $E=V/d$ double-counts. Using electron mass is a particle-identity error.",
    },
    fadedExample: {
      situation: "Two protons approach along a line, each with speed $v_0$ far away.",
      steps: [
        { prompt: "What is a sensible $U=0$?", hint: "Infinite separation is standard for point charges.", expected: "$U\\to 0$ as $r\\to\\infty$." },
        { prompt: "Closest-approach condition?", hint: "Symmetric, momentary rest in CM frame if equal mass.", expected: "$2\\times\\tfrac12 m v_0^2 = k e^2 / r_{\\min}$." },
      ],
    },
    independentItemIds: ["br-en-1"],
    videoAlt: "A bar chart of U and K for a proton moving toward a negative plate. The total height stays constant.",
  },
  {
    id: "bridge-force",
    slug: "force-and-newtons-laws",
    title: "Forces, free-body diagrams, and equilibrium",
    unit: "bridge",
    topics: ["B.9"],
    objectives: ["B.9.A"],
    capability: "Draw a free-body diagram for a charged object and write Newton\u2019s second law.",
    prereqs: ["bridge-vectors"],
    minutes: [18, 26],
    ...review,
    prediction: {
      prompt: "A hanging charged pith ball is deflected by a nearby charge and is at rest. The net force is",
      choices: [
        { id: "A", text: "the Coulomb force alone." },
        { id: "B", text: "zero.", correct: true },
        { id: "C", text: "equal to tension." },
        { id: "D", text: "mg downward, because electrostatic forces are not \u201creal\u201d mechanical forces." },
      ],
      explanation: "At rest, $\\sum \\vec{F}=0$. Tension, gravity, and the electric force form a closed vector triangle.",
    },
    explanation: {
      model: "Treat the object as a particle if rotation is irrelevant. Every agent that pushes or pulls appears on the diagram.",
      represent: "Dots, arrows from the particle, labelled $T$, $mg$, $q\\vec{E}$ or $\\vec{F}_C$.",
      derive: "Resolve axes and write $\\sum F_x=ma_x$, $\\sum F_y=ma_y$. Equilibrium is $a=0$.",
      check: "If the object is at rest and your forces do not close, a force is missing or a sign is wrong.",
      explain: "Electric force is a mechanical force in Newton\u2019s law. It is not an extra \u201celectrical acceleration.\u201d",
    },
    workedExample: {
      title: "Millikan-style balance",
      situation: "An oil drop of mass $m$ and charge $q$ is stationary between horizontal plates with field $E$ upward. Find $q$.",
      assumptions: ["No drag at terminal/zero velocity; $E$ uniform; gravity down."],
      derivation: "$qE = mg$, so $q = mg/E$, positive if $E$ is up and the drop is not falling.",
      units: "Coulombs.",
      interpretation: "The field must point so that $q\\vec{E}$ opposes weight.",
      whyAlternativesFail: "Using $qE + mg = 0$ with both treated as positive scalars without directions hides the sign of $q$.",
    },
    fadedExample: {
      situation: "Two identical charges hang from strings of length $L$, separated by $x$ at equilibrium.",
      steps: [
        { prompt: "Which forces act on one sphere?", hint: "Three.", expected: "Tension, weight, Coulomb repulsion." },
        { prompt: "Horizontal equilibrium?", hint: "Resolve $T$.", expected: "$T\\sin\\theta = k q^2 / x^2$." },
      ],
    },
    independentItemIds: ["br-force-1"],
    videoAlt: "A pith-ball free-body diagram is built one arrow at a time. The three arrows close. Newton\u2019s second law is written as a vector sum equal to zero.",
  },
  {
    id: "bridge-units",
    slug: "dimensions-and-units",
    title: "Dimensions and SI units in E\u0026M",
    unit: "bridge",
    topics: ["B.10"],
    objectives: ["B.10.A"],
    capability: "Reject an equation that fails a unit check and convert among N/C, V/m, T, Wb, and H.",
    prereqs: ["bridge-algebra"],
    minutes: [16, 24],
    ...review,
    prediction: {
      prompt: "Which is a valid unit of electric field?",
      choices: [
        { id: "A", text: "N/C and V/m, which are identical.", correct: true },
        { id: "B", text: "J/C, which is the same as N/C." },
        { id: "C", text: "T·m/s" },
        { id: "D", text: "Wb" },
      ],
      explanation: "J/C is the volt (potential). Tesla is magnetic field. Weber is flux.",
    },
    explanation: {
      model: "Every symbol in an equation carries units. A derived SI unit is a nickname for a combination of base units.",
      represent: "Write the candidate equation and expand each quantity into SI base units.",
      derive: "$[E]=\\mathrm{N/C}=\\mathrm{J/(C\\cdot m)}=\\mathrm{V/m}$. $[B]=\\mathrm{T}=\\mathrm{N\\cdot s/(C\\cdot m)}$.",
      check: "Arguments of exp, ln, and trig functions are dimensionless.",
      explain: "If $e^{-t/RC}$ appears, $RC$ must be seconds. That is a design check for transients.",
    },
    workedExample: {
      title: "Is $\\Phi_E = E A$ dimensionally allowed?",
      situation: "Someone writes net flux as $E$ times surface area for a cube in a uniform field.",
      assumptions: ["Uniform $E$; faces perpendicular or parallel to $E$."],
      derivation: "$[E A] = (\\mathrm{N/C})\\mathrm{m}^2 = \\mathrm{N\\cdot m}^2/\\mathrm{C}$, which matches $[Q/\\varepsilon_0]$. For a closed cube in uniform $E$, net flux is still zero.",
      units: "Flux SI unit is $\\mathrm{N\\cdot m}^2/\\mathrm{C}$ or $\\mathrm{V\\cdot m}$.",
      interpretation: "The formula $EA$ can be a face flux, not automatically the net flux.",
      whyAlternativesFail: "Treating $EA$ as Gauss\u2019s law without $Q_{\\mathrm{enc}}$ confuses a useful special case with the law.",
    },
    fadedExample: {
      situation: "Show that $RC$ has units of time.",
      steps: [
        { prompt: "Ohm\u2019s law units for $R$.", hint: "$R=V/I$.", expected: "V/A, or $\\Omega$." },
        { prompt: "Combine with farads.", hint: "$C=Q/V$ and $I=Q/t$.", expected: "$RC = (V/I)(Q/V)=Q/I=t$." },
      ],
    },
    independentItemIds: ["br-unit-1"],
    videoAlt: "A unit table for E, V, Φ, B, and L is filled from definitions rather than memorised nicknames.",
  },
  {
    id: "bridge-signs",
    slug: "sign-conventions",
    title: "Sign conventions you can defend",
    unit: "bridge",
    topics: ["B.11"],
    objectives: ["B.11.A"],
    capability: "Choose a sign convention, keep it, and interpret a negative solved value.",
    prereqs: ["bridge-vectors"],
    minutes: [16, 24],
    ...review,
    prediction: {
      prompt: "A loop equation yields $I = -0.20\\,\\mathrm{A}$ relative to an arrow you drew. This means",
      choices: [
        { id: "A", text: "the calculation is impossible; current cannot be negative." },
        { id: "B", text: "the actual current is 0.20 A opposite your assumed direction.", correct: true },
        { id: "C", text: "the battery polarity is physically reversed in the lab." },
        { id: "D", text: "power is negative, so the resistor generates energy." },
      ],
      explanation:
        "The minus sign is relative to the assumed arrow. Reverse the arrow in the diagram and take $I=0.20\\,\\mathrm{A}$. Power in an ohmic resistor is still $I^2 R \u003e 0$.",
    },
    explanation: {
      model: "Signs are not in nature; they are in the representation. Charge sign, current arrows, loop sense, and area-normal all need a sentence.",
      represent: "Draw the arrow. State \u201cclockwise is positive\u201d or \u201cthe normal follows the right-hand rule from the loop sense.\u201d",
      derive: "Every term in Kirchhoff or Faraday uses that same convention.",
      check: "If you change the loop sense, every signed term flips and the physics is unchanged.",
      explain: "A negative flux means the field has a component opposite your chosen normal, not that flux is \u201cunphysical.\u201d",
    },
    workedExample: {
      title: "Negative current in a two-loop circuit",
      situation: "Assume $I_2$ to the right through a 4 Ω resistor. Algebra gives $I_2=-0.5\\,\\mathrm{A}$. Find the actual power in that resistor.",
      assumptions: ["Ohmic resistor; steady DC."],
      derivation: "$P=I^2 R = (0.5)^2(4)=1.0\\,\\mathrm{W}$ dissipated, current 0.5 A to the left.",
      units: "Watts.",
      interpretation: "The assumption was wrong in direction, not in the existence of current.",
      whyAlternativesFail: "Reporting $P=-1\\,\\mathrm{W}$ treats the algebraic current as a power source.",
    },
    fadedExample: {
      situation: "Area normal of a loop points out of the page; $\\vec{B}$ points into the page and is increasing.",
      steps: [
        { prompt: "Sign of $\\Phi_B$?", hint: "Opposite to the normal.", expected: "Negative if out-of-page is positive." },
        { prompt: "Sign of $d\\Phi_B/dt$?", hint: "More negative if into-page field grows.", expected: "Negative and decreasing (derivative negative)." },
      ],
    },
    independentItemIds: ["br-sign-1"],
    videoAlt: "A current arrow is drawn, a negative result obtained, and the arrow is then redrawn the other way with a positive value of the same magnitude.",
  },
  {
    id: "bridge-limits",
    slug: "limiting-cases",
    title: "Limiting cases as a check",
    unit: "bridge",
    topics: ["B.12"],
    objectives: ["B.12.A"],
    capability: "Name a physically meaningful limit and use it to reject an algebraic result.",
    prereqs: ["bridge-algebra", "bridge-units"],
    minutes: [16, 24],
    ...review,
    prediction: {
      prompt: "The on-axis field of a ring of radius $R$ and charge $Q$, at distance $z$, must satisfy",
      choices: [
        { id: "A", text: "$E\\to\\infty$ as $z\\to\\infty$ because the ring is still there." },
        { id: "B", text: "$E\\to 0$ as $z\\to\\infty$, like a point charge $Q$.", correct: true },
        { id: "C", text: "$E$ is independent of $z$ by Gauss\u2019s law." },
        { id: "D", text: "$E\\to 0$ as $z\\to 0$ only if $Q=0$." },
      ],
      explanation:
        "Far away the ring is a point. At the centre, transverse cancellation makes $E=0$ even if $Q\\neq 0$. Gauss\u2019s law does not give a unique $E$ for this symmetry.",
    },
    explanation: {
      model: "A formula is a claim about every allowed input. Extreme inputs are cheap experiments.",
      represent: "Identify parameters you can send to 0 or $\\infty$ without leaving the model: $r$, $t$, $\\kappa$, $R$, $d$.",
      derive: "Take the limit of the closed-form expression. Series expansion is optional enrichment.",
      check: "If $t\\to\\infty$ on a discharging capacitor does not give $Q\\to 0$, the DE solution is wrong.",
      explain: "Limits also expose idealisations: $r\\to 0$ at a point charge is not a physical measurement.",
    },
    workedExample: {
      title: "Parallel-plate $C$ as $d\\to 0$",
      situation: "$C=\\varepsilon_0 A/d$. What happens as $d\\to 0$ at fixed $A$?",
      assumptions: ["Infinite-plate idealisation; vacuum; no dielectric breakdown."],
      derivation: "$C\\to\\infty$. The model has left the laboratory: plates cannot occupy the same plane and still be a capacitor.",
      units: "Farads grow without bound in the formula.",
      interpretation: "Use the formula only while $d$ is small compared with plate linear size but not atomically small.",
      whyAlternativesFail: "Claiming $C\\to 0$ as plates approach contradicts both the formula and the increase in stored charge at fixed $V$.",
    },
    fadedExample: {
      situation: "Point-charge field $E=kq/r^2$.",
      steps: [
        { prompt: "Limit $r\\to\\infty$.", hint: "Denominator grows.", expected: "$E\\to 0$." },
        { prompt: "Is $r\\to 0$ a valid check of a measurement?", hint: "Idealisations.", expected: "No. The point model is excluded at the source; the formula diverges." },
      ],
    },
    independentItemIds: ["br-lim-1"],
    videoAlt: "An on-axis ring-field formula is plotted versus z. The curve is zero at the origin and falls as 1/z² at large z, matching a point charge.",
  },
];
