import type { Lesson } from "@/lib/types";

const review = {
  reviewDate: "2026-09-10",
  authors: [
    { name: "Anannt physics author", role: "author" as const },
    { name: "Independent physics reviewer", role: "reviewer" as const },
  ],
  version: "1.0",
  status: "published" as const,
};

export const UNIT11_LESSONS: Lesson[] = [
  {
    id: "u11-current",
    slug: "electric-current",
    title: "Current as charge flow",
    unit: 11,
    topics: ["11.1"],
    objectives: ["11.1.A"],
    capability: "Use $I=dQ/dt$ and interpret the direction of conventional current, including a negative result.",
    prereqs: ["bridge-derivatives", "bridge-signs"],
    minutes: [18, 26],
    ...review,
    prediction: {
      prompt: "In a metal wire, conventional current to the right means",
      choices: [
        { id: "A", text: "protons drifting to the right." },
        { id: "B", text: "electrons drifting to the left.", correct: true },
        { id: "C", text: "the electric field pointing to the left." },
        { id: "D", text: "no net charge transport, only a field." },
      ],
      explanation: "Conventional current is the direction positive charge would flow. In metals the carriers are electrons, so they drift opposite the conventional current. $\\vec{E}$ in the wire points with the conventional current.",
    },
    explanation: {
      model: "$I = dQ/dt$ through a cross-section, with $Q$ the charge passing in the conventional sense. Steady current in a series circuit is the same at every cross-section.",
      represent: "Draw an arrow for $I$. If algebra later yields $I<0$, reverse the arrow.",
      derive: "Also $I = n q v_d A$ for drift. For electrons $q<0$ and $v_d$ is opposite $I$.",
      check: "Amperes = C/s. A capacitor being charged has $I$ onto the positive plate equal to $dQ/dt$ of that plate.",
      explain: "Current is not “used up” in a resistor. Energy is transferred; charge is not consumed.",
    },
    workedExample: {
      title: "Charging a plate",
      situation: "A capacitor plate’s charge goes from 0 to $12\\,\\mu\\mathrm{C}$ in $3.0\\,\\mathrm{ms}$ at a constant rate. Find $I$.",
      assumptions: ["Constant $dQ/dt$ during the interval."],
      derivation: "$I = \\Delta Q/\\Delta t = 4.0\\,\\mathrm{mA}$.",
      units: "A.",
      interpretation: "This is an average current if the rate is not truly constant; the problem stated constant rate.",
      whyAlternativesFail: "Using $Q t$ or $Q/t^2$.",
    },
    fadedExample: {
      situation: "Junction: 2.0 A in, 0.7 A out one branch.",
      steps: [
        { prompt: "Current in the remaining branch?", hint: "Charge conservation.", expected: "1.3 A out (or −1.3 A if you defined in as positive)." },
      ],
    },
    independentItemIds: ["u11-i-1"],
    retrievalItemId: "u11-i-r",
    videoAlt: "A wire with electron drift to the left and a conventional-current arrow to the right. A junction shows currents summing.",
  },
  {
    id: "u11-resistivity",
    slug: "resistance-and-resistivity",
    title: "Resistance, resistivity, and geometry",
    unit: 11,
    topics: ["11.2"],
    objectives: ["11.2.A"],
    capability: "Use $R=\\rho L/A$ and separate material from dimensions.",
    prereqs: ["u11-current"],
    minutes: [18, 26],
    ...review,
    prediction: {
      prompt: "A wire is stretched to twice its length, volume constant. $R$ is multiplied by",
      choices: [
        { id: "A", text: "2." },
        { id: "B", text: "4.", correct: true },
        { id: "C", text: "$1/2$." },
        { id: "D", text: "unchanged, because $\\rho$ is unchanged." },
      ],
      explanation: "Volume $AL$ constant: $A\\to A/2$ when $L\\to 2L$. $R=\\rho L/A \\to 4R$. Resistivity is unchanged at this level (ignore strain effects).",
    },
    explanation: {
      model: "Ohmic material: $V=IR$ with $R$ independent of $I$ in a range. $\\rho$ is a material property; $R$ is a device property.",
      represent: "Length along current, $A$ perpendicular.",
      derive: "$R=\\rho L/A$. Also $E=\\rho J$ as the local form.",
      check: "Ohms. Doubling $A$ halves $R$. Making a resistor shorter lowers $R$.",
      explain: "A “long thin” wire is high $R$ even if $\\rho$ is modest. Superconductors are outside ohmic $\\rho>0$.",
    },
    workedExample: {
      title: "Copper stub",
      situation: "$\\rho=1.7\\times 10^{-8}\\,\\Omega\\cdot\\mathrm{m}$, $L=0.50\\,\\mathrm{m}$, diameter $1.0\\,\\mathrm{mm}$. Find $R$.",
      assumptions: ["Uniform circular wire; room-temperature $\\rho$ given."],
      derivation: "$A=\\pi (5.0\\times 10^{-4})^2$, $R=\\rho L/A = 1.1\\times 10^{-2}\\,\\Omega$.",
      units: "Ω.",
      interpretation: "A thick short copper piece is almost a short circuit compared with typical resistors.",
      whyAlternativesFail: "Using radius as diameter, or $R=\\rho A/L$.",
    },
    fadedExample: {
      situation: "Same $R$, two materials, different $\\rho$.",
      steps: [
        { prompt: "Who needs more $L/A$?", hint: "$R=\\rho L/A$.", expected: "The smaller-$\\rho$ material needs larger $L/A$ to match $R$." },
      ],
    },
    independentItemIds: ["u11-rho-1"],
    retrievalItemId: "u11-rho-r",
    videoAlt: "A cylinder is stretched: L doubles, A halves, four times the resistance. ρ is labelled as unchanged.",
  },
  {
    id: "u11-power",
    slug: "electric-power",
    title: "Energy transfer rate in a circuit",
    unit: 11,
    topics: ["11.3"],
    objectives: ["11.3.A"],
    capability: "Use $P=IV$ with hypotheses, and locate where energy is transferred.",
    prereqs: ["u11-resistivity"],
    minutes: [20, 28],
    ...review,
    prediction: {
      prompt: "A 12 V battery drives 2.0 A through a heater. The heater’s power is",
      choices: [
        { id: "A", text: "6.0 W, because $P=V/I$." },
        { id: "B", text: "24 W, transferred from chemical energy in the battery to thermal energy.", correct: true },
        { id: "C", text: "24 W created in the wires from charge being used up." },
        { id: "D", text: "zero in the steady state because current is constant." },
      ],
      explanation: "$P=IV=24\\,\\mathrm{W}$. Charge is not used up. The battery’s chemical energy decreases; the heater’s thermal energy increases.",
    },
    explanation: {
      model: "$P=IV$ is the energy transfer rate at an element (careful with signs for batteries being charged). For an ohmic resistor $P=I^2 R = V^2/R$ as well.",
      represent: "Name the system: battery, resistor, connecting wires (often ideal, $R=0$).",
      derive: "In time $dt$, charge $dq=I dt$ loses $V dq$ of electrical energy traversing a potential drop $V$.",
      check: "Watts. $V^2/R$ is for the $V$ across that resistor, not the battery if other elements share $V$.",
      explain: "Ideal wires dissipate nothing. Real wires are small series $R$.",
    },
    workedExample: {
      title: "Which formula?",
      situation: "Two resistors 2 Ω and 4 Ω in series on 12 V. Power in the 4 Ω.",
      assumptions: ["Ohmic; ideal battery and wires."],
      derivation: "$I=12/6=2.0\\,\\mathrm{A}$. $P=I^2 R=16\\,\\mathrm{W}$. Alternatively $V_4=8.0\\,\\mathrm{V}$, $V^2/R=16\\,\\mathrm{W}$. Using battery 12 V in $V^2/R$ for the 4 Ω would be wrong.",
      units: "W.",
      interpretation: "The 4 Ω takes more of the series power because $P=I^2 R$ with the same $I$.",
      whyAlternativesFail: "$P=12^2/4=36\\,\\mathrm{W}$ assigns the whole battery voltage to one resistor.",
    },
    fadedExample: {
      situation: "Resistors in parallel, same $V$.",
      steps: [
        { prompt: "Who dissipates more, small $R$ or large $R$?", hint: "$P=V^2/R$.", expected: "The smaller $R$." },
      ],
    },
    independentItemIds: ["u11-p-1"],
    retrievalItemId: "u11-p-r",
    videoAlt: "Energy flow arrows from battery chemistry to a resistor’s thermal energy. Charge arrows go around the loop unchanged in the steady state.",
  },
  {
    id: "u11-circuit-models",
    slug: "circuit-models",
    title: "Ideal circuit elements and what they hide",
    unit: 11,
    topics: ["11.4"],
    objectives: ["11.4.A"],
    capability: "State the idealisations in a schematic: battery emf, internal resistance, ideal wires.",
    prereqs: ["u11-power"],
    minutes: [16, 24],
    ...review,
    prediction: {
      prompt: "A real battery is modelled as emf $\\mathcal{E}$ in series with $r$. Terminal voltage while supplying $I$ is",
      choices: [
        { id: "A", text: "$\\mathcal{E}$ always." },
        { id: "B", text: "$\\mathcal{E}-Ir$.", correct: true },
        { id: "C", text: "$\\mathcal{E}+Ir$." },
        { id: "D", text: "$Ir$ only." },
      ],
      explanation: "Inside the battery, you climb $\\mathcal{E}$ and drop $Ir$. Terminal voltage is $\\mathcal{E}-Ir$ when the battery supplies current. When being charged, $V=\\mathcal{E}+Ir$.",
    },
    explanation: {
      model: "Schematics replace physics with elements. Ideal wire: $R=0$, so $V$ is the same along it. Ideal voltmeter: infinite $R$. Ideal ammeter: zero $R$.",
      represent: "Draw $r$ explicitly if the problem mentions it. Otherwise the battery is ideal.",
      derive: "Closed-loop: $\\mathcal{E} = I(R+r)$ for a simple series heater.",
      check: "Open-circuit terminal voltage equals $\\mathcal{E}$. Short-circuit current is $\\mathcal{E}/r$ in this model (dangerous in the lab).",
      explain: "A 9 V battery showing 8.1 V under load is not “broken emf”; it is $Ir$ drop, or a dying $\\mathcal{E}$ and rising $r$.",
    },
    workedExample: {
      title: "Find $r$",
      situation: "$\\mathcal{E}=6.00\\,\\mathrm{V}$ on open circuit. Loaded with $10.0\\,\\Omega$, terminal voltage 5.80 V. Find $r$ and $I$.",
      assumptions: ["Series $r$ model; ohmic load."],
      derivation: "$I=5.80/10=0.580\\,\\mathrm{A}$. $Ir=0.20\\,\\mathrm{V}$, $r=0.34\\,\\Omega$.",
      units: "A and Ω.",
      interpretation: "Small $r$ compared with 10 Ω, so the load nearly sees $\\mathcal{E}$.",
      whyAlternativesFail: "Using $I=6/10$ while also using 5.80 V inconsistently.",
    },
    fadedExample: {
      situation: "Ammeter placed in parallel with a resistor (a mistake).",
      steps: [
        { prompt: "What does the ideal-ammeter model predict?", hint: "R=0.", expected: "A short across the resistor; large current, possibly a blown fuse." },
      ],
    },
    independentItemIds: ["u11-mod-1"],
    retrievalItemId: "u11-mod-r",
    videoAlt: "A battery icon is expanded into emf plus little r. A voltmeter across the terminals shows E minus Ir when current flows.",
  },
  {
    id: "u11-junctions",
    slug: "kirchhoff-junction-rule",
    title: "Junction equations from charge conservation",
    unit: 11,
    topics: ["11.5"],
    objectives: ["11.5.A"],
    capability: "Write $\\sum I_{\\mathrm{in}}=\\sum I_{\\mathrm{out}}$ at a node with a current map.",
    prereqs: ["u11-circuit-models"],
    minutes: [16, 24],
    ...review,
    investigationId: "circuit",
    prediction: {
      prompt: "At a junction, 3.0 A and 1.0 A enter. One outgoing branch carries 2.5 A. The other outgoing current is",
      choices: [
        { id: "A", text: "1.5 A.", correct: true },
        { id: "B", text: "6.5 A." },
        { id: "C", text: "0.5 A." },
        { id: "D", text: "undetermined without resistances." },
      ],
      explanation: "4.0 A enter, 2.5 A already leave, 1.5 A must leave the other branch. Resistances determine how the split happens in a full circuit, but the junction rule itself is conservation.",
    },
    explanation: {
      model: "Charge does not pile up at a node in the steady state (and in lumped circuits we assume that).",
      represent: "Label every branch current with an arrow before writing equations.",
      derive: "$\\sum I_{\\mathrm{in}}=\\sum I_{\\mathrm{out}}$, or equivalently $\\sum I = 0$ with a sign convention.",
      check: "Number of independent junction equations is nodes minus 1, typically.",
      explain: "The junction rule is not energy. It cannot by itself find currents without loop equations or equivalent resistance.",
    },
    workedExample: {
      title: "Three-branch node",
      situation: "Assume $I_1$ into the node, $I_2$ and $I_3$ out. Algebra later gives $I_1=0.40\\,\\mathrm{A}$, $I_2=-0.10\\,\\mathrm{A}$, $I_3=0.50\\,\\mathrm{A}$. Interpret.",
      assumptions: ["Steady DC; lumped circuit."],
      derivation: "Junction: $I_1 = I_2 + I_3 \\Rightarrow 0.40 = -0.10 + 0.50$, consistent. $I_2$ is actually 0.10 A opposite the assumed arrow.",
      units: "A.",
      interpretation: "Negative current is a reversed assumption, not a failed circuit.",
      whyAlternativesFail: "Discarding the solution because a current is negative.",
    },
    fadedExample: {
      situation: "Capacitor plate as a node during charging.",
      steps: [
        { prompt: "Does $I_{\\mathrm{in}}=I_{\\mathrm{out}}$ through the capacitor gap?", hint: "Displacement vs conduction.", expected: "Conduction current does not cross the gap. In the wires, $I$ onto one plate equals $I$ off the other. Maxwell’s addition is enrichment; AP C treats $I=dQ/dt$ in the leads." },
      ],
    },
    independentItemIds: ["u11-j-1"],
    retrievalItemId: "u11-j-r",
    videoAlt: "A node with incoming and outgoing current arrows. Numbers update so the algebraic sum is zero. A negative label is flipped.",
  },
  {
    id: "u11-loops",
    slug: "kirchhoff-loop-rule",
    title: "Loop equations from energy accounting",
    unit: 11,
    topics: ["11.6"],
    objectives: ["11.6.A"],
    capability: "Write a loop equation with a consistent sign convention and interpret a negative current.",
    prereqs: ["u11-junctions", "bridge-signs"],
    minutes: [22, 32],
    ...review,
    investigationId: "circuit",
    prediction: {
      prompt: "Walking around a loop with the assumed current, a resistor is a",
      choices: [
        { id: "A", text: "potential rise $+IR$." },
        { id: "B", text: "potential drop $-IR$.", correct: true },
        { id: "C", text: "drop only if the resistor is on the “bottom” of the diagram." },
        { id: "D", text: "rise if the current is negative." },
      ],
      explanation: "In the direction of assumed current, you go from high to low through a resistor: $-IR$. A negative solved $I$ later means you walked against the actual current, which is already handled by the algebra.",
    },
    explanation: {
      model: "Electrostatics in lumped circuits: the sum of potential changes around a closed path is zero (conservative $V$, neglecting induction until Unit 13).",
      represent: "Choose a loop sense. For each battery, $+\\mathcal{E}$ if you traverse − to + inside the battery.",
      derive: "$\\sum \\Delta V = 0$. Example: $\\mathcal{E} - IR_1 - IR_2 = 0$.",
      check: "If you reverse the loop sense, every sign flips and the equation is the same.",
      explain: "Assigning $+IR$ when walking with the current is a convention error that usually produces a current of the wrong sign or magnitude.",
    },
    workedExample: {
      title: "Single loop with two batteries",
      situation: "$\\mathcal{E}_1=12\\,\\mathrm{V}$, $\\mathcal{E}_2=4\\,\\mathrm{V}$ opposing, $R=8.0\\,\\Omega$. Find $I$.",
      assumptions: ["Ideal batteries; one loop; $\\mathcal{E}_1$ and $\\mathcal{E}_2$ opposing."],
      derivation: "Assume clockwise with $\\mathcal{E}_1$. $12 - 4 - 8I = 0$, $I=1.0\\,\\mathrm{A}$ clockwise.",
      units: "A.",
      interpretation: "The 12 V battery “wins.” Power: 12 W supplied by $\\mathcal{E}_1$, 4 W absorbed by $\\mathcal{E}_2$ (charging it, in this model), 8 W in $R$.",
      whyAlternativesFail: "Adding emfs $16/8=2\\,\\mathrm{A}$ as if they aided.",
    },
    fadedExample: {
      situation: "Loop includes a capacitor in the steady DC state.",
      steps: [
        { prompt: "Current through the capacitor branch?", hint: "Open circuit in DC steady state.", expected: "Zero. The capacitor is an open. $V_C$ is constant." },
        { prompt: "Does the loop rule still apply?", hint: "Yes, with $I=0$ in that branch.", expected: "Yes. The capacitor holds a potential difference $Q/C$." },
      ],
    },
    independentItemIds: ["u11-l-1", "u11-l-2"],
    retrievalItemId: "u11-l-r",
    videoAlt: "A finger walks around a loop: up a battery, down a resistor. Each ΔV is written. The sum is boxed as zero.",
  },
  {
    id: "u11-networks",
    slug: "multi-loop-networks",
    title: "Multi-loop networks",
    unit: 11,
    topics: ["11.7"],
    objectives: ["11.7.A"],
    capability: "Reduce series–parallel networks or write a consistent system of loop and junction equations.",
    prereqs: ["u11-loops"],
    minutes: [24, 35],
    ...review,
    investigationId: "circuit",
    prediction: {
      prompt: "Two 4 Ω resistors in parallel, then in series with 2 Ω, on 12 V. The current through the 2 Ω is",
      choices: [
        { id: "A", text: "2.0 A." },
        { id: "B", text: "3.0 A.", correct: true },
        { id: "C", text: "1.0 A." },
        { id: "D", text: "6.0 A." },
      ],
      explanation:
        "Two 4 Ω in parallel are 2 Ω. Adding the series 2 Ω gives $R_{\\mathrm{eq}}=4\\,\\Omega$. Total current $12/4=3.0\\,\\mathrm{A}$ is the current through the series 2 Ω.",
    },
    explanation: {
      model: "If the diagram is series–parallel, reduce. If it contains a bridge that cannot be reduced, use Kirchhoff or Δ–Y (Δ–Y is usually enrichment).",
      represent: "Redraw. Mark series (same $I$) and parallel (same $V$).",
      derive: "$R_s=\\sum R$, $1/R_p=\\sum 1/R$. Then $I=\\mathcal{E}/R_{\\mathrm{eq}}$ for a single battery.",
      check: "Currents into a parallel pair split inversely with $R$. Voltage across series elements split proportional to $R$.",
      explain: "Never add a parallel resistor as $R_1+R_2$ for $R_{\\mathrm{eq}}$. Never assume equal currents in unequal parallel resistors.",
    },
    workedExample: {
      title: "The 12 V network above",
      situation: "4 Ω || 4 Ω, in series with 2 Ω, 12 V battery. All currents.",
      assumptions: ["Ohmic; ideal battery."],
      derivation: "$R_{\\mathrm{eq}}=4.0\\,\\Omega$, $I_{2\\Omega}=3.0\\,\\mathrm{A}$. Each 4 Ω carries 1.5 A. $V_{\\mathrm{parallel}}=3.0\\,\\mathrm{V}$, $V_{2\\Omega}=6.0\\,\\mathrm{V}$.",
      units: "A and V.",
      interpretation: "The series 2 Ω takes half the battery voltage even though each 4 Ω is “larger,” because the parallel pair acts as 2 Ω.",
      whyAlternativesFail: "Sending the full 12 V across each 4 Ω, or giving the 2 Ω only 2 A from $12/(2+4)$.",
    },
    fadedExample: {
      situation: "Wheatstone-like unbalanced bridge (qualitative).",
      steps: [
        { prompt: "Can you use series–parallel reduction?", hint: "Look for a single pair that is purely series or parallel.", expected: "Usually not, unless a bridge current is zero by balance. Use two loops." },
      ],
    },
    independentItemIds: ["u11-n-1", "u11-n-2"],
    retrievalItemId: "u11-n-r",
    videoAlt: "A messy schematic is redrawn into a parallel pair plus a series resistor. Equivalent resistance is built in two steps, then currents are expanded back.",
  },
  {
    id: "u11-rc-transients",
    slug: "rc-transients",
    title: "RC transients: initial, final, and $Q(t)$",
    unit: 11,
    topics: ["11.8"],
    objectives: ["11.8.A"],
    capability: "Write the governing equation, apply $t=0$ and $t\\to\\infty$ shortcuts, and interpret $Q(t)=Q_\\infty(1-e^{-t/\\tau})$ or discharge.",
    prereqs: ["u11-loops", "bridge-de"],
    minutes: [28, 35],
    ...review,
    investigationId: "circuit",
    prediction: {
      prompt: "Just after a switch closes to charge an uncharged capacitor from a battery, the capacitor behaves as",
      choices: [
        { id: "A", text: "an open circuit, $I=0$." },
        { id: "B", text: "a short circuit, $V_C=0$, $I=\\mathcal{E}/R$.", correct: true },
        { id: "C", text: "a resistor of value $R$." },
        { id: "D", text: "a battery of emf $\\mathcal{E}$." },
      ],
      explanation: "Uncharged means $V_C=Q/C=0$ at $t=0^+$. The loop is $\\mathcal{E}=IR$ at that instant. Long after, $I=0$ and $V_C=\\mathcal{E}$.",
    },
    explanation: {
      model: "The capacitor’s $V$ cannot jump if $I$ is finite, because $I=C dV/dt$. Inductors will get the dual statement in Unit 13.",
      represent: "Redraw the circuit at $t=0^+$ (C as wire if uncharged) and at $t=\\infty$ (C as open for DC).",
      derive: "Charging: $Q(t)=C\\mathcal{E}(1-e^{-t/RC})$. Discharging: $Q=Q_0 e^{-t/RC}$. $\\tau=RC$.",
      check: "At $t=\\tau$, charging $Q$ is at $1-1/e\\approx 63\\%$ of $Q_\\infty$. Units of $RC$ are seconds.",
      explain: "Using the charging formula for a discharge, or setting $I=\\mathcal{E}/R$ at late times, are the standard errors. After two failed repairs, change representation: time graph instead of formula.",
    },
    workedExample: {
      title: "Charge after one time constant",
      situation: "$R=8.0\\,\\mathrm{k}\\Omega$, $C=5.0\\,\\mu\\mathrm{F}$, $\\mathcal{E}=9.0\\,\\mathrm{V}$, charging from $Q=0$. Find $Q(\\tau)$ and $I(\\tau)$.",
      assumptions: ["Series RC; switch closed at $t=0$."],
      derivation: "$\\tau=0.040\\,\\mathrm{s}$. $Q_\\infty=45\\,\\mu\\mathrm{C}$. $Q(\\tau)=45(1-e^{-1})=28\\,\\mu\\mathrm{C}$. $I(\\tau)=(\\mathcal{E}/R)e^{-1}=0.41\\,\\mathrm{mA}$.",
      units: "C and A.",
      interpretation: "Current has fallen to 37% of $I(0)$ while charge is at 63% of maximum — they are complementary exponentials.",
      whyAlternativesFail: "Taking $Q(\\tau)=Q_\\infty/2$, mixing with half-life $\\ln 2$.",
    },
    fadedExample: {
      situation: "Discharge of 40 μC through 2 kΩ and 10 μF.",
      steps: [
        { prompt: "$\\tau$?", hint: "RC.", expected: "0.020 s." },
        { prompt: "$I(0^+)$?", hint: "$V(0)=Q/C=4.0\\,\\mathrm{V}$.", expected: "$I=V/R=2.0\\,\\mathrm{mA}$, decaying." },
        { prompt: "$Q$ at 0.020 s?", hint: "$e^{-1}$.", expected: "$40/e \\approx 15\\,\\mu\\mathrm{C}$." },
      ],
    },
    independentItemIds: ["u11-rc-1", "u11-rc-2"],
    representationTask: {
      kind: "graph",
      prompt: "Sketch $V_C(t)$ and $I(t)$ for charging, labelled at $0$, $\\tau$, and $5\\tau$.",
      expected: "V_C rises to E, I falls to 0. At τ, V is 63% of E, I is 37% of E/R.",
    },
    retrievalItemId: "u11-rc-r",
    videoAlt: "A switch closes. At t=0 the capacitor is replaced by a wire in a ghost diagram; at infinity by a gap. Graphs of Q and I are drawn as complementary exponentials.",
  },
];
