import type { Lesson } from "@/lib/types";

const review = {
  reviewDate: "2026-09-10",
  authors: [
    { name: "Anannt physics author", role: "author" as const },
    { name: "Independent physics reviewer", role: "reviewer" as const },
  ],
  version: "1.0",
  status: "published" as const,
};

export const UNIT12_LESSONS: Lesson[] = [
  {
    id: "u12-force-on-charges",
    slug: "magnetic-force-on-charges",
    title: "Magnetic force on a moving charge",
    unit: 12,
    topics: ["12.1"],
    objectives: ["12.1.A"],
    capability: "Use $\\vec{F}=q\\vec{v}\\times\\vec{B}$, including negative $q$, and explain why $F$ cannot change speed.",
    prereqs: ["bridge-vectors"],
    minutes: [22, 32],
    ...review,
    investigationId: "magnetic-direction",
    prediction: {
      prompt: "An electron moves in the $+x$ direction through $\\vec{B}$ in the $+z$ direction. $\\vec{F}$ is in the",
      choices: [
        { id: "A", text: "$+y$ direction.", correct: true },
        { id: "B", text: "$-y$ direction (the direction of $\\vec{v}\\times\\vec{B}$ itself)." },
        { id: "C", text: "$+x$ direction, speeding the electron up." },
        { id: "D", text: "zero, because electrons do not feel magnetic fields." },
      ],
      explanation:
        "$\\hat{\\imath}\\times\\hat{k} = -\\hat{\\jmath}$, so $\\vec{v}\\times\\vec{B}$ is in the $-y$ direction. The electron’s negative charge reverses the force, so $\\vec{F}$ is in the $+y$ direction. A proton would feel $-y$. Magnetic force is perpendicular to $\\vec{v}$, so it cannot speed the electron up.",
    },
    explanation: {
      model: "$\\vec{F}=q\\vec{v}\\times\\vec{B}$. Magnetic force is perpendicular to $\\vec{v}$ and to $\\vec{B}$. It does no work, so it cannot change speed, only direction (in a purely magnetic field).",
      represent: "Draw $\\vec{v}$ and $\\vec{B}$. Use a right-hand rule for $\\vec{v}\\times\\vec{B}$, then reverse if $q<0$.",
      derive: "Magnitude $F=|q|vB\\sin\\theta$. Circular motion when $\\vec{v}\\perp\\vec{B}$: $r=mv/(|q|B)$.",
      check: "If $\\vec{v}\\parallel\\vec{B}$, $F=0$. Helical motion when there is a parallel component.",
      explain: "Applying the right-hand rule to $q\\vec{v}$ without reversing for electrons is the dominant error. Another is claiming the field does work because the path is curved.",
    },
    workedExample: {
      title: "Radius of a proton orbit",
      situation: "Proton, $v=3.0\\times 10^5\\,\\mathrm{m/s}$, perpendicular to $B=0.20\\,\\mathrm{T}$. Find $r$.",
      assumptions: ["Uniform $B$; no $E$; nonrelativistic."],
      derivation: "$r=mv/(qB)=(1.67\\mathrm{e}{-27})(3.0\\mathrm{e}5)/((1.60\\mathrm{e}{-19})(0.20))=1.57\\times 10^{-2}\\,\\mathrm{m}$.",
      units: "m.",
      interpretation: "A few centimetres. An electron at the same $v$ would have a radius smaller by $m_e/m_p$.",
      whyAlternativesFail: "Using $qE$ or $r=mvB$ without dividing.",
    },
    fadedExample: {
      situation: "Velocity selector: $E$ down, $B$ into the page, $v$ to the right, positive ion.",
      steps: [
        { prompt: "Direction of $q\\vec{E}$?", hint: "Positive charge.", expected: "Down." },
        { prompt: "Direction of $q\\vec{v}\\times\\vec{B}$?", hint: "Right-hand rule.", expected: "Up. Balance when $E=vB$." },
      ],
    },
    independentItemIds: ["u12-fq-1", "u12-fq-2"],
    retrievalItemId: "u12-fq-r",
    videoAlt: "A proton’s v and B are shown; F is perpendicular. The same v and B for an electron reverse F. A circle is labelled r = mv/qB.",
  },
  {
    id: "u12-force-on-currents",
    slug: "magnetic-force-on-currents",
    title: "Magnetic force on a current-carrying wire",
    unit: 12,
    topics: ["12.2"],
    objectives: ["12.2.A"],
    capability: "Use $\\vec{F}=I\\int d\\vec{\\ell}\\times\\vec{B}$ for a straight segment and discuss torque on a loop.",
    prereqs: ["u12-force-on-charges"],
    minutes: [20, 30],
    ...review,
    prediction: {
      prompt: "A wire along $+x$ carries $I$ in $+x$. $\\vec{B}$ is $+y$. $\\vec{F}$ on the wire is",
      choices: [
        { id: "A", text: "$+z$.", correct: true },
        { id: "B", text: "$-z$." },
        { id: "C", text: "along the wire." },
        { id: "D", text: "zero because a wire is electrically neutral." },
      ],
      explanation: "$d\\vec{\\ell}\\times\\vec{B}$ is $\\hat{\\imath}\\times\\hat{\\jmath}=\\hat{k}$. Neutrality of the wire does not cancel magnetic force: the current is moving charge.",
    },
    explanation: {
      model: "A current is many charges with drift. Summing $q\\vec{v}\\times\\vec{B}$ yields $I\\,d\\vec{\\ell}\\times\\vec{B}$.",
      represent: "$d\\vec{\\ell}$ in the conventional-current direction. For a closed loop in uniform $B$, net force is zero; torque need not be.",
      derive: "Straight length $L$ in uniform $B$: $F=ILB\\sin\\theta$.",
      check: "Newtons. Two parallel currents attract if they are in the same direction.",
      explain: "Using the electron-drift direction in $I\\,d\\ell$ without converting to conventional current doubles the sign error.",
    },
    workedExample: {
      title: "Force on a 12 cm segment",
      situation: "$I=5.0\\,\\mathrm{A}$, $L=0.12\\,\\mathrm{m}$, $B=0.40\\,\\mathrm{T}$ perpendicular. Find $F$.",
      assumptions: ["Uniform $B$; straight segment."],
      derivation: "$F=ILB=0.24\\,\\mathrm{N}$.",
      units: "N, perpendicular to both $I$ and $B$.",
      interpretation: "A modest laboratory force. Rails and bars in induction problems use this as the mechanical partner of Faraday’s law.",
      whyAlternativesFail: "$F=I B / L$ or omitting $\\sin\\theta$ when not perpendicular.",
    },
    fadedExample: {
      situation: "Rectangular loop, uniform $B$ in the plane of the loop.",
      steps: [
        { prompt: "Net force?", hint: "Uniform $B$, closed current.", expected: "Zero." },
        { prompt: "Torque?", hint: "$\\vec{\\mu}\\times\\vec{B}$.", expected: "May be nonzero; maximum when $\\vec{\\mu}\\perp\\vec{B}$." },
      ],
    },
    independentItemIds: ["u12-fi-1"],
    retrievalItemId: "u12-fi-r",
    videoAlt: "A wire with I and B; F is shown with the right-hand rule. Two parallel wires attract. A loop in uniform B has cancelling forces on opposite sides and a remaining torque.",
  },
  {
    id: "u12-biot-savart",
    slug: "biot-savart-law",
    title: "Biot–Savart: fields from current elements",
    unit: 12,
    topics: ["12.3"],
    objectives: ["12.3.A"],
    capability: "Write $d\\vec{B}$ for a current element and integrate a ring or a long straight wire.",
    prereqs: ["u12-force-on-currents", "bridge-integrals"],
    minutes: [24, 35],
    ...review,
    prediction: {
      prompt: "At the centre of a single circular loop of radius $R$ carrying $I$, $B$ is",
      choices: [
        { id: "A", text: "$\\mu_0 I /(2R)$, along the axis.", correct: true },
        { id: "B", text: "$\\mu_0 I /(2\\pi R)$, like a straight wire." },
        { id: "C", text: "zero by cancellation." },
        { id: "D", text: "$\\mu_0 I / R^2$." },
      ],
      explanation: "Every $d\\vec{B}$ at the centre is perpendicular to the plane and adds. The straight-wire formula is a different geometry.",
    },
    explanation: {
      model: "Biot–Savart: $d\\vec{B} = \\frac{\\mu_0}{4\\pi}\\frac{I d\\vec{\\ell}\\times\\hat{r}}{r^2}$. Steady currents; magnetostatics.",
      represent: "Draw $d\\vec{\\ell}$ and $\\vec{r}$ from the element to the field point. Only the perpendicular component survives.",
      derive: "Infinite straight wire: $B=\\mu_0 I /(2\\pi r)$. Loop centre: $B=\\mu_0 I /(2R)$. On a loop axis: $B= \\frac{\\mu_0 I R^2}{2(R^2+z^2)^{3/2}}$.",
      check: "Tesla. Direction by right-hand curl around the current.",
      explain: "Using Gauss’s law for $B$ as if monopoles existed, or using the electric Coulomb formula with $I$ in place of $q$.",
    },
    workedExample: {
      title: "Straight wire at 4.0 cm",
      situation: "$I=8.0\\,\\mathrm{A}$. Find $B$ at 4.0 cm from a long straight wire.",
      assumptions: ["Infinite wire idealisation."],
      derivation: "$B=\\mu_0 I /(2\\pi r)=4.0\\times 10^{-5}\\,\\mathrm{T}$.",
      units: "T, circling the wire.",
      interpretation: "About a gauss, comparable to Earth’s field. Laboratory coils are used when a larger controlled $B$ is needed.",
      whyAlternativesFail: "$\\mu_0 I /(2r)$ (the loop-centre formula) or $1/r^2$.",
    },
    fadedExample: {
      situation: "Two long parallel wires, currents same direction.",
      steps: [
        { prompt: "Direction of $B$ due to wire 1 at wire 2?", hint: "Right-hand curl.", expected: "Into or out of the page, perpendicular to the plane of the wires." },
        { prompt: "Force on wire 2?", hint: "$I\\,d\\ell\\times B$.", expected: "Toward wire 1 (attraction)." },
      ],
    },
    independentItemIds: ["u12-bs-1"],
    retrievalItemId: "u12-bs-r",
    videoAlt: "A current element dl and r-hat produce dB into the page. A circular loop’s elements all add at the centre. A long wire’s circles of B are drawn.",
  },
  {
    id: "u12-ampere",
    slug: "amperes-law",
    title: "Ampère’s law and useful Amperian paths",
    unit: 12,
    topics: ["12.4"],
    objectives: ["12.4.A"],
    capability: "Select a circle or rectangle, identify $I_{\\mathrm{enc}}$, and find $B$ for a long wire, solenoid, or sheet.",
    prereqs: ["u12-biot-savart", "u8-gauss-cylinder-plane"],
    minutes: [24, 35],
    ...review,
    prediction: {
      prompt: "Inside a long ideal solenoid, $B$ is",
      choices: [
        { id: "A", text: "$\\mu_0 n I$, along the axis, approximately uniform.", correct: true },
        { id: "B", text: "$\\mu_0 I /(2\\pi r)$, like a wire." },
        { id: "C", text: "zero, by analogy with $E$ inside a conductor." },
        { id: "D", text: "$\\mu_0 I /(2R)$ at every interior point." },
      ],
      explanation: "An Amperian rectangle with one side inside along the axis yields $B n L = \\mu_0 (n L I)$ so $B=\\mu_0 n I$. Outside, ideal $B\\approx 0$. Analogies with electrostatic conductors do not apply.",
    },
    explanation: {
      model: "$\\oint \\vec{B}\\cdot d\\vec{\\ell} = \\mu_0 I_{\\mathrm{enc}}$ (steady currents; Maxwell’s correction later/enrichment).",
      represent: "The path must respect symmetry so $B$ is constant and parallel (or zero) on segments.",
      derive: "Wire: circle, $B 2\\pi r = \\mu_0 I$. Solenoid: rectangle. Toroid: circle of radius $r$ in the doughnut: $B=\\mu_0 N I /(2\\pi r)$.",
      check: "Same infinite-wire result as Biot–Savart. A finite solenoid has fringing; the formula is an idealisation.",
      explain: "Drawing a circle around a solenoid’s exterior and setting $B=0$ because “no current is enclosed” forgets that the path’s interior includes the windings.",
    },
    workedExample: {
      title: "Solenoid field",
      situation: "$n=800\\,\\mathrm{m}^{-1}$, $I=1.2\\,\\mathrm{A}$. Find $B$ inside.",
      assumptions: ["Long solenoid; interior point far from ends."],
      derivation: "$B=\\mu_0 n I = 1.2\\times 10^{-3}\\,\\mathrm{T}$.",
      units: "T along the axis.",
      interpretation: "A millitesla: small compared with a strong neodymium magnet, large compared with Earth.",
      whyAlternativesFail: "Using $N$ without dividing by length, or $2\\pi$ in the denominator.",
    },
    fadedExample: {
      situation: "Coaxial cable, return current on the outer sheath.",
      steps: [
        { prompt: "$B$ outside the cable?", hint: "Net $I_{\\mathrm{enc}}=0$.", expected: "0, for a symmetric return." },
        { prompt: "Between core and sheath?", hint: "Only the core current.", expected: "$B=\\mu_0 I /(2\\pi r)$." },
      ],
    },
    independentItemIds: ["u12-amp-1", "u12-amp-2"],
    retrievalItemId: "u12-amp-r",
    videoAlt: "An Amperian circle around a wire; B is tangent. A rectangle through a solenoid wall; interior B is uniform, exterior ~0. A coaxial cable shows B=0 outside.",
  },
];

export const UNIT13_LESSONS: Lesson[] = [
  {
    id: "u13-magnetic-flux",
    slug: "magnetic-flux",
    title: "Magnetic flux and orientation",
    unit: 13,
    topics: ["13.1"],
    objectives: ["13.1.A"],
    capability: "Compute $\\Phi_B=\\int \\vec{B}\\cdot d\\vec{A}$ and separate flux from the rate of change of flux.",
    prereqs: ["u8-flux-misconception", "u12-ampere"],
    minutes: [18, 26],
    ...review,
    investigationId: "induction",
    prediction: {
      prompt: "A loop’s area is constant and $\\vec{B}$ is constant. Flux can still change if",
      choices: [
        { id: "A", text: "the loop translates in a uniform field without rotating." },
        { id: "B", text: "the loop rotates so that $\\theta$ between $\\vec{B}$ and the normal changes.", correct: true },
        { id: "C", text: "the current in a distant fixed magnet is unchanged and geometry is frozen." },
        { id: "D", text: "flux cannot change unless $B$ changes." },
      ],
      explanation: "$\\Phi=BA\\cos\\theta$. Any of $B$, $A$, or $\\theta$ can change $\\Phi$. Translating a loop in a truly uniform $B$ without rotation does not change $\\Phi$.",
    },
    explanation: {
      model: "Flux is a scalar (signed) for a chosen normal. It is not emf and not current.",
      represent: "Choose a normal with a right-hand rule tied to a loop sense you will use for emf later.",
      derive: "Uniform $B$, flat loop: $\\Phi=BA\\cos\\theta$. $N$ turns: $N\\Phi$.",
      check: "Weber = T·m². Reversing the normal flips $\\Phi$.",
      explain: "A large flux with $d\\Phi/dt=0$ produces no emf. A small flux changing quickly can produce a large emf.",
    },
    workedExample: {
      title: "Tilted loop",
      situation: "$B=0.35\\,\\mathrm{T}$, $A=0.040\\,\\mathrm{m}^2$, $\\theta=60^\\circ$ to the normal. Find $\\Phi$.",
      assumptions: ["Uniform $B$; single turn."],
      derivation: "$\\Phi=0.35\\times 0.040\\times 0.50=7.0\\times 10^{-3}\\,\\mathrm{Wb}$.",
      units: "Wb.",
      interpretation: "If this loop later spins, $\\theta(t)$ drives Faraday’s law.",
      whyAlternativesFail: "$\\sin 60^\\circ$, or using $B/A$.",
    },
    fadedExample: {
      situation: "Loop sliding out of a region of confined $B$.",
      steps: [
        { prompt: "What is changing?", hint: "Effective area in the field.", expected: "The area still in $B$, so $\\Phi=B\\,x\\,w$ if $B$ is uniform in a rectangular region." },
        { prompt: "Is $B$ at a point on the moving bar necessarily changing?", hint: "Local vs flux.", expected: "Not necessarily. Flux change can come from area leaving the region." },
      ],
    },
    independentItemIds: ["u13-flux-1"],
    retrievalItemId: "u13-flux-r",
    videoAlt: "A loop tilts in a uniform B; Φ = BA cosθ is plotted. A second loop slides out of a B-field region; the enclosed flux rectangle shrinks.",
  },
  {
    id: "u13-faraday",
    slug: "faradays-law",
    title: "Faraday’s law",
    unit: 13,
    topics: ["13.2"],
    objectives: ["13.2.A"],
    capability: "Compute $\\mathcal{E}=-d\\Phi_B/dt$ from a stated $\\Phi(t)$ or from motional $B\\ell v$.",
    prereqs: ["u13-magnetic-flux", "bridge-derivatives"],
    minutes: [22, 32],
    ...review,
    investigationId: "induction",
    prediction: {
      prompt: "$\\Phi_B(t)=0.012 t$ (SI) through a 5-turn coil. $|\\mathcal{E}|$ is",
      choices: [
        { id: "A", text: "0.012 V." },
        { id: "B", text: "0.060 V.", correct: true },
        { id: "C", text: "0.012 t V." },
        { id: "D", text: "zero because $\\Phi$ is linear, hence “steady.”" },
      ],
      explanation: "$d\\Phi/dt=0.012\\,\\mathrm{Wb/s}$ per turn. Five turns: $0.060\\,\\mathrm{V}$. A linear flux is a constant emf, not zero emf.",
    },
    explanation: {
      model: "A changing magnetic flux through a circuit is associated with an electric field that is not conservative around the loop, or equivalently with an emf $\\mathcal{E}=-N d\\Phi_B/dt$.",
      represent: "Write $\\Phi(t)$ with a stated normal. Differentiate. The minus is Lenz’s law.",
      derive: "Motional special case: rod of length $\\ell$ sliding at $v$ on rails in perpendicular $B$: $\\mathcal{E}=B\\ell v$.",
      check: "Volts. If $\\Phi$ is constant, $\\mathcal{E}=0$ even if $B\\neq 0$.",
      explain: "Using $\\mathcal{E}=\\Phi/t$ as an average can be an estimate but is not the instantaneous derivative. Omitting $N$ for a coil is common.",
    },
    workedExample: {
      title: "Sliding bar",
      situation: "$B=0.50\\,\\mathrm{T}$, $\\ell=0.20\\,\\mathrm{m}$, $v=3.0\\,\\mathrm{m/s}$ perpendicular. Find $\\mathcal{E}$.",
      assumptions: ["Uniform $B$; rails resistanceless except a load elsewhere; $v$ constant."],
      derivation: "$\\mathcal{E}=B\\ell v=0.30\\,\\mathrm{V}$.",
      units: "V.",
      interpretation: "Charges in the bar feel $q v B$, separating until $qE$ balances; $E\\ell=B\\ell v$.",
      whyAlternativesFail: "$B v /\\ell$ or using area instead of $\\ell v$ without $dA/dt=\\ell v$.",
    },
    fadedExample: {
      situation: "$B(t)=0.40 t^2$ through a 25-turn loop of area 0.010 m², $\\theta=0$.",
      steps: [
        { prompt: "$\\Phi$ one turn?", hint: "$BA$.", expected: "$0.0040 t^2$ Wb." },
        { prompt: "$\\mathcal{E}(t)$?", hint: "$-N d\\Phi/dt$.", expected: "$-25\\times 0.0080 t = -0.20 t$ V." },
      ],
    },
    independentItemIds: ["u13-far-1", "u13-far-2"],
    retrievalItemId: "u13-far-r",
    videoAlt: "A Φ(t) graph with a constant slope is shown; emf is a horizontal line. A sliding bar’s growing rectangle of flux is animated (or stepped, in reduced-motion mode).",
  },
  {
    id: "u13-lenz",
    slug: "lenz-law-and-energy",
    title: "Lenz’s law, direction, and energy accounting",
    unit: 13,
    topics: ["13.3"],
    objectives: ["13.3.A"],
    capability: "Determine induced-current direction and account for the mechanical power $F v = I^2 R$.",
    prereqs: ["u13-faraday"],
    minutes: [22, 32],
    ...review,
    investigationId: "induction",
    prediction: {
      prompt: "A loop faces an increasing $\\vec{B}$ out of the page. The induced current (as seen by you) is",
      choices: [
        { id: "A", text: "clockwise, to make $B$ into the page.", correct: true },
        { id: "B", text: "counterclockwise, to add more $B$ out of the page." },
        { id: "C", text: "zero, because the loop is not moving." },
        { id: "D", text: "alternating at random." },
      ],
      explanation: "The induced current opposes the change: increasing out-of-page flux is opposed by into-page induced $B$, which is clockwise by the right-hand rule (thumb into page, fingers clockwise).",
    },
    explanation: {
      model: "Lenz: the induced current’s field opposes the change in flux, not necessarily the field itself. Energy: if a magnet approaches a loop, repulsion (or attraction when receding) makes you do mechanical work that appears as $I^2 R$.",
      represent: "State $\\Phi$ sign, whether $|\\Phi|$ is increasing, then the induced $B$, then the current.",
      derive: "For a sliding bar, magnetic force $F=I\\ell B$ opposes the motion if the circuit dissipates. $P_{\\mathrm{mech}}=F v = I^2 R$.",
      check: "If your induced current would increase the change, the direction is wrong.",
      explain: "Opposing $B$ rather than $dB/dt$ fails when $B$ is decreasing: the induced current then tries to maintain $B$.",
    },
    workedExample: {
      title: "Power in a sliding bar",
      situation: "$B=0.40\\,\\mathrm{T}$, $\\ell=0.25\\,\\mathrm{m}$, $v=2.0\\,\\mathrm{m/s}$, $R=0.50\\,\\Omega$. Find $I$, $F$, and power.",
      assumptions: ["Rails ideal; only $R$ in the circuit; $v$ held constant by an agent."],
      derivation: "$\\mathcal{E}=B\\ell v=0.20\\,\\mathrm{V}$, $I=0.40\\,\\mathrm{A}$, $F=I\\ell B=0.040\\,\\mathrm{N}$ opposing $v$. $P=Fv=0.080\\,\\mathrm{W}=I^2 R$.",
      units: "A, N, W.",
      interpretation: "The agent pulling the bar at constant speed does 0.080 W, exactly the joule heating.",
      whyAlternativesFail: "Claiming the magnetic force does work (it is perpendicular to the charges’ drift along the bar, and for the bar as a whole the magnetic force is opposite $v$ while an agent does the work).",
    },
    fadedExample: {
      situation: "A superconducting loop ($R=0$) in a changing $B$.",
      steps: [
        { prompt: "Can $\\Phi$ through the loop change?", hint: "Perfect screening in the simple model.", expected: "Induced current runs so that $\\Phi$ stays at its initial value (idealisation). $I$ can be large; $R=0$ means no joule heating but the current persists." },
      ],
    },
    independentItemIds: ["u13-lenz-1", "u13-lenz-2"],
    retrievalItemId: "u13-lenz-r",
    videoAlt: "An approaching magnet faces a loop; induced current creates a like pole. A sliding bar has F opposite v; a power equality Fv = I²R is boxed.",
  },
  {
    id: "u13-inductance",
    slug: "inductance-and-energy",
    title: "Self-inductance and magnetic energy",
    unit: 13,
    topics: ["13.4"],
    objectives: ["13.4.A"],
    capability: "Use $\\mathcal{E}_L = -L dI/dt$ and $U=\\tfrac12 L I^2$.",
    prereqs: ["u13-lenz"],
    minutes: [20, 30],
    ...review,
    investigationId: "inductor",
    prediction: {
      prompt: "An inductor with constant current $I$ has induced emf",
      choices: [
        { id: "A", text: "$LI$." },
        { id: "B", text: "zero, because $dI/dt=0$.", correct: true },
        { id: "C", text: "infinite." },
        { id: "D", text: "$\\tfrac12 LI^2$ volts." },
      ],
      explanation: "Self-inductance emf exists when current is changing. Energy $\\tfrac12 LI^2$ can still be stored while $dI/dt=0$.",
    },
    explanation: {
      model: "$N\\Phi_B = LI$ defines $L$ for a coil in the linear regime. Then $\\mathcal{E}=-L dI/dt$.",
      represent: "The inductor symbol opposes changes in its current. In DC steady state it is a wire (ideal $L$).",
      derive: "Solenoid: $L=\\mu_0 n^2 A \\ell$. Energy $U=\\tfrac12 L I^2$, also $\\int (B^2/2\\mu_0)\\,dV$ in vacuum.",
      check: "Henrys. $L$ is geometry (and core $\\mu$), not a function of $I$ in the linear model.",
      explain: "Treating an inductor as an infinite resistance, or using capacitor energy formulae on $L$, mixes elements.",
    },
    workedExample: {
      title: "Solenoid $L$",
      situation: "$n=2000\\,\\mathrm{m}^{-1}$, $A=4.0\\times 10^{-4}\\,\\mathrm{m}^2$, length $0.25\\,\\mathrm{m}$. Find $L$ and $U$ at 0.80 A.",
      assumptions: ["Long solenoid; air core."],
      derivation: "$L=\\mu_0 n^2 A \\ell = 5.0\\times 10^{-4}\\,\\mathrm{H}$. $U=\\tfrac12 LI^2=1.6\\times 10^{-4}\\,\\mathrm{J}$.",
      units: "H and J.",
      interpretation: "A 0.5 mH air solenoid. Iron cores increase $L$ (with saturation caveats).",
      whyAlternativesFail: "Omitting $n^2$ (using $n$) or using $LI$ as energy.",
    },
    fadedExample: {
      situation: "Current through $L=0.20\\,\\mathrm{H}$ falls at 40 A/s.",
      steps: [
        { prompt: "$|\\mathcal{E}|$?", hint: "$L|dI/dt|$.", expected: "8.0 V." },
        { prompt: "Polarity?", hint: "Oppose the decrease.", expected: "The inductor acts to keep current going in the original direction (like a brief battery)." },
      ],
    },
    independentItemIds: ["u13-ind-1"],
    retrievalItemId: "u13-ind-r",
    videoAlt: "A coil’s flux is proportional to I; L is the slope. When I changes, a back emf appears. An energy bar ½LI² grows as current grows.",
  },
  {
    id: "u13-rl",
    slug: "rl-transients",
    title: "RL transients",
    unit: 13,
    topics: ["13.5"],
    objectives: ["13.5.A"],
    capability: "Write $I(t)$ for growth and decay, with $\\tau=L/R$ and correct $t=0^+$ behaviour.",
    prereqs: ["u13-inductance", "u11-rc-transients"],
    minutes: [24, 35],
    ...review,
    investigationId: "inductor",
    prediction: {
      prompt: "Just after a switch connects a battery to a series RL that had $I=0$, the inductor behaves as",
      choices: [
        { id: "A", text: "a short, $I=\\mathcal{E}/R$ immediately." },
        { id: "B", text: "an open, $I=0^+$, all voltage across $L$.", correct: true },
        { id: "C", text: "a capacitor." },
        { id: "D", text: "a resistor $L$." },
      ],
      explanation: "Current in an inductor cannot jump. At $t=0^+$, $I=0$, so $IR=0$ and $\\mathcal{E}=L dI/dt$. Long after, $dI/dt=0$ and $I=\\mathcal{E}/R$. Dual to the capacitor.",
    },
    explanation: {
      model: "Governing equation: $\\mathcal{E}=IR + L dI/dt$ for a series charging RL.",
      represent: "Redraw $t=0^+$ (L open if I was 0) and $t=\\infty$ (L short).",
      derive: "Growth: $I=(\\mathcal{E}/R)(1-e^{-t/\\tau})$, $\\tau=L/R$. Decay: $I=I_0 e^{-t/\\tau}$.",
      check: "At $t=\\tau$, growth current is 63% of $I_\\infty$. $L/R$ is seconds.",
      explain: "Using RC formulae with $L$ in place of $C$ without changing the time constant to $L/R$ is a common mix-up. After two failed repairs, show the dual table: C vs L at $t=0^+$ and $\\infty$.",
    },
    workedExample: {
      title: "Time to 90% of $I_\\infty$",
      situation: "$L=0.40\\,\\mathrm{H}$, $R=20\\,\\Omega$, $\\mathcal{E}=8.0\\,\\mathrm{V}$. Time to reach $0.90 I_\\infty$.",
      assumptions: ["Series RL; $I(0)=0$."],
      derivation: "$\\tau=0.020\\,\\mathrm{s}$. $1-e^{-t/\\tau}=0.90$, $t=\\tau\\ln 10=0.046\\,\\mathrm{s}$. $I_\\infty=0.40\\,\\mathrm{A}$.",
      units: "s and A.",
      interpretation: "A bit over two time constants, not five (five would be ~99%).",
      whyAlternativesFail: "$t=0.90\\tau$, or $\\tau=RC$ with a fabricated $C$.",
    },
    fadedExample: {
      situation: "Decay from 0.40 A through 20 Ω and 0.40 H (battery shorted out, L and R remain).",
      steps: [
        { prompt: "$I(t)$?", hint: "Exponential decay.", expected: "$0.40 e^{-t/0.020}\\,\\mathrm{A}$." },
        { prompt: "Energy at $t=0$ vs later?", hint: "$\\tfrac12 LI^2$.", expected: "Stored energy is dissipated in $R$ as the current falls." },
      ],
    },
    independentItemIds: ["u13-rl-1", "u13-rl-2"],
    retrievalItemId: "u13-rl-r",
    videoAlt: "Dual table: capacitor short at 0 vs inductor open at 0. I(t) for RL growth is drawn next to Q(t) for RC charging to show the analogy.",
  },
  {
    id: "u13-lc",
    slug: "lc-oscillations",
    title: "LC oscillations and energy exchange",
    unit: 13,
    topics: ["13.6"],
    objectives: ["13.6.A"],
    capability: "Use $\\omega=1/\\sqrt{LC}$, relate $Q(t)$ and $I(t)$, and track energy between $C$ and $L$.",
    prereqs: ["u13-rl"],
    minutes: [24, 35],
    ...review,
    investigationId: "inductor",
    prediction: {
      prompt: "In an ideal LC circuit, when $Q=0$ on the capacitor,",
      choices: [
        { id: "A", text: "energy is zero and the motion stops." },
        { id: "B", text: "$|I|$ is maximum and the energy is entirely magnetic.", correct: true },
        { id: "C", text: "$|I|$ is zero." },
        { id: "D", text: "$V_C$ is maximum." },
      ],
      explanation: "Charge and current are a quarter cycle apart. $Q=0$ is when current has emptied the capacitor; $U_B=\\tfrac12 LI^2$ is max. $V_C=Q/C=0$ then.",
    },
    explanation: {
      model: "Ideal LC: $L\\ddot Q + Q/C = 0$. Simple harmonic, $\\omega=1/\\sqrt{LC}$. Resistance is an enrichment (damping) unless an FRQ includes $R$.",
      represent: "Energy pie: $U_E=Q^2/(2C)$, $U_B=\\tfrac12 L I^2$, sum constant.",
      derive: "$Q=Q_{\\mathrm{m}}\\cos(\\omega t+\\phi)$, $I=-\\omega Q_{\\mathrm{m}}\\sin(\\omega t+\\phi)$. Period $T=2\\pi\\sqrt{LC}$.",
      check: "At $t=0$, if $Q=Q_m$ and $I=0$, all energy is electric. A quarter period later, all magnetic.",
      explain: "Using $\\omega=\\sqrt{LC}$ without the reciprocal, or treating LC like RC exponentials, misses the oscillation.",
    },
    workedExample: {
      title: "Period and peak current",
      situation: "$C=4.0\\,\\mu\\mathrm{F}$, $L=0.25\\,\\mathrm{H}$, $Q_m=8.0\\,\\mu\\mathrm{C}$, start from rest ($I=0$).",
      assumptions: ["Ideal LC; $Q(0)=Q_m$."],
      derivation: "$\\omega=1/\\sqrt{LC}=1000\\,\\mathrm{rad/s}$, $T=6.3\\,\\mathrm{ms}$. $I_m=\\omega Q_m=8.0\\,\\mathrm{mA}$. $U=Q_m^2/(2C)=8.0\\times 10^{-6}\\,\\mathrm{J}$.",
      units: "rad/s, s, A, J.",
      interpretation: "A millisecond-scale oscillation. Real circuits damp unless driven.",
      whyAlternativesFail: "$T=RC$ or $I_m=Q_m/C$ (that is $V$, not $I$).",
    },
    fadedExample: {
      situation: "Energy half electric, half magnetic.",
      steps: [
        { prompt: "What is $|Q|/Q_m$?", hint: "$U_E=U/2$ means $Q^2 = Q_m^2 / 2$.", expected: "$1/\\sqrt{2}$." },
        { prompt: "Is this at $T/8$?", hint: "$\\cos^2(\\omega t)=1/2$." , expected: "Yes, from $Q=Q_m\\cos\\omega t$, at $\\omega t=\\pi/4$, which is $T/8$." },
      ],
    },
    independentItemIds: ["u13-lc-1"],
    representationTask: {
      kind: "graph",
      prompt: "On one time axis, sketch $Q(t)$ and $I(t)$ for one period, starting at $Q=Q_m$. Mark when energy is all in $L$.",
      expected: "Q cosine, I negative sine. All magnetic at T/4 and 3T/4.",
    },
    retrievalItemId: "u13-lc-r",
    videoAlt: "Energy sloshes from capacitor bars to inductor bars. Q and I graphs are a quarter cycle apart. ω = 1/√(LC) is boxed.",
  },
];
