import type { Lesson } from "@/lib/types";

const review = {
  reviewDate: "2026-09-10",
  authors: [
    { name: "Anannt physics author", role: "author" as const },
    { name: "Independent physics reviewer", role: "reviewer" as const },
  ],
  version: "1.0",
  status: "published" as const,
};

export const UNIT9_LESSONS: Lesson[] = [
  {
    id: "u9-potential-energy",
    slug: "electric-potential-energy",
    title: "Electric potential energy of a charge system",
    unit: 9,
    topics: ["9.1"],
    objectives: ["9.1.A"],
    capability: "Write $U$ for point charges with a stated reference and apply energy conservation.",
    prereqs: ["bridge-energy", "u8-coulomb-vectors"],
    minutes: [22, 32],
    ...review,
    prediction: {
      prompt: "Two protons are released from rest a distance $r_0$ apart. As they separate, $U$ of the pair",
      choices: [
        { id: "A", text: "increases because kinetic energy appears." },
        { id: "B", text: "decreases, and $K$ of the two-proton system increases by the same amount.", correct: true },
        { id: "C", text: "is constant; electrostatic forces do no work." },
        { id: "D", text: "cannot be defined for two particles." },
      ],
      explanation: "Like charges have $U = k e^2/r$ (with $U(\\infty)=0$), which falls as $r$ grows. The lost $U$ becomes $K$. Electrostatic forces are conservative and do work.",
    },
    explanation: {
      model: "Potential energy belongs to a system. For two point charges $U = k q_1 q_2 / r$ with $U(\\infty)=0$. For more charges, sum every pair once.",
      represent: "State the reference. Draw initial and final configurations. Do not assign $U$ to “a charge” without a partner and a reference.",
      derive: "$\\Delta U = U_f - U_i$. If only electrostatic forces act, $\\Delta K + \\Delta U = 0$.",
      check: "Opposite charges have negative $U$ relative to infinity. That does not mean energy is “less than nothing”; it means you must do positive work to separate them to infinity.",
      explain: "Using $U = qEd$ without asking whether $E$ is uniform, or mixing $U$ with $V$, are the usual substitutions.",
    },
    workedExample: {
      title: "Three charges on a line",
      situation: "$+q$ at 0, $+q$ at $2a$, $-q$ at $a$. Find $U$ of the system relative to infinite separation.",
      assumptions: ["Point charges; $U(\\infty)=0$."],
      derivation: "Pairs: $(+q,+q)$ at $2a$ contributes $kq^2/(2a)$; two $(+q,-q)$ pairs at $a$ contribute $-kq^2/a$ each. $U = kq^2/(2a) - 2kq^2/a = -3kq^2/(2a)$.",
      units: "Joules.",
      interpretation: "The system is bound relative to infinity: you would have to add energy to move all three to infinite separation.",
      whyAlternativesFail: "Counting only nearest neighbours, or using $3$ pairs all as $kq^2/a$.",
    },
    fadedExample: {
      situation: "A charge $q_0$ is moved at constant speed in an electrostatic field.",
      steps: [
        { prompt: "Is $\\Delta K$ zero?", hint: "Constant speed.", expected: "Yes. An external agent cancelled the electrical force." },
        { prompt: "Who did work?", hint: "Both the field and the agent.", expected: "$W_{\\mathrm{field}} = -\\Delta U$. The agent does $+\\Delta U$ if speed is held constant." },
      ],
    },
    independentItemIds: ["u9-u-1"],
    retrievalItemId: "u9-u-r",
    videoAlt: "Two protons move apart. A bar chart shows U falling and K rising. A formula U = ke²/r is plotted.",
  },
  {
    id: "u9-potential",
    slug: "electric-potential",
    title: "Electric potential and potential difference",
    unit: 9,
    topics: ["9.2"],
    objectives: ["9.2.A"],
    capability: "Compute $V$ from point charges and $\\Delta V$ along a path in a known field.",
    prereqs: ["u9-potential-energy"],
    minutes: [22, 32],
    ...review,
    investigationId: "potential-graph",
    prediction: {
      prompt: "Potential $V$ is a",
      choices: [
        { id: "A", text: "vector pointing from high to low $V$." },
        { id: "B", text: "scalar; $V = kq/r$ for a point charge with $V(\\infty)=0$.", correct: true },
        { id: "C", text: "another name for $\\vec{E}$." },
        { id: "D", text: "defined only inside conductors." },
      ],
      explanation: "$V$ is a scalar field. Superposition of $V$ is algebraic, not vector. $\\vec{E}$ is minus the gradient of $V$.",
    },
    explanation: {
      model: "$V(\\vec{r}) = U(\\vec{r})/q_0$ for a test charge, independent of $q_0$. Difference $\\Delta V = V_b - V_a = -\\int_a^b \\vec{E}\\cdot d\\vec{\\ell}$.",
      represent: "Always state $V=0$. Infinity is common for localised charges; a plate is common for capacitors.",
      derive: "Point charge: $V=kq/r$. Superposition: $V=\\sum kq_i/r_i$. Uniform $E$: $\\Delta V = -E d$ along a field line of length $d$.",
      check: "Volts. Moving along an equipotential gives $\\Delta V=0$ even if $E\\neq 0$ (path perpendicular to $E$).",
      explain: "High potential is not \u201cmore field.\u201d A region can have high $V$ and small $E$ if $V$ is flat.",
    },
    workedExample: {
      title: "Potential of two charges",
      situation: "$+4.0\\,\\mathrm{nC}$ at $x=0$, $-4.0\\,\\mathrm{nC}$ at $x=0.20\\,\\mathrm{m}$. Find $V$ at the midpoint.",
      assumptions: ["$V(\\infty)=0$; vacuum."],
      derivation: "$V = k(4\\mathrm{e}{-9})/0.10 + k(-4\\mathrm{e}{-9})/0.10 = 0$.",
      units: "Volts.",
      interpretation: "The midpoint of a dipole has $V=0$ but $E\\neq 0$ (field from $+$ to $-$). Zero potential is not zero field.",
      whyAlternativesFail: "Adding magnitudes of $V$ as if signs did not matter, or concluding $E=0$ because $V=0$.",
    },
    fadedExample: {
      situation: "Uniform $E=200\\,\\mathrm{N/C}$ in $+x$. Point A at $x=0$, B at $x=0.15\\,\\mathrm{m}$.",
      steps: [
        { prompt: "Find $V_B-V_A$.", hint: "$\\Delta V=-\\int E_x dx$.", expected: "$-30\\,\\mathrm{V}$." },
        { prompt: "Which point is at higher potential?", hint: "Potential drops along $E$.", expected: "A." },
      ],
    },
    independentItemIds: ["u9-v-1", "u9-v-2"],
    retrievalItemId: "u9-v-r",
    videoAlt: "Scalar numbers for V are written at points around two charges. At a dipole midpoint V=0 while a field arrow remains.",
  },
  {
    id: "u9-zero-v-vs-zero-e",
    slug: "zero-potential-is-not-zero-field",
    title: "Zero potential is not zero field",
    unit: 9,
    topics: ["9.2"],
    objectives: ["9.2.B"],
    capability: "Give examples where $V=0$ but $E\\neq 0$, and where $E=0$ but $V\\neq 0$.",
    prereqs: ["u9-potential"],
    minutes: [20, 30],
    ...review,
    investigationId: "potential-graph",
    prediction: {
      prompt: "At the centre of a uniformly charged ring, which is true ($V(\\infty)=0$)?",
      choices: [
        { id: "A", text: "$E=0$ and $V=0$." },
        { id: "B", text: "$E=0$ and $V = kQ/R \\neq 0$.", correct: true },
        { id: "C", text: "$E\\neq 0$ and $V=0$." },
        { id: "D", text: "Neither $E$ nor $V$ can be defined on the axis." },
      ],
      explanation: "Field cancels by symmetry. Every $dq$ is at distance $R$, so $V=kQ/R$.",
    },
    explanation: {
      model: "$E$ is local slope of $V$. A function can be zero with nonzero slope (dipole midpoint if $V(\\infty)=0$) or nonzero with zero slope (ring centre).",
      represent: "Sketch $V(x)$ and $E_x=-dV/dx$ on the same axis.",
      derive: "If $V$ is even about a point, $E_x$ is odd and vanishes there. The value of $V$ itself is set by the reference.",
      check: "Changing the reference by a constant never changes $E$, and never changes $\\Delta V$.",
      explain: "Setting $V=0$ at a point does not force $E=0$ there. It is a bookkeeping choice unless that point is actually an equipotential region (conductor).",
    },
    workedExample: {
      title: "Dipole perpendicular bisector",
      situation: "Show $V=0$ everywhere on the perpendicular bisector of $\\pm q$ separated by $2a$ (with $V(\\infty)=0$), while $E\\neq 0$.",
      assumptions: ["Equal and opposite point charges."],
      derivation: "Each point on the bisector is equidistant from $+q$ and $-q$, so $V_+ + V_- = 0$. Field vectors have cancelling components along the dipole axis? On the perpendicular bisector they add antiparallel to $\\vec{p}$.",
      units: "V and N/C.",
      interpretation: "The entire bisector plane is an equipotential (the $V=0$ plane) without being a region of zero field.",
      whyAlternativesFail: "Equipotential does not mean $E=0$; it means $\\vec{E}$ is perpendicular to the surface.",
    },
    fadedExample: {
      situation: "Inside an empty cavity of a conductor in equilibrium, with no charge in the cavity.",
      steps: [
        { prompt: "$E$ in the cavity?", hint: "Unique solution; Faraday cage.", expected: "$E=0$ if no cavity charge (for empty cavity in electrostatics of this type)." },
        { prompt: "$V$ in the cavity versus the conductor?", hint: "$E=0$ implies $V$ constant.", expected: "$V$ is constant and equal to the conductor\u2019s potential, which need not be zero." },
      ],
    },
    independentItemIds: ["u9-zero-1"],
    representationTask: {
      kind: "graph",
      prompt: "Sketch $V(x)$ and $E_x(x)$ for two charges $+q$ at $x=-a$ and $+q$ at $x=+a$. Mark the midpoint.",
      expected: "V has a local minimum or maximum at 0 (actually a local min for +q pair along the line between? Between two positives V has a minimum at centre). E_x = 0 at centre, V \u2260 0.",
    },
    retrievalItemId: "u9-zero-r",
    videoAlt: "A V(x) curve with a flat peak: slope zero, V not zero. A separate dipole midpoint: V=0, slope nonzero.",
  },
  {
    id: "u9-e-from-v",
    slug: "field-from-potential",
    title: "Obtaining $\\vec{E}$ from $V$",
    unit: 9,
    topics: ["9.3"],
    objectives: ["9.3.A"],
    capability: "Use $E_x = -dV/dx$ and the idea of $\\vec{E}=-\\nabla V$, including graph reading.",
    prereqs: ["u9-zero-v-vs-zero-e", "bridge-graphs"],
    minutes: [22, 32],
    ...review,
    investigationId: "potential-graph",
    prediction: {
      prompt: "If $V(x)$ decreases in the $+x$ direction, $E_x$ is",
      choices: [
        { id: "A", text: "negative; the field points to $-x$." },
        { id: "B", text: "positive; the field points to $+x$.", correct: true },
        { id: "C", text: "zero, because $V$ is a scalar." },
        { id: "D", text: "indeterminate without $U$." },
      ],
      explanation: "$E_x = -dV/dx$. If $dV/dx \u003c 0$, $E_x \u003e 0$. Field points from high to low potential.",
    },
    explanation: {
      model: "The field is the downhill direction of potential, with magnitude the steepest slope.",
      represent: "Given $V(x,y)$ or a graph, mark increasing $V$ as \u201cuphill.\u201d",
      derive: "In 1-D, $E_x=-dV/dx$. In 3-D, $E_x=-\\partial V/\\partial x$, etc.",
      check: "If $V$ is in volts and $x$ in metres, $E$ is V/m. Sign: a proton released from rest moves toward lower $V$.",
      explain: "Reading $E$ as the value of $V$, or as $+dV/dx$, are the two most common graph errors.",
    },
    workedExample: {
      title: "From a polynomial $V$",
      situation: "$V(x)= 4.0 x^2 - 2.0 x$ (SI) along a line. Find $E_x$ at $x=0.50\\,\\mathrm{m}$.",
      assumptions: ["This $V$ is given only along x; we seek $E_x$."],
      derivation: "$E_x = -8.0 x + 2.0$, so at $0.50\\,\\mathrm{m}$, $E_x = -2.0\\,\\mathrm{N/C}$.",
      units: "N/C.",
      interpretation: "The field points toward $-x$ at that point even though $V(0.50)=0$ exactly? $V(0.5)=4(0.25)-1=0$. Again $V=0$ with $E\\neq 0$.",
      whyAlternativesFail: "Evaluating $V/x$ or using $+dV/dx$.",
    },
    fadedExample: {
      situation: "A graph of $V$ versus $x$ is a straight line from $(0, 12\\,\\mathrm{V})$ to $(0.04\\,\\mathrm{m}, 0)$.",
      steps: [
        { prompt: "Is $E_x$ uniform?", hint: "Constant slope.", expected: "Yes." },
        { prompt: "Value and sign?", hint: "$-\\Delta V/\\Delta x$.", expected: "$E_x = - (0-12)/0.04 = +300\\,\\mathrm{N/C}$." },
      ],
    },
    independentItemIds: ["u9-ev-1", "u9-ev-2"],
    retrievalItemId: "u9-ev-r",
    videoAlt: "A V(x) graph is shown with a tangent. The slope is negative; E is drawn in the +x direction. A proton is released and moves downhill in V.",
  },
  {
    id: "u9-energy-conservation",
    slug: "energy-conservation-with-potential",
    title: "Energy conservation with $qV$",
    unit: 9,
    topics: ["9.3"],
    objectives: ["9.3.B"],
    capability: "Use $\\tfrac12 mv^2 + qV$ conservation for electrostatics and state when it fails.",
    prereqs: ["u9-e-from-v", "bridge-energy"],
    minutes: [20, 30],
    ...review,
    prediction: {
      prompt: "An electron is released from rest at a point where $V= +80\\,\\mathrm{V}$ and moves to $V=0$. Its kinetic energy gained is",
      choices: [
        { id: "A", text: "$80\\,\\mathrm{J}$." },
        { id: "B", text: "$80\\,\\mathrm{eV}$, about $1.3\\times 10^{-17}\\,\\mathrm{J}$.", correct: true },
        { id: "C", text: "zero; electrons go to high potential." },
        { id: "D", text: "negative, so the speed is imaginary." },
      ],
      explanation: "$q$ is negative, so $U=qV$ is lower at $V=0$ than at $+80\\,\\mathrm{V}$. $\\Delta K = -q\\Delta V = e(80\\,\\mathrm{V})=80\\,\\mathrm{eV}$. Electrons are released from rest toward higher $V$ if they start at lower $U$, i.e. they go to higher potential.",
    },
    explanation: {
      model: "If electrostatic forces are the only forces doing work, $K+qV$ is constant (same $V$ reference throughout).",
      represent: "Table of $K$ and $qV$ at two points. Watch the sign of $q$.",
      derive: "$\\tfrac12 m v_f^2 - \\tfrac12 m v_i^2 = q(V_i - V_f)$.",
      check: "An electron volt is a unit of energy, not potential. Never set $\\tfrac12 mv^2 = V$.",
      explain: "Radiation, time-varying magnetic fields, and non-electrostatic battery internals are outside this conservation statement.",
    },
    workedExample: {
      title: "Proton through 250 V",
      situation: "A proton ($1.67\\times 10^{-27}\\,\\mathrm{kg}$) accelerates from rest through 250 V. Find $v$.",
      assumptions: ["Vacuum; electrostatic; rest at the high-V plate."],
      derivation: "$\\tfrac12 m v^2 = e\\Delta V$, $v=\\sqrt{2(1.60\\mathrm{e}{-19})(250)/1.67\\mathrm{e}{-27}} = 2.19\\times 10^5\\,\\mathrm{m/s}$.",
      units: "m/s, nonrelativistic (ok at this energy).",
      interpretation: "250 eV is tiny compared with $mc^2$, so classical mechanics is appropriate.",
      whyAlternativesFail: "Using electron mass, or $v=V/d$ with a missing $d$, or $qV=mv$.",
    },
    fadedExample: {
      situation: "Particle with $q=+2e$, $K_i=4.0\\,\\mathrm{eV}$, moves to a region where $V$ is 3.0 V higher.",
      steps: [
        { prompt: "$\\Delta U$?", hint: "$q\\Delta V$.", expected: "$+6.0\\,\\mathrm{eV}$." },
        { prompt: "Can it arrive?", hint: "Energy conservation.", expected: "No. It needs 6 eV of kinetic energy and has only 4 eV; it turns around (in a conservative 1-D picture)." },
      ],
    },
    independentItemIds: ["u9-cons-1"],
    retrievalItemId: "u9-cons-r",
    videoAlt: "A proton and an electron are released from rest in the same field. They accelerate opposite ways. Energy bar charts use qV with opposite signs.",
  },
];

export const UNIT10_LESSONS: Lesson[] = [
  {
    id: "u10-conductor-equilibrium",
    slug: "conductors-in-equilibrium",
    title: "Electrostatic equilibrium in conductors",
    unit: 10,
    topics: ["10.1"],
    objectives: ["10.1.A"],
    capability: "Use $E=0$ inside conducting material and place excess charge on surfaces.",
    prereqs: ["u8-gauss-sphere", "u9-potential"],
    minutes: [22, 32],
    ...review,
    prediction: {
      prompt: "A solid copper sphere carries net $+Q$ in equilibrium. Inside the metal, $E$ is",
      choices: [
        { id: "A", text: "the Coulomb field of $+Q$ as if at the centre." },
        { id: "B", text: "zero.", correct: true },
        { id: "C", text: "zero only at the centre." },
        { id: "D", text: "$\\sigma/\\varepsilon_0$ throughout the volume." },
      ],
      explanation: "In electrostatic equilibrium the field in the conducting material is zero. Excess charge resides on the outer surface. Inside a solid conductor there is no cavity, so $E=0$ everywhere in the copper.",
    },
    explanation: {
      model: "Free charges move until the net field in the material vanishes. That typically takes a tiny fraction of a second in metals.",
      represent: "Draw $\\sigma$ on the outer surface. If a cavity contains charge $q$, the inner surface carries $-q$.",
      derive: "Gaussian surface embedded in the metal: $E=0\\Rightarrow Q_{\\mathrm{enc}}=0$. Hence charge on an empty cavity\u2019s inner wall is zero; net charge on a solid conductor is on the outer surface.",
      check: "The conductor is an equipotential volume, not necessarily $V=0$.",
      explain: "$E=0$ does not mean $Q=0$. A charged conductor still has surface charge and exterior field.",
    },
    workedExample: {
      title: "Cavity with a charge",
      situation: "A conducting shell has a point charge $+q$ in its empty cavity. The shell\u2019s net charge is $+Q$. Find charges on inner and outer surfaces.",
      assumptions: ["Equilibrium; no charge in the cavity except $+q$."],
      derivation: "Gaussian surface in the metal: $Q_{\\mathrm{enc}}=0= q + Q_{\\mathrm{inner}}$ so $Q_{\\mathrm{inner}}=-q$. Then $Q_{\\mathrm{outer}} = Q - Q_{\\mathrm{inner}} = Q+q$.",
      units: "Coulombs.",
      interpretation: "The outer surface\u2019s charge is not $Q$ unless $q=0$. The exterior field, far away, looks like total $Q+q$.",
      whyAlternativesFail: "Putting $+Q$ on the outer surface and ignoring induced $-q$ on the inner surface.",
    },
    fadedExample: {
      situation: "Needle-like conductor versus a sphere, same $V$.",
      steps: [
        { prompt: "Where is $\\sigma$ larger?", hint: "Sharp points.", expected: "Near high curvature (the tip)." },
        { prompt: "Where is exterior $E$ larger just outside?", hint: "$E=\\sigma/\\varepsilon_0$ just outside.", expected: "At the tip, promoting corona discharge in air." },
      ],
    },
    independentItemIds: ["u10-cond-1", "u10-cond-2"],
    retrievalItemId: "u10-cond-r",
    videoAlt: "A conductor cutaway shows E=0 in the metal, charge on surfaces, and an interior Gaussian surface with Q_enc=0.",
  },
  {
    id: "u10-connected-conductors",
    slug: "connected-conductors",
    title: "Connected conductors share potential, not charge",
    unit: 10,
    topics: ["10.2"],
    objectives: ["10.2.A"],
    capability: "Find charges on connected conductors using $V$ common and $Q=CV$ or $V=kQ/R$ for spheres.",
    prereqs: ["u10-conductor-equilibrium", "u8-charge-transfer"],
    minutes: [20, 30],
    ...review,
    prediction: {
      prompt: "Two isolated conducting spheres, radii $R$ and $2R$, are connected by a long thin wire. Total charge $Q$. The smaller sphere has",
      choices: [
        { id: "A", text: "charge $Q/2$, because charge is shared equally." },
        { id: "B", text: "charge $Q/3$, the larger taking $2Q/3$.", correct: true },
        { id: "C", text: "charge $2Q/3$, because $E$ is larger on a smaller sphere." },
        { id: "D", text: "zero charge; all charge goes to the larger sphere." },
      ],
      explanation: "For isolated spheres, $V\\approx kQ/R$. Common $V$ means $Q\\propto R$. Smaller sphere: $Q_s = Q/3$. Surface field $kQ/R^2$ is actually larger on the smaller sphere.",
    },
    explanation: {
      model: "A connecting wire makes one conductor: a single potential. Charge flows until $V$ matches. Charge is not a fluid that splits 50\u201350 regardless of size.",
      represent: "$V_1=V_2$, $Q_1+Q_2=Q_{\\mathrm{tot}}$. For spheres far apart, $C\\propto R$.",
      derive: "$Q_1/Q_2 = R_1/R_2$ in that approximation.",
      check: "Far apart ignores the wire and mutual capacitance. Good for a first model.",
      explain: "Equal charge would make the smaller sphere a higher potential, so charge would still flow off it.",
    },
    workedExample: {
      title: "Numeric spheres",
      situation: "$R_1=5.0\\,\\mathrm{cm}$, $R_2=10\\,\\mathrm{cm}$, $Q_{\\mathrm{tot}}=12\\,\\mathrm{nC}$, connected. Find $Q_1$ and $E$ just outside each.",
      assumptions: ["Spheres far apart; isolated pair; vacuum."],
      derivation: "$Q_1=4.0\\,\\mathrm{nC}$, $Q_2=8.0\\,\\mathrm{nC}$. $E_1=kQ_1/R_1^2=1.4\\times 10^4\\,\\mathrm{N/C}$, $E_2=kQ_2/R_2^2=7.2\\times 10^3\\,\\mathrm{N/C}$.",
      units: "C and N/C.",
      interpretation: "More charge on the larger sphere, stronger $E$ on the smaller.",
      whyAlternativesFail: "Equal charges 6 nC each, or using $E=kQ_{\\mathrm{tot}}/R^2$.",
    },
    fadedExample: {
      situation: "A conductor is connected to Earth.",
      steps: [
        { prompt: "What is approximately fixed?", hint: "Earth as a huge conductor.", expected: "$V\\approx 0$ (Earth reference), not necessarily $Q=0$ before connecting." },
        { prompt: "After connecting a charged object to Earth, $Q$ on the object?", hint: "Charge can flow.", expected: "Often nearly 0 for a small object, because $C_{\\mathrm{Earth}}$ is huge \u2014 with caveats about what remains isolated." },
      ],
    },
    independentItemIds: ["u10-conn-1"],
    retrievalItemId: "u10-conn-r",
    videoAlt: "Two spheres of different size are joined by a wire. Charge ticks flow until V matches. E arrows just outside are longer on the small sphere.",
  },
  {
    id: "u10-capacitance",
    slug: "capacitance-from-geometry",
    title: "Capacitance from geometry",
    unit: 10,
    topics: ["10.3"],
    objectives: ["10.3.A"],
    capability: "Define $C=Q/V$ and compute $C$ for a parallel-plate capacitor.",
    prereqs: ["u10-conductor-equilibrium"],
    minutes: [20, 30],
    ...review,
    investigationId: "capacitor",
    prediction: {
      prompt: "Doubling the plate separation of a parallel-plate capacitor, vacuum, fixed geometry otherwise, multiplies $C$ by",
      choices: [
        { id: "A", text: "2." },
        { id: "B", text: "$1/2$.", correct: true },
        { id: "C", text: "4." },
        { id: "D", text: "unchanged, because $C$ is a material property only." },
      ],
      explanation: "$C=\\varepsilon_0 A/d$ for the ideal parallel plate. $C$ depends on geometry (and later $\\kappa$), not on $Q$ or $V$ for a linear capacitor.",
    },
    explanation: {
      model: "Capacitance tells how much charge a conductor pair stores per volt. It is a property of the arrangement, in the linear regime.",
      represent: "Two conductors, $\\pm Q$, potential difference $V$. $C=Q/V$.",
      derive: "Parallel plates: $E=\\sigma/\\varepsilon_0=Q/(\\varepsilon_0 A)$, $V=Ed$, so $C=\\varepsilon_0 A/d$.",
      check: "Farads. $C$ is huge if $d$ is tiny; the model fails if $d$ is not small compared with plate size (fringing) or is atomic.",
      explain: "$C$ does not \u201cbecome larger because you applied more voltage.\u201d If $V$ doubles at fixed $C$, $Q$ doubles.",
    },
    workedExample: {
      title: "Numeric plates",
      situation: "$A=0.020\\,\\mathrm{m}^2$, $d=1.0\\,\\mathrm{mm}$. Find $C$ and $Q$ if $V=12\\,\\mathrm{V}$.",
      assumptions: ["Vacuum; neglect fringing."],
      derivation: "$C=\\varepsilon_0 A/d = 1.77\\times 10^{-10}\\,\\mathrm{F}$. $Q=CV=2.12\\times 10^{-9}\\,\\mathrm{C}$.",
      units: "F and C.",
      interpretation: "A 177 pF capacitor. Everyday capacitors use larger $A/d$ or dielectrics.",
      whyAlternativesFail: "$C=\\varepsilon_0 Ad$, $C=\\varepsilon_0 A d$, or using $E=\\sigma/(2\\varepsilon_0)$ as if each plate were an isolated sheet in the two-sheet superposition sense incorrectly for conductors.",
    },
    fadedExample: {
      situation: "Coaxial cylinders (enrichment-adjacent; mark if beyond a given course sheet).",
      steps: [
        { prompt: "Is $C=\\varepsilon_0 A/d$ valid?", hint: "Geometry.", expected: "No. That formula is the parallel-plate idealisation. Coax uses $C=2\\pi\\varepsilon_0 L / \\ln(b/a)$." },
      ],
    },
    independentItemIds: ["u10-cap-1"],
    retrievalItemId: "u10-cap-r",
    videoAlt: "Plates move apart; C falls. Charge on an isolated capacitor stays put while V rises. A connected battery keeps V fixed while Q falls.",
  },
  {
    id: "u10-stored-energy",
    slug: "energy-in-a-capacitor",
    title: "Stored energy: what stays fixed?",
    unit: 10,
    topics: ["10.3"],
    objectives: ["10.3.B"],
    capability: "Choose $U=\\tfrac12 CV^2$ or $Q^2/(2C)$ according to whether $V$ or $Q$ is fixed.",
    prereqs: ["u10-capacitance"],
    minutes: [22, 32],
    ...review,
    investigationId: "capacitor",
    prediction: {
      prompt: "A capacitor remains connected to a battery while $d$ increases. The stored energy",
      choices: [
        { id: "A", text: "increases, because $C$ decreases and $U=Q^2/(2C)$." },
        { id: "B", text: "decreases, because $V$ is fixed and $C$ decreases.", correct: true },
        { id: "C", text: "is unchanged; energy is stored in the metal." },
        { id: "D", text: "becomes negative." },
      ],
      explanation: "Battery connected: $V$ fixed. $U=\\tfrac12 C V^2$ falls with $C$. Using $Q^2/(2C)$ would require updating $Q=CV$ first; then $U$ still falls. Charge is not fixed.",
    },
    explanation: {
      model: "Energy $U=\\tfrac12 QV = Q^2/(2C) = \\tfrac12 C V^2$. Equivalent only when you use consistent $Q$, $C$, $V$. The field stores $u=\\tfrac12 \\varepsilon_0 E^2$ in vacuum.",
      represent: "Before changing geometry, write \u201cbattery connected\u201d ($V$ fixed) or \u201cdisconnected\u201d ($Q$ fixed).",
      derive: "Disconnected, $d$ up: $C$ down, $U=Q^2/(2C)$ up (you do mechanical work pulling plates). Connected, $d$ up: $U$ down (energy returns to the battery).",
      check: "Signs of energy change match the work by the agent plus battery work.",
      explain: "The most expensive mistake in this unit is using the wrong invariant.",
    },
    workedExample: {
      title: "Disconnected plates pulled apart",
      situation: "$C_i=20\\,\\mathrm{pF}$, $V_i=50\\,\\mathrm{V}$, then disconnected, $d$ doubled.",
      assumptions: ["No leakage; vacuum; ideal plates."],
      derivation: "$Q$ fixed $=1.0\\,\\mathrm{nC}$. $C_f=10\\,\\mathrm{pF}$. $U_i=\\tfrac12 C V^2=25\\,\\mathrm{nJ}$. $U_f=Q^2/(2C_f)=50\\,\\mathrm{nJ}$.",
      units: "Joules (here nJ).",
      interpretation: "The agent pulling the plates does 25 nJ of work.",
      whyAlternativesFail: "Keeping $V=50\\,\\mathrm{V}$ after disconnect, or claiming energy is conserved without the agent.",
    },
    fadedExample: {
      situation: "Battery remains connected, dielectric later (preview).",
      steps: [
        { prompt: "What is fixed when the battery stays?", hint: "The battery\u2019s job.", expected: "$V$." },
        { prompt: "If $C$ increases, $U$?", hint: "$\\tfrac12 CV^2$.", expected: "$U$ increases; the battery supplies energy." },
      ],
    },
    independentItemIds: ["u10-en-1", "u10-en-2"],
    retrievalItemId: "u10-en-r",
    videoAlt: "Two columns: battery connected vs disconnected. Each column tracks Q, V, C, U as d changes. The wrong formula is crossed out in each column.",
  },
  {
    id: "u10-dielectrics",
    slug: "dielectrics",
    title: "Dielectrics with battery connected or not",
    unit: 10,
    topics: ["10.4"],
    objectives: ["10.4.A"],
    capability: "Use $C=\\kappa C_0$ and track $Q$, $V$, $E$, and $U$ when a dielectric is inserted.",
    prereqs: ["u10-stored-energy"],
    minutes: [22, 32],
    ...review,
    investigationId: "capacitor",
    prediction: {
      prompt: "A dielectric $\\kappa=4$ is inserted while the capacitor is isolated (fixed $Q$). The field in the dielectric",
      choices: [
        { id: "A", text: "quadruples." },
        { id: "B", text: "is unchanged, because $Q$ is fixed." },
        { id: "C", text: "falls to $E_0/4$.", correct: true },
        { id: "D", text: "falls to $E_0/2$ by averaging bound charge." },
      ],
      explanation: "Isolated: $Q$ fixed, $C\\to\\kappa C$, $V=Q/C$ falls by $\\kappa$, $E=V/d$ falls by $\\kappa$. Bound charge reduces the net field.",
    },
    explanation: {
      model: "A linear dielectric polarises. Bound surface charge reduces the net $E$ for a given free $Q$. Equivalent description: $C=\\kappa\\varepsilon_0 A/d$.",
      represent: "Label free charge $Q_f$ on the plates. Do not treat bound charge as free charge on the battery.",
      derive: "Connected: $V$ fixed, $Q\\to\\kappa Q_0$, $U\\to\\kappa U_0$. Isolated: $Q$ fixed, $V\\to V_0/\\kappa$, $U\\to U_0/\\kappa$.",
      check: "$\\kappa\\ge 1$ for ordinary dielectrics in this course. $\\kappa=1$ recovers vacuum.",
      explain: "Inserting a dielectric always increases $C$. Whether $U$ rises or falls depends on the constraint.",
    },
    workedExample: {
      title: "Insert $\\kappa=3$, battery connected",
      situation: "$C_0=12\\,\\mathrm{pF}$, $V=24\\,\\mathrm{V}$, then insert $\\kappa=3$ with battery attached.",
      assumptions: ["Fills the gap; linear dielectric; no leakage."],
      derivation: "$C=36\\,\\mathrm{pF}$, $Q=0.86\\,\\mathrm{nC}$ (was $0.29\\,\\mathrm{nC}$), $U=\\tfrac12 CV^2=1.04\\times 10^{-8}\\,\\mathrm{J}$ (was $3.5\\times 10^{-9}\\,\\mathrm{J}$).",
      units: "F, C, J.",
      interpretation: "The battery delivered additional charge and energy.",
      whyAlternativesFail: "Reducing $U$ as if $Q$ were fixed, or leaving $Q$ unchanged with the battery present.",
    },
    fadedExample: {
      situation: "Partial fill (qualitative).",
      steps: [
        { prompt: "If a slab does not fill $d$, is $C=\\kappa C_0$?", hint: "Series combination of dielectric and vacuum gaps.", expected: "No. Treat it as capacitors in series (slab spanning the plates) or parallel (slab covering fraction of $A$), depending on insertion geometry." },
      ],
    },
    independentItemIds: ["u10-di-1"],
    retrievalItemId: "u10-di-r",
    videoAlt: "A dielectric slab slides in. Two scenarios: clips on a battery versus an isolated capacitor. Meters for Q, V, and U update in opposite ways for U.",
  },
];
